### ISSUE TITLE
[Docusaurus v3.4] build error with scaffolded create-docusaurus

### ISSUE THREAD

**Issue by superap101** [facebook/docusaurus#10321]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Installed the vanilla repo with `npx create-docusaurus@latest deepmemory-documentation classic --typescript`
Tried `npm run build` and it fails :
The server build bar finishes.
Then the client bar stops at:
```
● Client █████████████████████████ sealing (92%) asset processing
 TerserPlugin
```

first this repeated many times
```
[WARNING] {"moduleIdentifier":"doc-test\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[5].use[0]!doc-test\\node_modules\\@docusaurus\\utils-common\\lib\\applyTrailingSlash.js","moduleName":"./node_modules/@docusaurus/utils-common/lib/applyTrailingSlash.js","message":"There are multiple modules with names that only differ in casing.\nThis can lead to unexpected behavior when compiling on a filesystem with other case-semantic.\nUse equal casing. Compare these module identifiers:\n* doc-test\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[5].use[0]!doc-test\\node_modules\\@docusaurus\\utils-common\\lib\\applyTrailingSlash.js\n    Used by 1 module(s), i. e.\n    doc-test\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[5].use[0]!doc-test\\node_modules\\@docusaurus\\utils-common\\lib\\index.js\n* doc-test\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[5].use[0]!doc-test\\node_modules\\@docusaurus\\utils-common\\lib\\applyTrailingSlash.js\n    Used by 1 module(s), i. e.\n    doc-test\\node_modules\\babel-loader\\lib\\index.js??ruleSet[1].rules[5].use[0]!doc-test\\node_modules\\@docusaurus\\utils-common\\lib\\index.js"}
```
then:
```
client (webpack 5.93.0) compiled with 12 warnings
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '../../url-loader/dist/cjs' in doc-test\node_modules\loader-runner\lib for build dependencies doesn't lead to expected result 'doc-test\node_modules\url-loader\dist\cjs.js', but to 'doc-test\node_modules\url-loader\dist\cjs.js' instead. Resolving dependencies are ignored for this path.
<w>  at resolve commonjs file ../../url-loader/dist/cjs (expected doc-test\node_modules\url-loader\dist\cjs.js)
<w>  at file dependencies doc-test\node_modules\loader-runner\lib\loadLoader.js
<w>  at file doc-test\node_modules\loader-runner\lib\loadLoader.js
<w>  at file dependencies doc-test\node_modules\loader-runner\lib\LoaderRunner.js
<w>  at file doc-test\node_modules\loader-runner\lib\LoaderRunner.js
<w>  at file dependencies doc-test\node_modules\webpack\lib\NormalModule.js
<w>  at file doc-test\node_modules\webpack\lib\NormalModule.js
<w>  at file dependencies doc-test\node_modules\webpack\lib\LoaderTargetPlugin.js
<w>  at file doc-test\node_modules\webpack\lib\LoaderTargetPlugin.js
<w>  at file dependencies doc-test\node_modules\webpack\lib\index.js
<w>  at file doc-test\node_modules\webpack\lib\index.js
<w>  at file dependencies doc-test\node_modules\@docusaurus\core\lib\webpack\utils.js
<w>  at file doc-test\node_modules\@docusaurus\core\lib\webpack\utils.js
<w>  at file dependencies doc-test\node_modules\@docusaurus\core\lib\webpack\base.js
<w>  at file doc-test\node_modules\@docusaurus\core\lib\webpack\base.js
<w>  at resolve commonjs doc-test\node_modules\@docusaurus\core\lib\webpack\base.js
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving '../../@docusaurus/plugin-content-blog/lib/markdownLoader' in doc-test\node_modules\loader-runner\lib for build dependencies doesn't lead to expected result 'doc-test\node_modules\@docusaurus\plugin-content-blog\lib\markdownLoader.js', but to 'doc-test\node_modules\@docusaurus\plugin-content-blog\lib\markdownLoader.js' instead. Resolving dependencies are ignored for this path.
<w>  at resolve commonjs file ../../@docusaurus/plugin-content-blog/lib/markdownLoader (expected doc-test\node_modules\@docusaurus\plugin-content-blog\lib\markdownLoader.js)
<w>
```

Then this:
```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:54:19)        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doc-test\node_modules\@docusaurus\core\lib\commands\build.js:65:9
    at async mapAsyncSequential (doc-test\node_modules\@docusaurus\utils\lib\jsUtils.js:20:24)      
    at async Command.build (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {    
  [cause]: Error: Docusaurus static site generation failed for 25 paths:
  - "/404.html"
  - "/blog"
  - "/blog/archive"
  - "/blog/first-blog-post"
  - "/blog/long-blog-post"
  - "/blog/mdx-blog-post"
  - "/blog/tags"
  - "/blog/tags/docusaurus"
  - "/blog/tags/facebook"
  - "/blog/tags/hello"
  - "/blog/tags/hola"
  - "/blog/welcome"
  - "/markdown-page"
  - "/docs/category/tutorial---basics"
  - "/docs/category/tutorial---extras"
  - "/docs/intro"
  - "/docs/tutorial-basics/congratulations"
  - "/docs/tutorial-basics/create-a-blog-post"
  - "/docs/tutorial-basics/create-a-document"
  - "/docs/tutorial-basics/create-a-page"
  - "/docs/tutorial-basics/deploy-your-site"
  - "/docs/tutorial-basics/markdown-features"
  - "/docs/tutorial-extras/manage-docs-versions"
  - "/docs/tutorial-extras/translate-your-site"
  - "/"
      at generateStaticFiles (doc-test\node_modules\@docusaurus\core\lib\ssg.js:85:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      ... 5 lines matching cause stack trace ...
      at async Command.build (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {  
    [cause]: AggregateError
        at generateStaticFiles (doc-test\node_modules\@docusaurus\core\lib\ssg.js:86:20)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async executeSSG (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:175:23)   
        at async buildLocale (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:135:31)  
        at async tryToBuildLocale (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:47:13)
        at async doc-test\node_modules\@docusaurus\core\lib\commands\build.js:65:9
        at async mapAsyncSequential (doc-test\node_modules\@docusaurus\utils\lib\jsUtils.js:20:24)  
        at async Command.build (doc-test\node_modules\@docusaurus\core\lib\commands\build.js:63:5) {      [errors]: [
```

I've tried the prerequisite steps, it changes nothing and I get the sames errors.

Since this is an unaltered install, I really don't know what the problem is.

### Steps to reproduce

1. `npx create-docusaurus@latest deepmemory-documentation classic --typescript`
2. `npm run build`

### Expected behavior

The build to succeed and be able to start learning how to use the lib.

### Actual behavior

Error mentioned above occurs.

### Your environment

- Docusaurus version used:
  - "@docusaurus/core": "3.4.0",
  - "@docusaurus/preset-classic": "3.4.0",
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodejs v20.10.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): windows 10

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Do you have a reproduction? We build scaffolded templates in our CI, and people make new websites everyday, so it must be something specific to your environment.

**Comment by superap101** [comment]
Hi @Josh-Cena I've tried creating one on https://docusaurus.new/ but since I've modified nothing, I'm not able to reproduce.
I've compared the package.json, docusaurus.config.ts,  babel.config.js in my project with the one on sandbox and they are similar.
Only difference is the node version.

**Comment by Josh-Cena** [comment]
It could also be specific to Windows. Unfortunately I don't think we have access to a Windows system and our Windows CI is working, so there's no way for us to investigate.

**Comment by superap101** [comment]
Thanks @Josh-Cena  for your quick reply.
I don't think I'll be able to solve it on my own (too junior), I'll close the issue.
