### ISSUE TITLE
Broken link detection reports valid links inside parens

### ISSUE THREAD

**Issue by B4nan** [facebook/docusaurus#10739]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We have a changelog.md file as part of the markdown content, and it gets flagged as having wrong links for PRs. Those links are inside parens, and the mechanism detects them as wrong because of the trailing paren, thinking it is a part of the link.

### Steps to reproduce

Add this into a markdown file rendered via docusaurus and enable link checking

```md
- Add user.updateLimits ([#595](https://github.com/apify/apify-client-js/pull/595)) ([bf97c0f](https://github.com/apify/apify-client-js/commit/bf97c0f5bf8d0cbd8decb60382f0605243b00dd5)) by [@MFori](https://github.com/MFori), closes [#329](https://github.com/apify/apify-client-js/issues/329)
```

### Expected behavior

Links can be wrapped in parens and wont trigger this validation.

### Actual behavior

Such links result in broken builds:

```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:78:15)
    at async /Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
    ... 4 lines matching cause stack trace ...
    at async file:///Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Docusaurus found broken links!
  
  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
  
  It looks like some of the broken links we found appear in many pages of your site.
  Maybe those broken links appear on all pages through your site layout?
  We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
  Frequent broken links are linking to:
  - %5B#595%5D(https://github.com/apify/apify-client-js/pull/595)
  - %5B#602%5D(https://github.com/apify/apify-client-js/pull/602)
  - %5B#604%5D(https://github.com/apify/apify-client-js/pull/604)
  
  Exhaustive list of all broken links found:
  - Broken link on source page path = /api/client/js/docs/2.6/changelog:
     -> linking to %5B#595%5D(https://github.com/apify/apify-client-js/pull/595) (resolved as: /api/client/js/docs/2.6/%5B#595%5D(https://github.com/apify/apify-client-js/pull/595))
     -> linking to %5B#602%5D(https://github.com/apify/apify-client-js/pull/602) (resolved as: /api/client/js/docs/2.6/%5B#602%5D(https://github.com/apify/apify-client-js/pull/602))
     -> linking to %5B#604%5D(https://github.com/apify/apify-client-js/pull/604) (resolved as: /api/client/js/docs/2.6/%5B#604%5D(https://github.com/apify/apify-client-js/pull/604))
  - Broken link on source page path = /api/client/js/docs/2.7/changelog:
     -> linking to %5B#595%5D(https://github.com/apify/apify-client-js/pull/595) (resolved as: /api/client/js/docs/2.7/%5B#595%5D(https://github.com/apify/apify-client-js/pull/595))
     -> linking to %5B#602%5D(https://github.com/apify/apify-client-js/pull/602) (resolved as: /api/client/js/docs/2.7/%5B#602%5D(https://github.com/apify/apify-client-js/pull/602))
     -> linking to %5B#604%5D(https://github.com/apify/apify-client-js/pull/604) (resolved as: /api/client/js/docs/2.7/%5B#604%5D(https://github.com/apify/apify-client-js/pull/604))
  - Broken link on source page path = /api/client/js/docs/2.8/changelog:
     -> linking to %5B#595%5D(https://github.com/apify/apify-client-js/pull/595) (resolved as: /api/client/js/docs/2.8/%5B#595%5D(https://github.com/apify/apify-client-js/pull/595))
     -> linking to %5B#602%5D(https://github.com/apify/apify-client-js/pull/602) (resolved as: /api/client/js/docs/2.8/%5B#602%5D(https://github.com/apify/apify-client-js/pull/602))
     -> linking to %5B#604%5D(https://github.com/apify/apify-client-js/pull/604) (resolved as: /api/client/js/docs/2.8/%5B#604%5D(https://github.com/apify/apify-client-js/pull/604))
  - Broken link on source page path = /api/client/js/docs/next/changelog:
     -> linking to %5B#595%5D(https://github.com/apify/apify-client-js/pull/595) (resolved as: /api/client/js/docs/next/%5B#595%5D(https://github.com/apify/apify-client-js/pull/595))
     -> linking to %5B#602%5D(https://github.com/apify/apify-client-js/pull/602) (resolved as: /api/client/js/docs/next/%5B#602%5D(https://github.com/apify/apify-client-js/pull/602))
     -> linking to %5B#604%5D(https://github.com/apify/apify-client-js/pull/604) (resolved as: /api/client/js/docs/next/%5B#604%5D(https://github.com/apify/apify-client-js/pull/604))
  - Broken link on source page path = /api/client/js/docs/changelog:
     -> linking to %5B#595%5D(https://github.com/apify/apify-client-js/pull/595) (resolved as: /api/client/js/docs/%5B#595%5D(https://github.com/apify/apify-client-js/pull/595))
     -> linking to %5B#602%5D(https://github.com/apify/apify-client-js/pull/602) (resolved as: /api/client/js/docs/%5B#602%5D(https://github.com/apify/apify-client-js/pull/602))
     -> linking to %5B#604%5D(https://github.com/apify/apify-client-js/pull/604) (resolved as: /api/client/js/docs/%5B#604%5D(https://github.com/apify/apify-client-js/pull/604))
  
      at throwError (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/logger/lib/logger.js:80:11)
      at reportBrokenLinks (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:250:47)
      at handleBrokenLinks (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:282:5)
      at executeBrokenLinksCheck (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/buildLocale.js:91:47)
      at /Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/buildLocale.js:70:67
      at Object.async (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/logger/lib/perfLogger.js:42:47)
      at buildLocale (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/buildLocale.js:70:31)
      at async runBuildLocaleTask (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:93:5)
      at async /Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:74:13
      at async tryToBuildLocale (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:70:9)
      at async /Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
      at async mapAsyncSequential (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
      at async Command.build (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/build/build.js:33:5)
      at async Promise.all (index 0)
      at async runCLI (/Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/lib/commands/cli.js:56:5)
      at async file:///Users/adamek/htdocs/apify/apify-client-js/website/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3
}
[INFO] Docusaurus version: 3.6.3
Node version: v22.12.0
```

### Your environment

Here is a failed job in our CI, it uses older docusaurus and node versions, but I've tried it locally with node 22.12 and docusaurus 3.6.3, with the same outcome.

https://github.com/apify/apify-client-js/actions/runs/12069278020/job/33656193940

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by OzakIOne** [comment]
I tried a minimal repro of your problem and couldn't get Docusaurus to fail https://stackblitz.com/edit/github-upgr1x?file=docs%2Fintro.md,docusaurus.config.js 

It's been a long time since I've done this so there may be something I'm missing ?

**Comment by slorber** [comment]
This is a bug in `@apify/docusaurus-plugin-typedoc-api`

Your generated changelog files contain syntax such as:

```md
- Add user.updateLimits ([#595]([#595](https://github.com/apify/apify-client-js/pull/595))) ([bf97c0f](https://github.com/apify/apify-client-js/commit/bf97c0f5bf8d0cbd8decb60382f0605243b00dd5)) by [@MFori](https://github.com/MFori)
```

which is wrong and different from what you expected/provided:

```md
- Add user.updateLimits ([#595](https://github.com/apify/apify-client-js/pull/595)) ([bf97c0f](https://github.com/apify/apify-client-js/commit/bf97c0f5bf8d0cbd8decb60382f0605243b00dd5)) by [@MFori](https://github.com/MFori)
```

You can see for yourself the result in the MDX playground:

![CleanShot 2024-12-05 at 18 57 12@2x](https://github.com/user-attachments/assets/07d29827-1e1a-4f2b-ae50-a3298b4215c9)
