### ISSUE TITLE
A filename causes crash at build

### ISSUE THREAD

**Issue by rzippo** [facebook/docusaurus#10744]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

I have a part of my docs organized with the following structure
```
- Esercitazioni
      - 1. Esercitazione 1.mdx
      - 2. Esercitazione 2.mdx
      - 3. Esercitazione 3.mdx
      - 4. Esercitazione 4.mdx
      - 5. Esercitazione 5.mdx
```
This was fine until `4. Esercitazione 4.mdx`. When I added the last file, I started having crashes when running `docusaurus build`, with these relevant lines

```
[cause]: ReactContextError
              at useDocsVersion (server.bundle.js:32793:128)        
              at DocVersionBanner (server.bundle.js:34427:1161)     
              at Uc (server.bundle.js:41905:44)
              at Xc (server.bundle.js:41907:253)
              at Z (server.bundle.js:41913:89)
              at Yc (server.bundle.js:41916:98)
              at $c (server.bundle.js:41915:140)
              at Z (server.bundle.js:41913:345)
              at Yc (server.bundle.js:41916:98)
              at Xc (server.bundle.js:41908:145) {
            message: 'Hook useDocsVersion is called outside the <DocsVersionProvider>. '
```

Note that the development version `docusaurus start` was compiling and running fine.
After fruitless attemps, I found that all I had to change was the file name. The following works fine:
```
- Esercitazioni
      - 1. Esercitazione 1.mdx
      - 2. Esercitazione 2.mdx
      - 3. Esercitazione 3.mdx
      - 4. Esercitazione 4.mdx
      - 5. Esercitazione CINQUE.mdx
```

### Steps to reproduce

I did not try to reproduce with another website or naming structure.

### Expected behavior

It builds fine, like in `docusaurus start` where those names have no effect.

### Actual behavior

I does not build.

### Your environment

- Public source code: none
- Public site URL: https://rzippo.github.io/reti-logiche-esercitazioni
- Docusaurus version used: 3.6.3
- Environment name and version: Node version: v20.18.0
- Operating system and version: Windows 10 22H2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
I'm sorry but we need a repro to troubleshoot these problems. We can't do anything from a public URL only without seeing the code behind it.

The public repo seems to only contain the built Docusaurus files, not its sources: https://github.com/rzippo/reti-logiche-esercitazioni

We'll re-open once a repro is provided

**Comment by rzippo** [comment]
The problem appeared again when `6. Esercitazione 6.mdx` was added. The error this time is

```
[ERROR] Error: Unable to build website for locale it.
    at tryToBuildLocale (C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\node_modules\@docusaurus\core\lib\commands\build\build.js:78:15)
    at async C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\node_modules\@docusaurus\core\lib\commands\build\build.js:34:9
    at async mapAsyncSequential (C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\node_modules\@docusaurus\utils\lib\jsUtils.js:21:24)
    at async Command.build (C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\node_modules\@docusaurus\core\lib\commands\build\build.js:33:5)
    at async Promise.all (index 0)
    at async runCLI (C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\node_modules\@docusaurus\core\lib\commands\cli.js:56:5)
    at async file:///C:/GitHubDocs/reti-logiche-esercitazioni-dispensa/docusaurus/reti-logiche-esercitazioni/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: [Error: ENOTEMPTY: directory not empty, rmdir 'C:\GitHubDocs\reti-logiche-esercitazioni-dispensa\docusaurus\reti-logiche-esercitazioni\build\__server'] {
    errno: -4051,
    code: 'ENOTEMPTY',
    syscall: 'rmdir',
    path: 'C:\\GitHubDocs\\reti-logiche-esercitazioni-dispensa\\docusaurus\\reti-logiche-esercitazioni\\build\\__server'
  }
}
```
Again, renaming the file to `6. Esercitazione SEI.mdx` fixed the issue.

**Comment by slorber** [comment]
Can't help without a repro

The error is totally different in your last stacktrace
