### ISSUE TITLE
Don't show error messages for prismjs missing languages

### ISSUE THREAD

**Issue by iRoachie** [facebook/Docusaurus#1076]
## 💥 Proposal

Currently, it's possible to use `usePrism: true` to set prismjs as the syntax highlighter for all languages. However when a language that prismjs doesn't support is used, the errors are logged to console. Personally think this could be done much better.

```
 Error: Cannot find module 'prismjs/components/prism-html.min'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.require (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:52:17)
    at Object.rules.fence (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/rules.js:73:37)
    at Renderer.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/renderer.js:71:39)
    at Remarkable.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/index.js:152:24)
    at MarkdownRenderer.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:103:26)
    at toHtml (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:113:43) code: 'MODULE_NOT_FOUND' }
```

References https://github.com/facebook/Docusaurus/pull/735#issuecomment-395484508

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Shriram-Balaji** [comment]
@endiliey I'd like to take this up. Do you have something in mind, of how we can do better here? It looks like the error is thrown from `              require(`prismjs/components/prism-${language}.min`);
`

**Comment by endiliey** [comment]
Instead of throwing the error stack. Lets log that the language is not supported.

Any other idea is welcomed
