### ISSUE TITLE
Unable to run under node 6

### ISSUE THREAD

**Issue by cmdcolin** [facebook/Docusaurus#1102]
Hi there, I am encountering an error running docusaurus build under node 6

Basically there is code like this currently in docusaurus

```
console.log(
    chalk.red('hello world'),
);
```

And this gives an error with something like this

```
$ docusaurus-build
/home/travis/build/proj/proj/website/node_modules/docusaurus/lib/build-files.js:31
  );
  ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by cmdcolin** [comment]
Okay. Guess I missed that. Is there any way to warn about this because a mysterious syntax error can kind of waste a bunch of time...it only showed up on travis-CI and confused me a fair amount.
