### ISSUE TITLE
Unable to build versioned and translated site with docs in subdirs after adding a new headerLink

### ISSUE THREAD

**Issue by robbiet480** [facebook/Docusaurus#1395]
## 🐛 Bug Report

Unable to build versioned and translated site with docs in subdirs after adding a new headerLink.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a new site
1. Put docs into subfolders of `docs`
1. Set some of those docs to be headerLinks
1. Enable translation
1. Enable versioning
1. Cut a version
1. Change headerLinks
1. Unable to build or preview the site because internal IDs either have a language prepended or a version prepended.

## Expected behavior

I expected to be able to add headerLinks after cutting a version of a translated site.

## Actual Behavior

Build fails with this error:

```
Error: Processing the following `doc` field in `headerLinks` within `siteConfig.js`: 'misc/index'. Check the spelling of your `doc` field. If that seems sane, and a document in your docs folder exists with that `id` value,
then this is likely a bug in Docusaurus. Docusaurus thinks one or both of translations (currently set to: true) or versioning (currently set to: true) is enabled when maybe they should not be.
Thus my internal id for this doc is: 'en-version-1.0.0-misc/index'. Please file an issue for this possible bug on GitHub.
    at HeaderNav.makeLinks (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:192:15)
    at Array.map (<anonymous>)
    at HeaderNav.map [as renderResponsiveNav] (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:287:26)
    at HeaderNav.renderResponsiveNav [as render] (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/docusaurus/lib/core/nav/HeaderNav.js:328:19)
    at processChild (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
    at resolve (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at renderToStaticMarkupWithDoctype (/Users/robbiet480/Repos/HomeAssistant/home-assistant-companion-docs/website/node_modules/docusaurus/lib/server/renderUtils.js:16:48)
```

## Reproducible Demo

Commit that broke my repo is https://github.com/home-assistant/companion.home-assistant/commit/4991ea09ad685698ee048773e54ae0324e22078a. You can grab repo at that point to be able to reproduce easily. Netlify build log for the commit can be found [here](https://app.netlify.com/sites/home-assistant-companion-docs/deploys/5cc2b30ee91c180008ee3a91). All commits after this are broken with the same error.

**Comment by robbiet480** [comment]
For those experiencing this issue in the future, @endiliey was kind enough to help me out on Discord. The problem is that headerLinks aren't versioned, so if you add a headerLink after a version is cut you must make that page available to the previous version as well. So copy the page you created into the version directory and add a `id` and `original_id` to the front matter just like the other versioned docs also have. Then you should be good to go.
