### ISSUE TITLE
[TRAVIS] TypeError on SVG during docusaurus-publish 

### ISSUE THREAD

**Issue by RoiArthurB** [facebook/docusaurus#1919]
## 🐛 Bug Report

During the Travis build of the website, the console return a TypeError for every SVG files. The error is not blocking and the website has been generated anyway and it should be related to an update (it was not doing it before).

Below a short log of the error, and here's a link to the full build : https://travis-ci.org/gama-platform/gama-platform.github.io/builds/604853476

```
$ docusaurus-publish
HEAD
https://github.com/gama-platform/gama-platform.github.io.git
generate.js triggered...
sitemap.js triggered...
TypeError: Error in file: /home/travis/build/gama-platform/gama-platform.github.io/website/static/img/apple-logo.svg

Cannot set property 'multipassCount' of undefined
    at optimizeOnceCallback (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo.js:41:37)
    at /home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo.js:71:9
    at SAXParser.sax.onend (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo/svg2js.js:169:13)
    at emit (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/sax/lib/sax.js:624:35)
    at end (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/sax/lib/sax.js:667:5)
    at SAXParser.write (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/sax/lib/sax.js:975:14)
    at SAXParser.close (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo/svg2js.js:182:28)
    at SVGO._optimizeOnce (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo.js:63:5)
    at Promise (/home/travis/build/gama-platform/gama-platform.github.io/website/node_modules/svgo/lib/svgo.js:56:14)
TypeError: Error in file: /home/travis/build/gama-platform/gama-platform.github.io/website/static/img/linux-logo.svg
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Create any Docusaurus (template) website
2. Add a SVG file in website/static/
3. Build it in Travis
4. See the error

## Expected behavior

The website is still properly generated so the expected behavior is reached, but I'm scared about the error logs anyway.. 🙊

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

**Comment by moozzyk** [comment]
https://github.com/svg/svgo/issues/1180

**Comment by endiliey** [comment]
dependencies.
