### ISSUE TITLE
bug(v2): unable to build site when swizzling components (when src/theme/NotFound.js is present)

### ISSUE THREAD

**Issue by yangshun** [facebook/docusaurus#2244]
## 🐛 Bug Report

If a user swizzles `NotFound.js` as `src/theme/NotFound.js`, `yarn build` will fail.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Use this [branch](https://github.com/facebook/docusaurus/tree/repro-2244/website-build-fail)
1. In `website-build-fail`, run `yarn build`

**OR**

1. Create a new Docusaurus 2 site
1. Add `src/theme/NotFound.js`
1. Use this content:

```
import React from 'react';
import Layout from '@theme/Layout';

function NotFound() {
  return <Layout title="Page Not Found">Not Found</Layout>;
}

export default NotFound;
```

Run `yarn build`

## Expected behavior

Site builds

## Actual Behavior

Get the error:

```
# yangshun @ yangshun-mbp in ~/Developer/tech-interview-handbook/website on git:master x [1:39:54] 
$ yarn build
yarn run v1.16.0
$ docusaurus build
Creating an optimized production build...

✔ Client
  Compiled successfully in 22.34s

✖ Server
  Compiled with some errors in 24.70s

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`


TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Array.reduce (<anonymous>)TypeError: Cannot convert undefined or null to object
    ...
(undefined) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at main:24269:12
    at Array.reduce (<anonymous>)
    at getBundles (main:24268:20)
    at render (main:49334:113)
    at <anonymous>
(undefined) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at main:24269:12
    at Array.reduce (<anonymous>)
    at getBundles (main:24268:20)
    at render (main:49334:113)
    at <anonymous>
    ...
Error: Failed to compile with errors.
    at compiler.run (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/@docusaurus/core/lib/commands/build.js:37:24)
    at finalCallback (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at runWithDependencies.err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/MultiCompiler.js:277:6)
    at done (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/MultiCompiler.js:188:7)
    at compiler.run (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/MultiCompiler.js:270:7)
    at finalCallback (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compiler.js:273:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compiler.js:271:21)
    at hooks.afterCompile.callAsync.err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compiler.js:678:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/webpack/lib/Compilation.js:1423:35)
    at _err0 (eval at create (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at tryCatcher (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/@endiliey/static-site-generator-webpack-plugin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Users/yangshun/Developer/tech-interview-handbook/website/node_modules/@endiliey/static-site-generator-webpack-plugin/node_modules/bluebird/js/release/nodeify.js:23:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Observations

- Happens for all swizzled components, not just `src/theme/NotFound`. `src/theme/Footer` can result in the same issue
- The crash is in `react-loadable-ssr-addon/lib/getBundles.js`. I suspect this problem is related to https://github.com/themgoncalves/react-loadable-ssr-addon/issues/8

**Comment by lex111** [comment]
@yangshun are you sure that this error is due to the NotFound component? The fact is that v2 uses its own NotFound component and the website is building without errors

https://github.com/facebook/docusaurus/blob/master/website/src/theme/NotFound.js

**Comment by yangshun** [comment]
@lex111 yes, I can't confirm whether only NotFound triggers this error but I can confirm swizzling NotFound will cause it. I'll try with swizzling other components as well.

> The fact is that v2 uses its own NotFound component and the website is building without errors

I'm aware of that, hence I'm puzzled. Maybe using the npm version of Docusaurus has some subtle differences than using the monorepo's version.

**Comment by yangshun** [comment]
I can confirm that this breaks for all swizzled components, not just `src/theme/NotFound`. I tried with `src/theme/Footer` as well.

**Comment by yangshun** [comment]
⚠️ However, I also tried with a fresh `npx @docusaurus/init@next` installation but was not able to reproduce the issue. This is super weird.

**Comment by prma85** [comment]
I am using it in my doc website (a custom NotFound.js) where the docusaurus is in the root of my repo and it works just fine. Before, when I had my `website` folder, I had the same issue.

**Comment by sserrata** [comment]
I ran into this error only after I swizzled the `DocPage` component (had previously swizzled `DocItem`, `Navbar`, and `CodeBlock`). 

After some troubleshooting, I landed on this issue and decided to try swizzling the `NotFound` component (in addition to `DocPage`). This resolved the issue for me.

**Comment by daldridge-cs** [comment]
Similar to @sserrata , I had to swizzle all three of DocItem, DocPage, and NotFound to avoid the build error.

**Comment by dvanlaeken** [comment]
I'm hitting this issue as well. 

1. Is there any workaround other than swizzling more components? 
2. Is there a way to build without SSR?

**Comment by lex111** [comment]
@yangshun could we close this issue if there is no way to reproduce it?

**Comment by yangshun** [comment]
> could we close this issue if there is no way to reproduce it?

Repro is here https://github.com/facebook/docusaurus/tree/repro-2244/website-build-fail

**Comment by yangshun** [comment]
Fixed in https://github.com/facebook/docusaurus/pull/2854
