### ISSUE TITLE
[v2] (undefined) ReferenceError: command is not defined at MDXContent

### ISSUE THREAD

**Issue by focaaby** [facebook/docusaurus#2268]
## 🐛 Bug Report

It can not be built in Server stage.

```
$ node -v
v13.7.0

$ npm -v
6.13.6
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Run the command `npx @docusaurus/init@next init my-website classic`.
1. Modify the config and add the markdown files.
1. Run the build command `npm build`

## Expected behavior

It should be built successfully.

## Actual Behavior

```
$ npm run build

> ncnu-opensource.github.io@0.0.0 build /Users/focaaby/Project/NCNU-OpenSource.github.io
> docusaurus build

Creating an optimized production build...

✔ Client
  Compiled successfully in 38.09s

✖ Server
  Compiled with some errors in 43.44s



ReferenceError: command is not defined
(undefined) ReferenceError: command is not defined
    at MDXContent (main:14754:931)
    at d (main:23128:498)
    at Za (main:23131:16)
    at a.b.render (main:23136:476)
    at a.b.read (main:23136:18)
    at Object.renderToString (main:23146:364)
    at render (main:40286:252)
Error: Failed to compile with errors.
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/@docusaurus/core/lib/commands/build.js:37:24
    at finalCallback (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/focaaby/Project/NCNU-OpenSource.github.io/node_modules/webpack/lib/Compiler.js:678:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ncnu-opensource.github.io@0.0.0 build: `docusaurus build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ncnu-opensource.github.io@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/focaaby/.npm/_logs/2020-02-05T17_39_04_248Z-debug.log
```
![image](https://user-images.githubusercontent.com/8644704/73868043-bd791980-4882-11ea-85be-97d4c4aa5488.png)

## Reproducible Demo

1. `git clone https://github.com/NCNU-OpenSource/NCNU-OpenSource.github.io.git`
1. `git checkout migrate-theme-to-docusaurus`
1. `npm install`
1. `npm run build`

**Comment by focaaby** [comment]
Thanks for @lex111 !
