### ISSUE TITLE
Bug - Encountering issues with readCategories and sidebar.json

### ISSUE THREAD

**Issue by ericnakagawa** [facebook/Docusaurus#236]
Versioning logic is triggering error message.

```
💎 🕵 :ericnakagawa:17:12:01:[master !x?]:~/Work/draft-js/website: yarn build
Using globally installed version of Yarn
yarn run v1.2.0
warning package.json: No license field
$ docusaurus-build
Extracting translateable strings from files...
Loading translation files...
Generating Metadata for Docs....
Generating Metadata for Docs....
Generating Metadata for Docs....
generate.js triggered...
Generating Metadata for Docs....
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Head`. See https://fb.me/react-warning-keys for more information.
    in script (created by Head)
    in Head (created by Site)
    in html (created by Site)
    in Site (created by DocsLayout)
    in DocsLayout
/Users/ericnakagawa/Work/draft-js/website/node_modules/docusaurus/lib/server/readCategories.js:60
          throw new Error(_metadata2.version ? "Improper sidebars file for version " + _metadata2.version + ". Make sure that all documents with ids specified in this version's sidebar file exist and that no ids are repeated." : "Improper sidebars.json file. Make sure that documents with the ids specified in sidebars.json exist and that no ids are repeated.");
          ^

Error: Improper sidebars.json file. Make sure that documents with the ids specified in sidebars.json exist and that no ids are repeated.
    at _loop (/Users/ericnakagawa/Work/draft-js/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/Users/ericnakagawa/Work/draft-js/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/Users/ericnakagawa/Work/draft-js/website/node_modules/docusaurus/lib/core/DocsSidebar.js:18:26)
    at /Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:793:21
    at measureLifeCyclePerf (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:792:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:819:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:359:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/ericnakagawa/Work/draft-js/website/node_modules/react-dom/lib/ReactReconciler.js:43:35)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
💎 🕵 :ericnakagawa:17:12:05:[master !x?]:~/Work/draft-js/website: 
```

**Comment by endiliey** [comment]
Does this bug still exists @ericnakagawa ?
