### ISSUE TITLE
prism.additionalLanguages broken in v2

### ISSUE THREAD

**Issue by watzon** [facebook/docusaurus#2564]
## 🐛 Bug Report

`themeConfig.prism.additionalLanguages` seems to be broken in the most recent v2 alpha.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

- Create a new docusaurus app using `2.0.0-alpha.50`.
- In `docusaurus.config.js` within `themeConfig` add
  ```json
  prism: {
    additionalLanguages: [ 'crystal' ] // Or any language
  }
  ```
- Run `npm start`

## Expected behavior

Things should build correctly and syntax highlighting should work with the requested language

## Actual Behavior

The following error is shown in the teminal:

```
TypeError: Cannot read property 'originalSource' of undefined
    at getSourceById (/home/username/projectname/node_modules/react-dev-utils/evalSourceMapMiddleware.js:18:17)
    at handleWebpackInternalMiddleware (/home/username/projectname/node_modules/react-dev-utils/evalSourceMapMiddleware.js:37:22)
    at Layer.handle [as handle_request] (/home/username/projectname/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/username/projectname/node_modules/express/lib/router/index.js:317:13)
    at /home/username/projectname/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/username/projectname/node_modules/express/lib/router/index.js:335:12)
    at next (/home/username/projectname/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/username/projectname/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:315:20)
    at SendStream.error (/home/username/projectname/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/username/projectname/node_modules/send/index.js:421:12)
    at next (/home/username/projectname/node_modules/send/index.js:735:16)
    at onstat (/home/username/projectname/node_modules/send/index.js:724:14)
    at FSReqCallback.oncomplete (fs.js:171:21)
```

## Your Environment

- Docusaurus version used: `2.0.0-alpha.50`
- Environment name and version :
  - `Mozilla Firefox 74.0.1`
  - `NodeJS v13.12.0` (also tried with 12, 11, and 10)
- Operating system and version (desktop or mobile): `Arch Linux 5.5.13-arch2-1`

## Reproducible Demo

https://github.com/watzon/dousaurus-testapp

Literally a brand new app with the aforementioned section added to the config.

**Comment by lex111** [comment]
I cannot reproduce with similar errors, but Crystal syntax highlighting really will not work like that, because you still need to include Ruby, because Crystal extends it's syntax (this is done in Prism)

```diff
- additionalLanguages: ['crystal'],
+ additionalLanguages: ['ruby', 'crystal'],
```

**Comment by watzon** [comment]
@lex111 I tried that as well. I still get the same error in the terminal, and in the browser console I get `Error: Cannot find module './prism-ruby'`.

**Comment by watzon** [comment]
Weird. It works when I deploy to zeit, just not locally. So it has to be a system issue.

**Comment by watzon** [comment]
Ok well I got it working locally. I was using asdf to version node, so I uninstalled the asdf node plugin and installed node using my system package manager. Now things work.

**Comment by fdmmarshall** [comment]
I am having a similar issue when trying to add `'sparql'` to the `additionalLanguages` array. Below is the error I am receiving:

```
Uncaught TypeError: Cannot set property 'boolean' of undefined
    at Object.extend (index.js?4953:86)
    at eval (prism-sparql.js?7063:1)
    at Object../node_modules/prismjs/components/prism-sparql.js (main.js:362)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at webpackContext (main.js:377)
    at eval (prism-include-languages.js?fcbd:6)
    at Array.forEach (<anonymous>)
    at prismIncludeLanguages (prism-include-languages.js?fcbd:6)
    at eval (prism-include-languages.js?67c1:6)
    at Module../node_modules/@docusaurus/theme-classic/lib/prism-include-languages.js (main.js:237)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at eval (client-modules.js?5edc:1)
    at Module../.docusaurus/client-modules.js (main.js:23)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at eval (client-lifecycles-dispatcher.js:5)
    at Module../node_modules/@docusaurus/core/lib/client/client-lifecycles-dispatcher.js (main.js:79)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at eval (PendingNavigation.js:9)
    at Module../node_modules/@docusaurus/core/lib/client/PendingNavigation.js (main.js:63)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at eval (App.js:14)
    at Module../node_modules/@docusaurus/core/lib/client/App.js (main.js:55)
    at __webpack_require__ (runtime~main.js:36)
    at fn (runtime~main.js:340)
    at eval (clientEntry.js:7)
    at Module../node_modules/@docusaurus/core/lib/client/clientEntry.js (main.js:87)
    at __webpack_require__ (runtime~main.js:36)
    at __webpack_exec__ (main.js:772)
    at main.js:773
    at Function.__webpack_require__.O (runtime~main.js:83)
    at main.js:774
    at webpackJsonpCallback (runtime~main.js:1313)
    at main.js:9```
    
    Any advice would be greatly appreciated.

**Comment by afshinm** [comment]
Fix for `scala`:

```
     prism: {
       additionalLanguages: ['java', 'scala'],
     },
```

**Comment by dswiecki** [comment]
in fact I needed to add this to work
```     prism: {
       additionalLanguages: ['clike', 'java', 'scala'],
     }
```
becouce of 
``` Prism.languages.java = Prism.languages.extend('clike', {
```

**Comment by Josh-Cena** [comment]
`clike` should be enabled by Prism by default: https://github.com/FormidableLabs/prism-react-renderer/blob/4d8019490a3ad89c310d877a9ae3130084261bc9/src/vendor/prism/includeLangs.js#L9

Does it not work without that?

**Comment by blacktop** [comment]
Is there a fix for `armasm` ?

**Comment by coswat** [comment]
what about php guys ? its not working

**Comment by franck-grenier** [comment]
Same for me, PHP not working with error in console: 

```
Uncaught Error: Cannot find module './prism-php.js'
```

My config: 

```
prism: {
    theme: lightCodeTheme,
    darkTheme: darkCodeTheme,
    additionalLanguages: ['php'],
},
 ```

**Comment by coswat** [comment]
@franck-grenier i solved the issue by restarting the devlopment server

**Comment by waldyrious** [comment]
Just in case someone else ends up here with the same issue that I had, I'll quote the comment from @ArthurFlag [here](https://github.com/facebook/docusaurus/issues/5443#issuecomment-908555172):

> I do not use scala anywhere, but your suggestion fixed it.

Indeed, I too don't use have any scala code blocks in my docs, but somehow adding scala to the `additionalLanguages` array fixed the `TypeError: Cannot set properties of undefined (setting 'triple-quoted-string')` error that I was having (which I assume is the same as the `Cannot set property 'triple-quoted-string' of undefined` error reported in #5013).
