### ISSUE TITLE
Plugins are broken (Cannot find module '@docusaurus/plugin-google-analytics')

### ISSUE THREAD

**Issue by lumio** [facebook/docusaurus#2866]
## 🐛 Bug Report

Plugins are no longer resolved with docusaurus@2.0.0-alpha.56 (fresh install).
It looks like `import-fresh` does not resolve node modules in `@docusaurus/core/lib/server/plugins/init.js`.

This was working in the past (checked with a fresh clone and 2.0.0-alpha.50). However, removing `node_modules` and yarn.lock/package-lock.json will lead into the same error (see below).

*Workaround below*

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Enable any plugin **(without an absolute path)** in your docusaurus.config.js (e.g. `@docusaurus/plugin-google-analytics`)
2. Start docusaurus

## Expected behavior

The webpage should work as it did before with other versions and load plugins.

## Actual Behavior

Plugins cannot be resolved and throws the following error:

```
Error: Cannot find module '@docusaurus/plugin-google-analytics'
Require stack:
- /Users/.../docusaurus-project
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at /Users/.../docusaurus-project/node_modules/@docusaurus/core/lib/server/plugins/init.js:40:67
    at Array.map (<anonymous>)
    at Object.initPlugins (/Users/.../docusaurus-project/node_modules/@docusaurus/core/lib/server/plugins/init.js:22:10)
    at Object.loadPlugins (/Users/.../docusaurus-project/node_modules/@docusaurus/core/lib/server/plugins/index.js:47:28)
    at Object.load (/Users/.../docusaurus-project/node_modules/@docusaurus/core/lib/server/index.js:57:62)
    at start (/Users/.../docusaurus-project/node_modules/@docusaurus/core/lib/commands/start.js:45:34)
    at /Users/.../docusaurus-project/node_modules/@docusaurus/core/bin/docusaurus.js:29:5
    at Command.<anonymous> (/Users/.../docusaurus-project/node_modules/@docusaurus/core/bin/docusaurus.js:97:23)
    at Command.listener (/Users/.../docusaurus-project/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:196:13)
    at Command.parseArgs (/Users/.../docusaurus-project/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/.../docusaurus-project/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/.../docusaurus-project/node_modules/@docusaurus/core/bin/docusaurus.js:120:5)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
```

**I suspect that `@docusaurus/core` uses an incompatible version of `import-fresh`.**

## Your Environment

- Docusaurus version used: `2.0.0-alpha.56`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
    - Chrome 83.0.4103.61
    - Node.js 12.2.0
- Operating system and version (desktop or mobile):
    - desktop (MacOS 10.15.5)

## Possible solution/workaround

* Lock import-fresh to an older version
* Generate absolute imports in `@docusaurus/core/lib/server/plugins/init.js`
* Generate absolute plugin import in your `docusaurus.config.js` like so

```js
const fix_plugin = (plugin) => path.resolve(__dirname, 'node_modules', plugin);

module.exports = {
  // ...
  plugins: [
    fix_plugin('@docusaurus/plugin-google-analytics'),
    [
      fix_plugin('@docusaurus/plugin-sitemap'),
      {
        cacheTime: 600 * 1000
      }
    ],
  ]
}
```

**Comment by yangshun** [comment]
Please read the release notes. There's a breaking change.

**Comment by lumio** [comment]
Thanks! Weird that I had the same problem with 2.0.0-alpha.50 but resolved nonetheless

**Comment by pbeshai** [comment]
Note this is not mentioned in the [changelog](https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md), but is in the [GitHub releases area](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.56)

**Comment by ioan-ghisoi-cko** [comment]
To save someone a minute:

- plugins: ['@docusaurus/plugin-google-analytics']
+ plugins: [require.resolve('@docusaurus/plugin-google-analytics')]
