### ISSUE TITLE
Cannot find module '../lib'

### ISSUE THREAD

**Issue by zkrami** [facebook/docusaurus#2942]
I am trying to launch my website which depends on an edited package of docusaurus. 

so my dependencies look like this: 

   ` "@docusaurus/core": "file:../docusaurus/packages/docusaurus",`

there is no major changes in the package. 
anyway the project used to work well but now trying to launch it on another machine I got this error. 
```

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Rami\git\studio-website\10StudioWebsite\website\node_modules\@docusaurus\core\bin\docusaurus.js:14:41)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

which correspond to this file 
 
https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/bin/docusaurus.js#L14

the lib file doesn't exit in the package and I don't know where it comes from. 
is there any command I should run to generate this file ?

**Comment by slorber** [comment]
Hi,

Docusaurus 2 is a TS project. 
You have to compile it to obtain the final code that will be run on NodeJS (ie generating the /lib folder).

After compilation, the /lib folder will exist:

![image](https://user-images.githubusercontent.com/749374/84752451-10e03e80-afbe-11ea-88af-3691f0c4b462.png)

At the root of the repo, run `yarn install && yarn tsc` and it should compile everything you might need
