### ISSUE TITLE
Cryptic message regarding language support

### ISSUE THREAD

**Issue by aadsm** [facebook/Docusaurus#309]
After I added my own data to siteConfig.js, I reloaded and got:
> Error: It looks like you've enabled language support, but haven't provided translated files. The document with id: 'en-Overview' doesn't exist.

I didn't enable language support, or if I did it was not explicit. This message doesn't help me figure out what is going on. I believe two things are missing on this message.
1) What makes docusaurus believe I've enabled language support.
2) Link to the documentation pointing to language support.

**Comment by JoelMarcey** [comment]
@aadsm Yeah, I filed a bug today re: how we are dealing with languages overall, particularly when running the `docusaurus-init` script to start off with a sample website.

https://github.com/facebook/Docusaurus/issues/305

Are you starting off with the `site-config.js` that was provided by the `docusaurus-init` script? Or are you creating it from scratch?

**Comment by aadsm** [comment]
I've started with the siteConfig.js provided by the `docusaurus-init`. I figured out what the problem was, the `doc` property is actually an `id` (should probably be named `docId`, yeah, I'm a pain with names 😛).
Once I fixed this I got an exception (I haven't debug yet):
```
TypeError: Cannot read property 'filter' of undefined
    at Index.render (/Users/aadsm/Projects/draft-js/website/node_modules/docusaurus/lib/pages/en/tempindex.js:84:8)
    at /Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:793:21
    at measureLifeCyclePerf (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:792:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:819:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:359:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactCompositeComponent.js:255:21)
    at Object.mountComponent (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactDOMComponent.mountChildren (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactMultiChild.js:234:44)
    at ReactDOMComponent._createContentMarkup (/Users/aadsm/Projects/draft-js/website/node_modules/react-dom/lib/ReactDOMComponent.js:657:32)
```

**Comment by steveklabnik** [comment]
I'm seeing this today too.

**Comment by n7best** [comment]
Having same issues after clone and install from a different computer. But the original doesn't pop up the error.

**Comment by JoelMarcey** [comment]
I think that error is actually misleading. I am working on a fix now.

**Comment by JoelMarcey** [comment]
I got a pull request out. Hopefully the error message is more useful now.
