### ISSUE TITLE
Navbar lable issue

### ISSUE THREAD

**Issue by krishnaUIDev** [facebook/docusaurus#3151]
Need some help with navbar configuration. Currently, I am using the below config for the navbar. In local env, I can see navbar labels. But when I deploy app labels are not displaying. I am not sure what's wrong. 

```javascript
   navbar: {
      hideOnScroll: false,
      title: 'UI-Kit',
      logo: {
        alt: 'UI Kit Logo',
        src: 'img/logo.svg',
        href: 'https://ui-webkit.netlify.app/', 
        target: '_self',
      },
      items: [
        {
          to: '/docs',
          activeBasePath: 'docs',
          label: 'Docs',
          position: 'left',
        },
        {to: '/blog', label: 'Blog', position: 'left'},
        {to: '/Versions', label: 'All versions', position: 'right'},
        {
          href: 'https://github.com/krishnaUIDev/UI-Kit',
          position: 'right',
          className: 'header-github-link',
          'aria-label': 'GitHub Repository',
        },
      ],
    },
```

**Comment by slorber** [comment]
Please include all the needed infos:
- link to your repo (if public)
- link to your deployment
- screenshot of site working locally
- screenshot of site not working in deployment

**Comment by slorber** [comment]
Ok the links on your json seems valid, this is weird.

Have you tried a production build locally, with `docusaurus build` and `docusaurus serve`?

Are you sure your CI has no error and deployed successfully?

**Comment by krishnaUIDev** [comment]
@slorber Please find the details below. 

link to your repo (if public): [(https://github.com/krishnaUIDev/UI-Kit](https://github.com/krishnaUIDev/UI-Kit)
link to your deployment: 

```shell
  5:10:07 PM: Build ready to start
5:10:09 PM: build-image version: ca811f47d4c1cbd1812d1eb6ecb0c977e86d1a1d
5:10:09 PM: build-image tag: v3.3.20
5:10:09 PM: buildbot version: be8ecf2af866e16fa4301cc5c14de2ccbbb21cf4
5:10:09 PM: Fetching cached dependencies
5:10:09 PM: Starting to download cache of 153.6MB
5:10:11 PM: Finished downloading cache in 2.160500713s
5:10:11 PM: Starting to extract cache
5:10:18 PM: Finished extracting cache in 6.944902959s
5:10:18 PM: Finished fetching cache in 9.153802573s
5:10:18 PM: Starting to prepare the repo for build
5:10:19 PM: Preparing Git Reference refs/heads/master
5:10:20 PM: Starting build script
5:10:20 PM: Installing dependencies
5:10:20 PM: Python version set to 2.7
5:10:21 PM: Started restoring cached node version
5:10:23 PM: Finished restoring cached node version
5:10:23 PM: v12.18.0 is already installed.
5:10:24 PM: Now using node v12.18.0 (npm v6.14.4)
5:10:24 PM: Started restoring cached build plugins
5:10:24 PM: Finished restoring cached build plugins
5:10:24 PM: Attempting ruby version 2.7.1, read from environment
5:10:25 PM: Using ruby version 2.7.1
5:10:26 PM: Using PHP version 5.6
5:10:26 PM: 5.2 is already installed.
5:10:26 PM: Using Swift version 5.2
5:10:26 PM: Started restoring cached node modules
5:10:26 PM: Finished restoring cached node modules
5:10:26 PM: Started restoring cached yarn cache
5:10:26 PM: Finished restoring cached yarn cache
5:10:26 PM: Installing NPM modules using Yarn version 1.22.4
5:10:27 PM: yarn install v1.22.4
5:10:27 PM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
5:10:27 PM: [1/4] Resolving packages...
5:10:28 PM: [2/4] Fetching packages...
5:10:50 PM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
5:10:50 PM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
5:10:50 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
5:10:50 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
5:10:50 PM: [3/4] Linking dependencies...
5:10:50 PM: warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
5:10:50 PM: warning " > @docusaurus/plugin-ideal-image@2.0.0-alpha.39" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/plugin-ideal-image > @endiliey/lqip-loader@3.0.2" has unmet peer dependency "file-loader@*".
5:10:50 PM: warning " > @docusaurus/preset-classic@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-content-blog@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-content-docs@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-content-pages@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-debug@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-google-analytics@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-google-gtag@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/plugin-sitemap@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/theme-classic@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia@2.0.0-alpha.58" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia@2.0.0-alpha.58" has unmet peer dependency "@docusaurus/utils@^2.0.0-alpha.54".
5:10:50 PM: warning " > @docusaurus/theme-search-algolia@2.0.0-alpha.32" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning " > docusaurus-plugin-sass@0.1.9" has incorrect peer dependency "@docusaurus/core@^2.0.0".
5:10:50 PM: warning "docusaurus-plugin-sass > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
5:10:50 PM: warning "@storybook/addon-actions > @storybook/api@5.3.19" has unmet peer dependency "regenerator-runtime@*".
5:11:03 PM: [4/4] Building fresh packages...
5:11:05 PM: success Saved lockfile.
5:11:05 PM: Done in 38.52s.
5:11:05 PM: NPM modules installed using Yarn
5:11:05 PM: Started restoring cached go cache
5:11:05 PM: Finished restoring cached go cache
5:11:05 PM: go version go1.14.4 linux/amd64
5:11:05 PM: go version go1.14.4 linux/amd64
5:11:05 PM: Installing missing commands
5:11:05 PM: Verify run directory
5:11:06 PM: ​
5:11:06 PM: ┌─────────────────────────────┐
5:11:06 PM: │        Netlify Build        │
5:11:06 PM: └─────────────────────────────┘
5:11:06 PM: ​
5:11:06 PM: ❯ Version
5:11:06 PM:   @netlify/build 3.0.1
5:11:06 PM: ​
5:11:06 PM: ❯ Flags
5:11:06 PM:   deployId: 5f20942f4738ff0008094d8b
5:11:06 PM:   mode: buildbot
5:11:06 PM: ​
5:11:06 PM: ❯ Current directory
5:11:06 PM:   /opt/build/repo
5:11:06 PM: ​
5:11:06 PM: ❯ Config file
5:11:06 PM:   No config file was defined: using default values.
5:11:06 PM: ​
5:11:06 PM: ❯ Context
5:11:06 PM:   production
5:11:06 PM: ​
5:11:06 PM: ❯ Loading plugins
5:11:06 PM:    - netlify-plugin-is-website-vulnerable@1.0.8 from Netlify app
5:11:10 PM: ​
5:11:10 PM: ┌───────────────────────────────────┐
5:11:10 PM: │ 1. Build command from Netlify app │
5:11:10 PM: └───────────────────────────────────┘
5:11:10 PM: ​
5:11:10 PM: $ npm run build
5:11:10 PM: > ui-kit@1.0.1 build /opt/build/repo
5:11:10 PM: > docusaurus build
5:11:11 PM: Creating an optimized production build...
5:11:12 PM: [info] [webpackbar] Compiling Client
5:11:12 PM: [info] [webpackbar] Compiling Server
5:11:28 PM: [success] [webpackbar] Client: Compiled successfully in 16.58s
5:11:32 PM: [success] [webpackbar] Server: Compiled successfully in 20.48s
5:11:32 PM: Success! Generated static files in build.
5:11:32 PM: ​
5:11:32 PM: (build.command completed in 22.6s)
5:11:32 PM: ​
5:11:32 PM: ┌────────────────────────────────────────────────────────────────┐
5:11:32 PM: │ 2. onSuccess command from netlify-plugin-is-website-vulnerable │
5:11:32 PM: └────────────────────────────────────────────────────────────────┘
5:11:32 PM: ​
5:11:32 PM: Serving and scanning site from directory 'build'
5:11:40 PM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
5:11:40 PM: [DEP0066] 
5:11:40 PM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/response-stream.js:50:60)
5:11:40 PM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/routing-stream.js:30:17)
5:11:40 PM:     at Server.requestHandler (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/core.js:27:25)
5:11:40 PM:     at Server.emit (events.js:310:20)
5:11:40 PM:     at parserOnIncoming (_http_server.js:786:12)
5:11:40 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
5:11:42 PM: No vulnerable JavaScript libraries detected
5:11:42 PM: ​
5:11:42 PM: (netlify-plugin-is-website-vulnerable onSuccess completed in 10.2s)
5:11:42 PM: ​
5:11:42 PM: ┌─────────────────────────────┐
5:11:42 PM: │   Netlify Build Complete    │
5:11:42 PM: └─────────────────────────────┘
5:11:42 PM: ​
5:11:42 PM: (Netlify Build completed in 36s)
5:11:42 PM: Caching artifacts
5:11:42 PM: Started saving node modules
5:11:42 PM: Finished saving node modules
5:11:42 PM: Started saving build plugins
5:11:43 PM: Finished saving build plugins
5:11:43 PM: Started saving yarn cache
5:11:43 PM: Finished saving yarn cache
5:11:43 PM: Started saving pip cache
5:11:43 PM: Finished saving pip cache
5:11:43 PM: Started saving emacs cask dependencies
5:11:43 PM: Finished saving emacs cask dependencies
5:11:43 PM: Started saving maven dependencies
5:11:43 PM: Finished saving maven dependencies
5:11:43 PM: Started saving boot dependencies
5:11:43 PM: Finished saving boot dependencies
5:11:43 PM: Started saving go dependencies
5:11:43 PM: Finished saving go dependencies
5:11:43 PM: Build script success
5:11:43 PM: Starting to deploy site from 'build'
5:11:43 PM: Creating deploy tree 
5:11:43 PM: Creating deploy upload records
5:11:43 PM: 0 new files to upload
5:11:43 PM: 0 new functions to upload
5:11:43 PM: Starting post processing
5:11:43 PM: Post processing - HTML
5:11:43 PM: Post processing - redirect rules
5:11:43 PM: Post processing - header rules
5:11:43 PM: Post processing done
5:11:43 PM: Site is live
5:12:10 PM: Finished processing build request in 2m0.516182418s
```
screenshot of site working locally: 
![local](https://user-images.githubusercontent.com/24648588/88823775-7a459680-d193-11ea-9ea2-b2ec3c72416c.PNG)


screenshot of site not working in deployment
![prod](https://user-images.githubusercontent.com/24648588/88823887-9c3f1900-d193-11ea-8b26-1a508a49e90d.PNG)

Currently, i am using below version. 
```
  "@docusaurus/core": "^2.0.0-alpha.58",
```

**Comment by teikjun** [comment]
![image](https://user-images.githubusercontent.com/46853051/88826124-ef988200-d1fa-11ea-9065-1510aee56802.png)

Hi, this seems to be a version alpha 59 site. Could you double check if you have pushed your local changes to your repository?

**Comment by slorber** [comment]
@krishnaUIDev , the navbar.items was previously navbar.links and renamed in alpha 59.

If you are not seeing navbar items, it's because you are not in alpha 59, and you are trying to use navbar.items while the renaming didn't happen yet 🤪 

Also, you have both a yarn.lock and a package-lock. It is likely that you have differences between local dev and netlify because you use npm locally, and netlify uses yarn.

At some point you have to choose between npm or yarn.

Also, you have versions that do not match here, while they should (use alpha 60, just released for example)

```
    "@docusaurus/core": "^2.0.0-alpha.58",
    "@docusaurus/plugin-ideal-image": "^2.0.0-alpha.39",
    "@docusaurus/preset-classic": "^2.0.0-alpha.58",
    "@docusaurus/theme-search-algolia": "^2.0.0-alpha.32",
```

---

What I'd do:

- update everything to alpha 60
- delete both yarn.lock and package-lock
- decide to use yarn only (add package-lock.json to gitignore)
- yarn install, add new generated yarn.lock to repo
- local and netlify should now both use yarn with alpha 60

**Comment by krishnaUIDev** [comment]
@slorber thanks. Its working as expected.
