### ISSUE TITLE
"Cannot find module '@docusaurus/core/lib/webpack/plugins/LogPlugin'" when trying to add @docusaurus/plugin-pwa

### ISSUE THREAD

**Issue by krillboi** [facebook/docusaurus#3395]
## 🐛 Bug Report

I am trying to use the PWA plugin after upgrading to alpha.62. But now when I try to run `docusaurus start` it fails with the message "Cannot find module '@docusaurus/core/lib/webpack/plugins/LogPlugin'".

I added the plugin by running `yarn add @docusaurus/plugin-pwa`.

Afterwards I created `static/manifest.json` with the following content:

```
{
  "name": "TouchGFX Documentation",
  "short_name": "TGFX Doc",
  "theme_color": "#158EC2",
  "background_color": "#FFFFFF",
  "display": "standalone",
  "scope": "/",
  "start_url": "/",
  "icons": [
    {
      "src": "/img/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png"
    },
    {
      "src": "/img/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

Then I added the following to my `docusaurus.config.js`:

```
  plugins: [
    [
      require.resolve('@docusaurus/plugin-pwa'),
      {
        debug: false,
        offlineModeActivationStrategies: ['appInstalled', 'queryString'],
        pwaHead: [
          {
            tagName: 'link',
            rel: 'icon',
            href: '/img/icons/icon-192x192.png',
          },
          {
            tagName: 'link',
            rel: 'manifest',
            href: '/manifest.json', // your PWA manifest
          },
          {
            tagName: 'meta',
            name: 'theme-color',
            content: 'rgb(21, 142, 194)',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-capable',
            content: 'yes',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-status-bar-style',
            content: '#000',
          },
          {
            tagName: 'link',
            rel: 'apple-touch-icon',
            href: '/img/icons/icon-192x192.png',
          },
          {
            tagName: 'link',
            rel: 'mask-icon',
            href: '/img/icon.svg',
            color: 'rgb(21, 142, 194)',
          },
          {
            tagName: 'meta',
            name: 'msapplication-TileImage',
            content: '/img/icons/icon-192x192.png',
          },
          {
            tagName: 'meta',
            name: 'msapplication-TileColor',
            content: '#000',
          },
        ],
      },  
    ],
  ],
```

Running `docusaurus start` produces the following error:

```
$ env DISABLE_VERSIONING=true INCLUDE_CURRENT_VERSION=true node --max_old_space_size=16000 node_modules/@docusaurus/core/bin/docusaurus start
Starting the development server...
Error: Cannot find module '@docusaurus/core/lib/webpack/plugins/LogPlugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\git\touchgfx.git\node_modules\@docusaurus\plugin-pwa\src\index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.module.exports.moduleId [as default] (c:\git\touchgfx.git\doc\touchgfx-doc\node_modules\import-fresh\index.js:31:59)
    at pluginConfigs.map (c:\git\touchgfx.git\doc\touchgfx-doc\node_modules\@docusaurus\core\lib\server\plugins\init.js:46:52)
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (c:\git\touchgfx.git\doc\touchgfx-doc\node_modules\@docusaurus\core\lib\server\plugins\init.js:27:10)
    at Object.loadPlugins (c:\git\touchgfx.git\doc\touchgfx-doc\node_modules\@docusaurus\core\lib\server\plugins\index.js:49:35)
error Command failed with exit code 1.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Add PWA plugin with `yarn add @docusaurus/plugin-pwa`
2. Add `static/manifest.json`
3. Use plugin in `docusaurus.config.js`
4. Run `docusaurus start`
5. Error

## Expected behavior

The site compiles without error.

## Actual Behavior

An error occurs stating that some module cannot be found.

## Your Environment

- Docusaurus version used: alpha.62
- Environment name and version: Node.js 12.14.0

**Comment by krillboi** [comment]
Nevermind, I'm an idiot and installed the plugin in the wrong directory.. carry on.
