### ISSUE TITLE
[v2] build -> deploy doesn't work

### ISSUE THREAD

**Issue by longlho** [facebook/docusaurus#3452]
## 🐛 Bug Report

`build` -> `deploy --skip-build` doesn't seem to work. I'm trying to `bazel` docusaurus and am stuck at this step.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `docusaurus build --out-dir=foo my-custom-website`
1. `docusaurus deploy --skip-build --dir=foo my-custom-website`

## Expected behavior

`deploy` to work with prebuilt artifacts

## Actual Behavior

Fail with
```
Error: Temp dir .docusaurus does not exists. Run build website first.
    at runDeploy (/home/longlho/formatjs/node_modules/@docusaurus/core/lib/commands/deploy.js:75:19)
    at deploy (/home/longlho/formatjs/node_modules/@docusaurus/core/lib/commands/deploy.js:147:9)
    at /home/longlho/formatjs/node_modules/@docusaurus/core/bin/docusaurus.js:73:5
    at Command.<anonymous> (/home/longlho/formatjs/node_modules/@docusaurus/core/bin/docusaurus.js:134:24)
    at Command.listener (/home/longlho/formatjs/node_modules/@docusaurus/core/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/longlho/formatjs/node_modules/@docusaurus/core/node_modules/commander/index.js:892:12)
    at Command.parse (/home/longlho/formatjs/node_modules/@docusaurus/core/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/home/longlho/formatjs/node_modules/@docusaurus/core/bin/docusaurus.js:205:5)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

## Your Environment

Ubuntu 18

**Comment by slorber** [comment]
Hi @longlho 

I can confirm running these commands at the root of our own monorepo don't work.

```bash
yarn docusaurus build --out-dir=foo website
yarn docusaurus deploy --skip-build --out-dir=foo
```

This is because you did  not provide the siteDir option. This does work:

```bash
yarn docusaurus build --out-dir=foo website
yarn docusaurus deploy --skip-build --out-dir=foo website
```

**Comment by slorber** [comment]
Note, as you have a monorepo for FormatJS, and it's less common/battletested to launch commands at the root of the monorepo. 

Most of the time it should work fine, but you in case of troubles, you might as well consider:
- adding the website as a monorepo package and run `yarn workspace website docusaurus build`
- running the docusaurus cli from the website folder (can be done with `yarn --cwd website docusaurus build` I  think)
