### ISSUE TITLE
Help translate the Docusaurus 2 website

### ISSUE THREAD

**Issue by slorber** [facebook/docusaurus#3526]
## Help translate the Docusaurus 2 website

As Docusaurus v2 i18n implemetation is in progress (https://github.com/facebook/docusaurus/pull/3325), it would be nice to translate the Docusaurus 2 website. 

It would help Docusaurus 2 adoption, but also dogfood the i18n implementation and Crowdin integration to ensure it's robust enough so that we can release a beta/RC/GA release.

Before doing that, we must:
- Ship i18n
- Refactor a bit v2 documentation to a decent folder structure (so that we don't translate docs for nothing)

Also, the translations would happen through Crowdin, so unfortunately they wouldn't show on the Github contribution history of contributors, but I have ideas so that translations done on Crowdin could end up showing as Github contributions, which hopefully could give more incentives to contribute to translations.

For now, I'd like to know if some people would be interested to contribute to translations?

**Comment by leeyspaul** [comment]
I'm interested in helping out with the translation efforts for i18n! Would you be able to put more information here on what that would look like for interested folks?

**Comment by slorber** [comment]
Thanks @leeyspaul. In which language are you able to translate?

Basically, the work would be to use Crowdin and translate:
- a file of layout key/value pairs
- whole markdown documents

Very similar to v1 translation process. To get familiar with it, you can join the v1 translation project here: https://crowdin.com/project/docusaurus and submit a few translation proposals.

**Comment by leeyspaul** [comment]
@slorber I'd be able to contribute in Spanish and maybe in Korean in the future. But for now I'd like to start with Spanish. I'll check out the links and ask any questions through the discord channel. Would it be helpful for perhaps new folks looking to contribute to have a page on the localization process? Perhaps a new issue could be opened up on that.

**Comment by ArtFlag** [comment]
I could help with French, if needed.

**Comment by slorber** [comment]
Thanks. I'm French so would be able to translate it in French but still help is welcome 👍 

@leeyspaul the localization process does not exist yet. We'll actually write it from practical experience traducting the Docusaurus site. There are multiple things to figure out, including Crowdin recommended settings etc...

**Comment by leeyspaul** [comment]
Totally! Happy to help brainstorm with a proposal of sorts if you're looking to do that. @slorber

**Comment by limkinZero** [comment]
I could help with spanish. This feature is a must

**Comment by iamrubayet** [comment]
I can help you with Bengali

**Comment by shaonkabir8** [comment]
Hi,
I'm highly interested in translating **Docusaurus 2 website** in Bengali :raising_hand_man: and super excited to be assigned as a :bangladesh:  Bengali translator.  :heart:

Thanks

**Comment by ayonious** [comment]
@slorber Im happy to help with German translations. Already signed up in Crowdin. I dont see any German folder to start from. 

Thanks

**Comment by slorber** [comment]
Thanks everyone,

I've just enabled German, Spanish and Bengali on Crowdin.

@shaonkabir8 @iamrubayet I've enabled Bengali too, but there are 2 options so let me know if I didn't select the best one:

![image](https://user-images.githubusercontent.com/749374/105990002-25cb9700-60a2-11eb-8c2d-b919892e3095.png)

**Comment by f0rb1d** [comment]
Can help with Simplified Chinese (zh-cn) translation here.

**Comment by slorber** [comment]
Thanks @f0rb1d , just enabled it: https://crowdin.com/project/docusaurus-v2/zh-CN

**Comment by mrcsvg** [comment]
Hello! Greetings from Brazil!

Portuguese (pt-br) is not in the list but I would be really happy to help translating it!

> "How much can you translate (in % of the whole documentation)."

 That will depend, but for sure I can get more people for help and have it in 100%.

**Comment by slorber** [comment]
Thanks, enabled :) https://crowdin.com/project/docusaurus-v2/pt-BR

**Comment by CUBERLEON** [comment]
@slorber I am happy to help with Ukrainian translation.
Thanks.

**Comment by slorber** [comment]
Thanks :) 

https://crowdin.com/project/docusaurus-v2/uk

**Comment by f0rb1d** [comment]
@slorber Hi there. Lots of content have been translated since I commented. I want to see preview and adjust translations based it. Could you please also enable the language on the website? Thank you in advance.

**Comment by slorber** [comment]
Hi @f0rb1d 

Unfortunately, I don't see much content that has been translated so far.
https://crowdin.com/project/docusaurus-v2

![image](https://user-images.githubusercontent.com/749374/107048872-b3f1fc80-67c9-11eb-9698-ba5e27a5de40.png)


I think we don't want to put online translations that are mostly incomplete, but rather have a minimum threshold to put the translated site online, maybe around 30%, and ensure at least the homepage + introduction pages are fully translated?

About the preview, unfortunately, you can't have it easily locally because afaik Crowdin only allow project managers to download the translations through their cli, and I can't create any read-only/project-specific API key that I can securely share.

If someone is actively working on translations and want to have previews, just ask after at least 5%/10% of translations have been done, and I'll add such locales to a separate i18n work-in-progress deployment

**Comment by Ningensei848** [comment]
@slorber Hi ! 👋 Greetings from Japan 🗻 🗾 🏯 👺  

I couldn't find the Japanese folder, so I will help you with the translation as soon as the subfolder is added.

p.s. 
I found that the Japanese folder exists in the [v1 project](https://crowdin.com/project/docusaurus). I'm going to practice using [CrowdIn](https://crowdin.com/) a bit there until a new folder is created in the v2 project.

**Comment by slorber** [comment]
@Ningensei848 I've enabled japanese here: https://crowdin.com/project/docusaurus-v2/ja

**Comment by noworneverev** [comment]
Hi @slorber, I can help with Traditional Chinese (zh-tw). Thanks.

**Comment by slorber** [comment]
Thanks: https://crowdin.com/project/docusaurus-v2/zh-TW

**Comment by slorber** [comment]
> I think the progress shown in the screenshot isn't correct, as the project contains 'Versioned docs' mentioned above which takes up a big part of it.

0% is 0% no matter the versioning system. 

We also use the "hide duplicates strings" feature from crowdin so if 2 versions are similar strings aren't counted multiple times. So when you see "5%" Chinese, it's pretty accurate of the amount translated of upstream docs, just a little bit lower (at least in our case as versions are quite similar).

> Also, a little suggestion here, maybe we can add a feature to automatically fetch and deploy translations per day/week and deploy them? This may be done via GitHub Actions or Netlify plugins.

Translations are already fetched whenever code is merged on master. We just don't trigger builds on translation changes, that feels not necessary as the project is active enough to trigger at least a build per day.

> Last, I think it is a good idea to put thresholds on the process. I've already translated more than homepage + introduction, so please add it to i18n branch. Thank you in advance <3

Thanks, will review that and try to get a deployment soon, but I'd rather have a bit more of ./docs be translated ;)

![image](https://user-images.githubusercontent.com/749374/107555095-0cb10300-6bd7-11eb-9ce5-17e7f8c5e046.png)

**Comment by slorber** [comment]
I've set up a preview deployment for staging locales.
Will add any locale for which there is active translation work going on. 
For now I just added `zh-CN`.

- Preview: https://docusaurus-i18n-staging.netlify.app/
- Netlify site: https://app.netlify.com/sites/docusaurus-i18n-staging
- Trigger a build: `curl -X POST -d {} https://api.netlify.com/build_hooks/602511032ce0923d1b6cd220`

I did not automate the triggering of a build because Crowdin webhooks are not throttled. It feels a bit unnecessary to trigger a build every time there's a new translated string, so for now it's your responsibility to trigger it.

**Comment by slorber** [comment]
FYI the classic theme also ships with some default translation bundles for theme labels, like "next" / "previous" pagination buttons etc...

If you. want to help, please create a similar translation bundle for your language.

You can just copy this file and localize the messages:
https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/codeTranslations/fr.json

**Comment by eshkaflex** [comment]
Hello! I can help with Russian Language.

**Comment by slorber** [comment]
Russian enabled :)
https://crowdin.com/project/docusaurus-v2/ru

I've re-enabled the top30 Crowdin locales, that will be simpler as your locale is more likely to already be enabled.

**Comment by felipecespedes** [comment]
Can help with Spanish of Latin America

**Comment by slorber** [comment]
FYI it's now possible to translate the MDX files, as Crowdin added support for the .mdx extension.
Just, please don't translate the JSX syntax in the MDX documents

**Comment by ZER0-X** [comment]
I'm translating the **Arabic** language.

In the plural rules, can i use the variable more then one time?
like: aaa {count}|bbb {count}|ccc {count}|

**Comment by slorber** [comment]
Hi!

FYI I enabled "ko" and "ja" locales on staging!

https://docusaurus-i18n-staging.netlify.app/

**Comment by alstn2468** [comment]
# `themeClassic/codeTranslations/ko.json` has a comma at the end.

![image](https://user-images.githubusercontent.com/30997311/114207104-f89b3f00-9996-11eb-90af-8e5e6831d8de.png)

## Flow

1. `yarn install`
2. `yarn start -- --locale ko`

## Error Message

```
$ docusaurus start --locale ko
Starting the development server...
SyntaxError: Unexpected token } in JSON at position 2841
    at JSON.parse (<anonymous>)
    at readDefaultCodeTranslationMessages (/Users/minsu/Documents/React/Recoil/docs/node_modules/@docusaurus/utils/lib/index.js:494:25)
    at async Promise.all (index 4)
    at async Object.getPluginsDefaultCodeTranslationMessages (/Users/minsu/Documents/React/Recoil/docs/node_modules/@docusaurus/core/lib/server/translations/translations.js:189:29)
    at async Object.load (/Users/minsu/Documents/React/Recoil/docs/node_modules/@docusaurus/core/lib/server/index.js:189:76)
    at async start (/Users/minsu/Documents/React/Recoil/docs/node_modules/@docusaurus/core/lib/commands/start.js:45:19)
```

**Comment by slorber** [comment]
@alstn2468 this was a mistake that has been fixed already but is not released yet (next week, you can try to use `@canary` in the meantime). I've setup unit tests so that it does not happen again.

**Comment by alstn2468** [comment]
@slorber Thank you for your quick reply.

**Comment by f0rb1d** [comment]
@slorber Just FYI, the Simplified Chinese translation has already reached the minimum translations requirement. You might want to have a peek on the staging site and deploy it on production if it looks good.

**Comment by slorber** [comment]
Thanks for your work everyone, we now have good progress in fr, ko and zh-CN!

As requested by @f0rb1d , fixed some issues + I'm enabling ko + zh-CN in production with https://github.com/facebook/docusaurus/pull/4599

**Comment by yuxxeun** [comment]
Hey! I can help with Bahasa which is Indonesian language.

**Comment by slorber** [comment]
Thanks @yuxxeun , you can submit your translations here already: https://crowdin.com/project/docusaurus-v2/id

**Comment by TomPeirs** [comment]
>Please do not translate for now:
> Versioned docs
>Frontmatter such as id, slug, URLs...
> Code blocks
> **Admonitions**
> JSX syntax in MDX docs

I have a question, I noticed in the crodwin docs files the Admonitions were simply appended A (french) Title.
Will there be a `.json` which interprets admonitions and translates the titles?
![image](https://user-images.githubusercontent.com/68061801/117152399-451d4300-adba-11eb-922d-50857f086b88.png)

Otherwise  we'll need to write a script to translate the titles of markdown admonitions. (we have 1700 files which might potentially have admonitions ;-) )

**Comment by slorber** [comment]
> Will there be a .json which interprets admonitions and translates the titles?

The md content is translated as a whole, and it's a bit complicated to handle such things unfortunately.

What I mean here is that you should not translate the admonition markers.

This is wrong

```diff
- :::caution
+ :::attention
```

But this is a legit translation:

```diff
- :::caution Be careful
+ :::caution Faites attention
```

Unfortunately, I don't think tooling like Crowdin will help much, as each admonition with title will be displayed as a unique string (unlike a `:::tip` that can be marked as hidden string), so translators must remain careful for admonitions with titles.

**Comment by slorber** [comment]
Actually, I think our admonitions plugin hardcode some admonition titles when there is no title, this is probably why @forresst added french titles after the admonition to make sure the default admonition title is translated on the french site:

Reported here: https://github.com/facebook/docusaurus/issues/4542

**Comment by TomPeirs** [comment]
> Actually, I think our admonitions plugin hardcode some admonition titles when there is no title, this is probably why @forresst added french titles after the admonition to make sure the default admonition title is translated on the french site:
> 
> Reported here: #4542

Good to know, in this case we will take the same approach :-)

**Comment by forresst** [comment]
> Actually, I think our admonitions plugin hardcode some admonition titles when there is no title, this is probably why @forresst added french titles after the admonition to make sure the default admonition title is translated on the french site:
> 
> Reported here: [#4542 (comment)](https://github.com/facebook/docusaurus/issues/4542#issuecomment-832898463)

It is exactly that, it is the only trick that I found to have a translation in French

**Comment by Neilblaze** [comment]
> Thanks everyone,
> 
> I've just enabled German, Spanish and Bengali on Crowdin.
> 
> @shaonkabir8 @iamrubayet I've enabled Bengali too, but there are 2 options so let me know if I didn't select the best one:
> 
> ![image](https://user-images.githubusercontent.com/749374/105990002-25cb9700-60a2-11eb-8c2d-b919892e3095.png)

is this still available for grabs? @slorber
If yes, then I would like to take it :)

**Comment by slorber** [comment]
@Neilblaze thanks, you don't need to ask, you can directly follow the instructions of this issue, register to Crowdin and submit translations here: https://crowdin.com/project/docusaurus-v2/bn#

**Comment by slorber** [comment]
Hi there!

Docusaurus has a new mobile nav UX in beta.4!  (https://github.com/facebook/docusaurus/pull/4273)

There are 2 new labels to translate, can you help and submit translation PRs, please?

https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/codeTranslations

```
  "theme.TOCCollapsible.toggleButtonLabel": "On this page",
  "theme.navbar.mobileSidebarSecondaryMenu.backButtonLabel": "← Back to main menu",
```

**Comment by MrPand-21** [comment]
Hello, I want to help with Turkish translation. Okay? or am i late?

**Comment by yokymia** [comment]
Thank you so much

**Comment by slorber** [comment]
Thanks @MrPand-21 

You don't need to ask any permission for submitting translations: just go there and submit your translations directly: https://crowdin.com/project/docusaurus-v2/tr#

**Comment by rafaelbmateus** [comment]
Hello @slorber, pt-BR in 59% and counting...

I triiger a build on staging env a few minutes ago, using `curl -X POST -d {} https://api.netlify.com/build_hooks/602511032ce0923d1b6cd220`.

I'll keep my eye on https://docusaurus-i18n-staging.netlify.app/ to check the changes.

Thanks for now!

**Comment by slorber** [comment]
Thanks a lot @rafaelbmateus ! I'll enable the pt-BR locale in our staging env asap, just busy finishing things for a release but it will be done very soon!

**Comment by massoudmaboudi** [comment]
@slorber 
I would appreciate it if you can enable Farsi (fa-IR) translation so I can start the translation.
Please consider that when a user chooses to use Farsi, the style should also change from LTR to RTL.

**Comment by slorber** [comment]
Thanks @massoudmaboudi , just enabled Farsi here: https://crowdin.com/project/docusaurus-v2/fa
Will enable it on our staging env once 10% translations were submitted.

> Please consider that when a user chooses to use Farsi, the style should also change from LTR to RTL.

Yes, this is applied automatically by Docusaurus as Intl apis can tell us language direction for a language/locale code.

**Comment by massoudmaboudi** [comment]
> https://crowdin.com/project/docusaurus-v2/fa
Thank you @slorber. I will inform you when the translation happens.

**Comment by massoudmaboudi** [comment]
> Thanks @massoudmaboudi , just enabled Farsi here: https://crowdin.com/project/docusaurus-v2/fa
> Will enable it on our staging env once 10% translations were submitted.
> 
> > Please consider that when a user chooses to use Farsi, the style should also change from LTR to RTL.
> 
> Yes, this is applied automatically by Docusaurus as Intl apis can tell us language direction for a language/locale code.

Thank you @slorber. I will inform you when the translation happens.

**Comment by slorber** [comment]
We have merged 2 new translation keys, please help us by submitting a PR:

```
"theme.docs.tagDocListPageTitle": "{nDocsTagged} with \"{tagName}\"",
"theme.docs.tagDocListPageTitle___DESCRIPTION": "The title of the page for a docs tag",

"theme.docs.tagDocListPageTitle.nDocsTagged": "One doc tagged|{count} docs tagged",
"theme.docs.tagDocListPageTitle.nDocsTagged___DESCRIPTION": "Pluralized label for \"{count} docs tagged\". Use as much plural forms (separated by \"|\") as your language support (see https://www.unicode.org/cldr/cldr-aux/charts/34/supplemental/language_plural_rules.html)",
```

**Comment by supernover** [comment]
i would like to help out,if you could enable  Kinyarwanda (eng-ki)  thanks!

**Comment by slorber** [comment]
Thanks @supernover , enabled it here: https://crowdin.com/project/docusaurus-v2/rw

**Comment by hanancs** [comment]
Hi @slorber, I can help with Tamil. Thanks

**Comment by hanancs** [comment]
Hi @slorber, I can help with Tamil. Thanks

**Comment by caleeli** [comment]
Hi! I can help with Spanish translations.

**Comment by MrTechHunter** [comment]
Hey! I can help with Persian/Farsi which is Iranian language.

**Comment by lex111** [comment]
For those who want to contribute with code, you can help translate our classic theme by adding new or improving existing translation. For more details, please see this section https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-theme-classic/codeTranslations#for-docusaurus-users

**Comment by MrTechHunter** [comment]
Hey mate @lex111 
This is my PR: https://github.com/facebook/docusaurus/pull/5640

Sincerely,
Mahdi Hamldar

**Comment by uguraktas** [comment]
hey, @slorber I am happy to help with Turkish translation.

**Comment by slorber** [comment]
Thanks @uguraktas 

It's not necessary to tell us there, you can directly submit your translations on Crowdin (https://crowdin.com/project/docusaurus-v2/tr) and I'll enable a Turkish site once enough translations have been submitted

**Comment by jrmejiaa** [comment]
Hi @slorber I would like to help with Spanish, I saw that there are just 4% of the page translated. However, I don't have much time, so could you tell me which pages are the more important ones in order to have a first Spanish version of docusaurus?

**Comment by slorber** [comment]
FYI the default theme translations have been moved to a new package: https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-theme-translations

I edited the issue to reflect this change

**Comment by slorber** [comment]
@jrmejiaa this issue is up-to-date and all the relevant info are displayed at the top. Unfortunately navigating a i18n site that is only half translated is not very nice for the users. If we could get at least the getting started + guides in Spanish, that would be nice

**Comment by noomorph** [comment]
> * ~Slave~ languages, 4 plural forms: "One post|Few posts|Many posts|{count} posts"

It is rude and unpleasant to see. 🤦‍♂️ 
Please fix to `Slavic` whenever you can.

**Comment by ss-o** [comment]
Hey @slorber,

I recently adopted Docusaurus for my projects. While having the learning curve I can kick off Lithuanian translations, at the same time would be a great practice for me. If there are no limits on how small :mag: a country can be for translations :wink:

**Comment by slorber** [comment]
Thanks @ss-o 👍  , you can now translate our site to lt here: https://crowdin.com/project/docusaurus-v2/lt

**Comment by zixuan945** [comment]
Some snippets like `<code>'light' \| 'dark'</code>` is not escaped correctly and becomes garbage characters on the pages in other languages, looking like` ! !crwdBlockTags_299_sgaTkcolBdwrc!!!`
![image](https://user-images.githubusercontent.com/17488847/155071876-5806010d-44e0-4256-aa68-17597fd1e70c.png)
![image](https://user-images.githubusercontent.com/17488847/155071943-9154ce80-3509-4f0a-8203-0ddfd46ad5da.png)

**Comment by Josh-Cena** [comment]
@zixuan945 This is a known bug with Crowdin. See #5602

**Comment by slorber** [comment]
Admonition default titles are now translatable (https://github.com/facebook/docusaurus/pull/7556) (canary or next release)

Please help us and provide the missing admonition translations for your language: https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-theme-translations/locales

(tip: also provide all the other missing translations at the same time)

**Comment by CarlosMarinAquino** [comment]
I want to collab in the Spanish version, did you have one branch for this language?

**Comment by SilverTee** [comment]
> I want to collab in the Spanish version, did you have one branch for this language?

you could do this here:
https://crowdin.com/project/docusaurus-v2/es-ES

**Comment by shawshankkumar** [comment]
Hey @slorber is there a chance https://docusaurus-i18n-staging.netlify.app/ this isn't auto updating? because I don's see a few things on the production link here. Also, I'd like to contribute to Hindi, anything I should be aware of?

**Comment by slorber** [comment]
There's a section in our "Preview your translation work" that explains how this preview work. It is supposed to be up to date (but sometimes fail, not a big deal). Last successful publish was yesterday. I don't know what you are looking for that you don't find so it's hard to say if there's a problem or not.

Nothing particular to do to contribute to Hindi apart reading the docs. If you have any question left after reading that doc and giving it a try, I'll answer them.

**Comment by shawshankkumar** [comment]
Thanks I'll give it a try!

**Comment by Dong-Qiu-Long** [comment]
你好

**Comment by Dong-Qiu-Long** [comment]
您好， Docusaurus 文档的源码在哪里？

**Comment by Dong-Qiu-Long** [comment]
Hello, where is the source code for the Docusaurus documentation?

**Comment by Dong-Qiu-Long** [comment]
My internationalization configuration has no effect

**Comment by Dong-Qiu-Long** [comment]
？

**Comment by Dong-Qiu-Long** [comment]
I would like to refer to your official website source code

**Comment by kgolubic** [comment]
@slorber I'd like to help with the translation of localization and translation of Docusarus to Croatian. It is not available as [theme default translations](https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-theme-translations/locales) at the moment. What can be done so that I can start with the translation process?

**Comment by slorber** [comment]
@kgolubic I've clarified the instructions, to create a new theme language in the issue. We have a CLI for that. Please let me know if anything is still unclear.

**Comment by slorber** [comment]
We are experiencing some issues with Crowdin for all newly uploaded `.mdx` files. 

Notably, the newly released version `2.4.0` has lost its previously existing translations

![CleanShot 2023-03-24 at 16 19 38@2x](https://user-images.githubusercontent.com/749374/227567436-38122330-ec49-4e9d-9950-58f82f0d75d2.png)


I hope we'll be able to fix this soon with Crowdin support. 

In the meantime, it's probably not worth investing your time in translating these new strings from v2.4.

More info here: https://github.com/facebook/docusaurus/discussions/8821

**Comment by tats-u** [comment]
Japanese now meets all the criteria.

P.S.
Can't we translate the banner string "⭐️ If you like Docusaurus, give it a star on [GitHub](https://github.com/facebook/docusaurus) and follow us on Twitter" at the top of each page?

**Comment by slorber** [comment]
Thanks for your work on this @tats-u 

Due to recent changes on Crowdin and Netlify I have to adjust a bit our translation workflows and versioning archive procedure, so it's not a great timing right now to enable a new language, but we'll do this when I figure it out.

**Comment by CarlosMarinAquino** [comment]
Recently I was working in the Spanish version but I can understand how the platform works in some strings shows 1/2 and then turns into 1/163.
I attending the transition as long I can

**Comment by slorber** [comment]
> some strings shows 1/2 and then turns into 1/163.

@CarlosMarinAquino I don't understand what you mean here 😅 screenshot?

**Comment by Zubiii333** [comment]
I'm working on Bangla localization. Could you please let me know how do I push the changes to test app?

**Comment by slorber** [comment]
@Zubiii333 by Bangla you mean Bengali / bn right?

As explained in the intro post, you can't test it locally, and we ask you to first translate at least 10% on Crowdin before turning your local on in our preview environment. Currently Bengali is at 0% translated: https://crowdin.com/project/docusaurus-v2/bn

**Comment by tats-u** [comment]
The build of https://docusaurus-i18n-staging.netlify.app/ has been broken for a long time.

**Comment by tats-u** [comment]
@yuxxeun 
It's too old. The latest version there is RC of 2.0.
It shows the build has been failed for a very long time.

**Comment by slorber** [comment]
> The build of [docusaurus-i18n-staging.netlify.app](https://docusaurus-i18n-staging.netlify.app/) has been broken

Yes. 

Fixing an issue that prevents the build to even start:
https://github.com/facebook/docusaurus/pull/9374

> for a long time, hasn't it?

What's the point here?

The build logs are public: https://app.netlify.com/sites/docusaurus-i18n-staging/deploys

The project is open-source and you can submit a PR or translation fixes if you see it failing, or kindly report them if we didn't notice.

Even with my PR above, I'm not sure it will fix every issues, we'll see.
It's not my top priority to fix this deployment right now: shipping v3 is way more important.

**Comment by tats-u** [comment]
@slorber It's just because it was too difficult for me to specify the trouble spot from the error logs. Thanks a lot for fixing the issue on behalf of me.

**Comment by tats-u** [comment]
Some languages are better translated than Japanese. How about adding them to the staging site?

**Comment by slorber** [comment]
> Some languages are better translated than Japanese. How about adding them to the staging site?

There's a cost for me to adding any language in terms of maintenance (when i18n staging is blocked due to a bad translation, happens often and hard to debug) and adding languages can also add time to the CI builds (and we are already close to the max build time on Netlify).

Unless they request it, until I find a solution to these problems I am cautious when adding new languages, in both prod and staging.

**Comment by AntonMit84** [comment]
When can we start on version 3?

**Comment by paraskevasleivadaros** [comment]
I am excited to inform you that I have commenced work on the Greek translation for the project. I will be actively updating my progress on Crowdin and look forward to contributing to making Docusaurus more accessible to Greek-speaking users. I'll provide updates and reach out if I encounter any issues or need further guidance!

**Comment by ilmedova** [comment]
@slorber Hi! I would really love to contribute and help with Turkmen language (tm) 🙋🏻‍♀️ It is not available in Crowdin 😞

**Comment by tats-u** [comment]
@ilmedova 
Did you mean `tk`?
It looks like it's supported by Crowdin.

https://developer.crowdin.com/language-codes/

**Comment by ilmedova** [comment]
@tats-u got it, thanks

**Comment by tats-u** [comment]
@ilmedova Let's wait a response from maintainers

**Comment by slorber** [comment]
@ilmedova thanks, Turkmen has been enabled here: https://crowdin.com/project/docusaurus-v2/tk

**Comment by Thecode764** [comment]
i want to help in persian translation how?

**Comment by yunfeidog** [comment]
@slorber There are too few Chinese translations, do you still need simplified Chinese translation

**Comment by goffxnca** [comment]
Count me in for the Thai translation🇹🇭
I’d love to help!

**Comment by slorber** [comment]
> Count me in for the Thai translation🇹🇭 I’d love to help!

Thanks, Thai is now enabled: https://crowdin.com/project/docusaurus-v2/th

> @slorber There are too few Chinese translations, do you still need simplified Chinese translation

I don't "need" translations. If the community contributes translations for their country, then this increases the adoption of Docusaurus in that country, that's all.

**Comment by tats-u** [comment]
I triggered the stating build because I have removed a "translation" hindering the build but got:

```
3:07:32 PM: build-image version: 59029cc38debec12b365d8cde2431251b878d6bf (focal)
3:07:32 PM: buildbot version: 7247145a56b36a0319fe3c98407f85b1c4c84911
3:07:32 PM: Fetching cached dependencies
3:07:32 PM: Failed to fetch cache, continuing with build
3:07:33 PM: Failed during stage 'preparing repo': git ref refs/heads/master does not exist
3:07:33 PM: Starting to prepare the repo for build
3:07:33 PM: git ref refs/heads/master does not exist or you do not have permission
3:07:33 PM: Did you change the name of your production branch? Don't forget to update your settings: https://docs.netlify.com/site-deploys/overview/#branches-and-deploys
3:07:33 PM: Failing build: Failed to prepare repo
```

You may need to update the branch name from master to main.

**Comment by slorber** [comment]
Thanks @tats-u I recreated the build hook to target `main` instead of `master`, and updated the curl command in 1st post.

**Comment by tats-u** [comment]
Successfully triggered. (However still failed due to a bug in the ideal-image plugin.


```
9:15:52 PM: [ERROR] Error while attempting to extract Docusaurus translations from source code file at "../packages/docusaurus-plugin-ideal-image/lib/theme/IdealImageLegacy/components/helpers.d.ts".
9:15:52 PM: [ERROR] SyntaxError: /opt/build/repo/packages/docusaurus-plugin-ideal-image/lib/theme/IdealImageLegacy/components/helpers.d.ts: Missing initializer in const declaration. (1:25)
9:15:52 PM: 
9:15:52 PM: > 1 | export const ssr: boolean;
9:15:52 PM:     |                          ^
9:15:52 PM:   2 | export const nativeConnection: boolean;
9:15:52 PM:   3 | export function guessMaxImageWidth(dimensions: any, w: any): number;
9:15:52 PM:   4 | export function bytesToSize(bytes: any): string;
```

Additional tips:

- `--json` is preferred to `-d`. It automatically sets the `Content-Type` header.
- In WIndows (PowerShell), {} must be quoted. i.e. `"{}"`

**Comment by slorber** [comment]
Thanks, the build problem is being fixed at https://github.com/facebook/docusaurus/pull/11027

The curl command is what Netlify UI shows, I just copied it as is 😅 You should suggest these options to them directly, it would be much more impactful.

**Comment by YagoLeo** [comment]
I can translate Chinese and Spanish version of the doc. Do you need any help?^_^

**Comment by slorber** [comment]
> I can translate Chinese and Spanish version of the doc. Do you need any help?^_^

Thanks, yes we'd be happy to improve on these languages

You don't need to ask, you can submit contributions here directly: https://crowdin.com/project/docusaurus-v2

**Comment by winstonsung** [comment]
Can we fix the BCP 47 language tag to use `zh-Hans`/`zh-Hans-CN` instead of `zh-CN`?

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Thanks.

**Comment by slorber** [comment]
@winstonsung Docusaurus site and other sites could configure this thanks to the `i18n.<localeConfig>['zh-CN'].htmlLang = 'zh-Hans'`

But from my understanding `zh-CN` is also a valid BCP 47 tag, and you'll find references to it in those docs:
- https://www.ietf.org/rfc/bcp/bcp47.txt
- https://unicode.org/reports/tr35/#BCP_47_Conformance

> Or perhaps a user would want to associate
   requests for the range "zh-Hans" (Chinese as written in the
   Simplified script) with content bearing the language tag "zh-CN"
   (Chinese as used in China, where the Simplified script is
   predominant).

We can study this more, but from my understanding, a BCP47 tag (like `zh`, present in your doc) remains perfectly valid if we add a region to it (`-ZN`). 

Why do you think `zh-CN` is broken, and what would this change fix exactly?

Any opinion @Josh-Cena ?

---

If you think our HTML lang tag is wrong, we are not alone using it:
- https://www.apple.com.cn/
- https://www.tencent.com/zh-cn/

**Comment by winstonsung** [comment]
I didn't mean `zh-CN` is wrong/invalid, but it's not preferred as `zh-CN` was first being used when the script subtags were not being considered.

Android and MediaWiki both include the script subtag, and it's better for the definition (zh doesn't have the `Suppress-Script` field and is written in multiple scripts) and fallback.

https://android.googlesource.com/platform/frameworks/base/+/android15-release/core/res/res/values/locale_config.xml#612

https://developer.android.com/guide/topics/resources/app-languages

https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/tags/1.43.1/includes/language/LanguageCode.php#136

**Comment by xeneize1212** [comment]
spanish please

**Comment by Roushan901** [comment]
Is there any option to translate it into Japanese?

**Comment by tats-u** [comment]
https://docusaurus-i18n-staging.netlify.app/ja/

**Comment by OfficialMutazAwad** [comment]
New reply to your ticket #13245

Title: Re: [facebook/docusaurus] Help us translate the Docusaurus website (#3526)

Message: Hello,we received your message and our support will reach out to you as soon as possible.

**Comment by MateoLoz** [comment]
hey I want to contribute translating the docs to spanish is it available to do it ?

**Comment by alihanbays** [comment]
Hello, I would love to help with the Turkish translation if needed. Let me know!

**Comment by Injora** [comment]
if possible, i would love to help in hindi translation.Let me know!

**Comment by slorber** [comment]
A kind reminder that you do not need to ask permission to start translating things on Crowdin

However, I'm not sure it's super useful anymore to translate sites manually. Most likely in the future, we will fully pre-translate sites with AI. Then you would only have to proofread and correct strings when the AI was wrong.

**Comment by tats-u** [comment]
All the Japanese translation in the staging site went away even though no build errors seems to be found in the Netlify log. In the past, when similar issues occurred repeatedly, they were always caused by syntax errors in the translation. But this time, no build errors are found.


https://docusaurus-i18n-staging.netlify.app/ja/docs

**Comment by ankur0904** [comment]
@slorber yes exactly. We only need to do proofreading and cross check the translation done by AI.

**Comment by OrkhanAbbasli** [comment]
Added Azerbaijani (az) default theme translations in #12370. Happy to help with the Crowdin side once the locale is enabled.
