### ISSUE TITLE
Poll option for `docusaurus start` doesn't work

### ISSUE THREAD

**Issue by perry-mitchell** [facebook/docusaurus#3620]
## 🐛 Bug Report

I'm trying to use polling as I can't get watching to work, due to the `EMFILE` node error. I've increased all of my watch limits but this doesn't help. I've opted to use the documented `--poll` cli flag.

When following the v2 instructions for using `docusaurus start`, I've tried to configure following in the following ways:

 * `docusaurus start --poll` - results in `EMFILE` error, no difference
 * `docusaurus start --poll=true` - `Error: docusaurus.config.js not found`
 * `docusaurus start --poll true` - `Error: docusaurus.config.js not found`
 * `docusaurus start --poll=1500` - `Error: docusaurus.config.js not found`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Simply modify the `start` npm script to use one of the `docusaurus start` alternatives above.

## Expected behavior

Polling should be enabled, avoiding the `EMFILE` error. I have another webpack project open where the poll option in the `webpack.config.js` file works fine.

## Actual Behavior

Errors are thrown, docusaurus fails to start.

## Your Environment

- Docusaurus version used: `2.0.0-alpha.66`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node `v12.16.1`
- Operating system and version (desktop or mobile): Ubuntu 18.04

**Comment by perry-mitchell** [comment]
Output of the `docusaurus.config.js` error is as follows:

```
Starting the development server...
Error: docusaurus.config.js not found
    at Object.loadConfig [as default] (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/lib/server/config.js:22:15)
    at loadContext (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/lib/server/index.js:48:40)
    at Object.load (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/lib/server/index.js:77:21)
    at start (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/lib/commands/start.js:36:34)
    at /mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/bin/docusaurus.js:74:5
    at Command.<anonymous> (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/bin/docusaurus.js:153:23)
    at Command.listener (/mnt/s1/my-project/docs/docs-website/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:311:20)
    at Command.parseArgs (/mnt/s1/my-project/docs/docs-website/node_modules/commander/index.js:892:12)
    at Command.parse (/mnt/s1/my-project/docs/docs-website/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/mnt/s1/my-project/docs/docs-website/node_modules/@docusaurus/core/bin/docusaurus.js:214:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

```

**Comment by slorber** [comment]
Hi

We don't implement this option ourselves, we just "forward" the cli attribute to Webpack dev server config, so if there is a polling but, it's more likely to be in Webpack than in Docusaurus, and I can't do anything about it.

But I don't understand how `Error: docusaurus.config.js not found` is related to the poll option in any way. When this error happens it's usually because you run the cli commands in the wrong folder.

**Comment by perry-mitchell** [comment]
Thanks @slorber for the quick response. Completely get that it's a webpack **function**, but it looks like the error is primarily in docusaurus as it's crashing. Could you please confirm which format is correct out of the options I mentioned? Or provide an example of `--poll` if none of mine are correct?

> When this error happens it's usually because you run the cli commands in the wrong folder.

I checked this, and have been running in the same folder as `package.json` and `docusaurus.config.js`.

**Comment by slorber** [comment]
So I think you are right, currently we can't pass a number through the cli, only a boolean, otherwise the number is interpreted as the `siteDir`, not the poll value.

Will make the config not found error message clearer in this case so that you know what is happening.

![image](https://user-images.githubusercontent.com/749374/96745196-26c79b00-13c6-11eb-903c-2114a739909e.png)


Not sure yet if I can support boolean+number with our cli helpers, but will look at it.

**Comment by perry-mitchell** [comment]
@slorber Did you manage to get `--poll` working at all? I'm happy with a default value for the interval, but I can't get it to function at the moment, and see the same error you're getting.

**Comment by slorber** [comment]
@perry-mitchell , I don't know  how  the webpack dev server poll works,  I can just tell you that `--poll 500` currently does not work  and you can only pass a boolean/true by simply using `--poll`

And double-checked, this config is correctly forwarded to webpack dev server options (https://webpack.js.org/configuration/watch/#watchoptionspoll)

The next release will allow to use `--poll 500` (https://github.com/facebook/docusaurus/pull/3622) and forward the interval to webpack. After I can't guarantee it will work for you, but will have done everything I can from Docusaurus side.

**Comment by slorber** [comment]
As I don't have your watch problem I can't reproduce it locally and help you more.

You can try to modify locally the `node_modules/docusaurus/lib/commands/start.js` file and see if anything work. 

Current options are:

```
        watchOptions: {
            ignored: /node_modules/,
            poll: cliOptions.poll,
        },
```

try to hardcode whatever you want here and see if it improves anything

**Comment by perry-mitchell** [comment]
@slorber Sure, I'll try those. But `--poll` is definitely broken for me currently, as I'm constantly getting EMFILE errors even after a reboot:

```
✔ Client  Compiled successfully in 3.39s(node:19494) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/mnt/s1/leadoo/docs/docs-website/sidebars.js'    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1346:11)
    at createFsWatchInstance (/mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/lib/nodefs-handler.js:119:15)    at setFsWatchListener (/mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/lib/nodefs-handler.js:166:15)    at NodeFsHandler._watchWithNodeFs (/mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/lib/nodefs-handler.js:331:14)    at NodeFsHandler._handleFile (/mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/lib/nodefs-handler.js:395:23)    at NodeFsHandler._addToNodeFs (/mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/lib/nodefs-handler.js:628:21)    at async /mnt/s1/leadoo/docs/docs-website/node_modules/chokidar/index.js:445:21
    at async Promise.all (index 0)(node:19494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:19494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'll test soon and update.

**Comment by slorber** [comment]
If you hardcode the poll settings you want in both Chokidar and Webpack Dev Server, and still get an error, you should report the bug to these tools directly, as I'm not able to do anything else about it.

**Comment by abe-winter** [comment]
For what it's worth I also had this problem on a linux laptop
- finally solved by closing vscode, which was probably hogging all the watches (and which also uses chokidar internally)
- before that, I audited what chokidar was doing -- as far as I could tell, it wasn't doing anything egregious (like for example watching the entire node_modules tree). pretty sure it was tracking 11 globs which added to under 30 files
- I think chokidar poll mode still uses some file watch resources, just of a different type. I think the chokidar polling flag switches between node's fs.watch and fs.watchFile. I don't fully understand this
- `npm run build && npm run serve` is an alternative that doesn't consume watchers, but the `build` command is potentially slow for iterative dev

Possible solutions here:
- flag for `--no-watch` in the `serve` command
- use readline to listen for the 'r' key on the console to allow manual refreshing

But for my purposes, shutting down other resource hogs is fine + the tool is good as-is.
