### ISSUE TITLE
Cannot destructure property 'permalinkToSidebar' of 'docsMetadata' as it is undefined.

### ISSUE THREAD

**Issue by Danon** [facebook/docusaurus#3711]
## 🐛 Bug Report

Inability to run a page both in prod and dev mode.

### Have you read the [Contributing Guidelines on issues]
Yup

## To Reproduce

1. Install docusaurus `2.0.0-alpha.66`

## Expected behavior

Ability to build a page:

1. `docusaurus build` and/or `docusaurus start`

## Actual Behavior

```
(undefined) TypeError: Cannot destructure property 'permalinkToSidebar' of 'docsMetadata' as it is undefined.
    at DocPageContent (main:27613:201)
    at d (main:30360:498)
    at $a (main:30363:16)
    at a.b.render (main:30368:476)
    at a.b.read (main:30368:18)
    at Object.renderToString (main:30378:364)
    at serverEntry_render (main:58048:375)
Error: Failed to compile with errors.
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\@docusaurus\core\lib\webpack\utils.js:164:24
    at finalCallback (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\neo-async\async.js:2931:13)
    at runCompilers (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\MultiCompiler.js:188:7
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\tapable\lib\Hook.js:154:20)
    at onCompiled (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\Compiler.js:271:21)
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Danon\PhpstormProjects\T-Regx.github.io\website\node_modules\webpack\lib\Compiler.js:678:31
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `docusaurus build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Danon\AppData\Roaming\npm-cache\_logs\2020-11-07T12_36_28_807Z-debug.log
```

## Your Environment

- Docusaurus version used: 2.0.0-alpha.66
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 14.5 (np 6.14)
- Operating system and version (desktop or mobile): Windows 10

## Reproducible Demo

https://github.com/T-Regx/T-Regx.github.io checkout branch `source`, 
run `npm install` and `npm run build`.

**Comment by slorber** [comment]
Hi,

Your site used to work right?

Can you find out the commit that breaks it?

**Comment by lukewhyte** [comment]
Just updated to `2.0.0-alpha.66` and uncovered the same bug. However, I was able to solve it by clearing out `node_modules` + `package-lock.json` and doing a fresh install of my repo.

**Comment by Danon** [comment]
Helped, thanks .

**Comment by lex111** [comment]
By the way, maybe the new Docusaurus command `yarn clear` would help in this case, try it if you experience this error next time. So in the meantime, I am closing this issue.
