### ISSUE TITLE
Exception starting site after v2 migration

### ISSUE THREAD

**Issue by caabernathy** [facebook/docusaurus#3770]
## 🐛 Bug Report

Running the v1 to v2 migration script results in an error when running the `yarn start` command. I saw this recently when I was migrating a real site and here reproduced it from the basic site generated for v1.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. `$ mkdir DocuMig`
1.  `$ cd DocuMig/`
1.  `$ npx docusaurus-init .`
1. `$ cd website/; yarn start`
1. Test that the site shows up on the browser http://localhost:300
1. Stop the server running by killing the command in (my case) Terminal
1. `cd ..`
1. `$ npx @docusaurus/migrate migrate ./website ./v2-website`
1. Verify migration script runs with no errors
1. `$ cd ../v2-website/`
1. `$ yarn install`
1. `$ yarn start`

## Expected behavior

The local server should start showing the v2 version of the website.

## Actual Behavior

Exception thrown:

```
$ docusaurus start
Starting the development server...
The docs plugin option homePageId=doc1 is deprecated. To make a doc the "home", prefer frontmatter: "slug: /"
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at Object.generate (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/utils/lib/index.js:40:52)
    at createData (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:75:27)
    at async Object.contentLoaded (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/plugin-debug/lib/index.js:23:36)
    at async /Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:91:9
    at async Promise.all (index 3)
    at async Object.loadPlugins (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:64:5)
    at async Object.load (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/core/lib/server/index.js:77:58)
    at async start (/Users/caabernathy/Facebook/OpenSource/Apps/DocuMig/v2-website/node_modules/@docusaurus/core/lib/commands/start.js:44:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Your Environment

- Docusaurus version used: Latest
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 12.18.1
- Operating system and version (desktop or mobile): macOS Catalina 10.15.7

## Reproducible Demo

The steps should cover this.

**Comment by lex111** [comment]
Sorry for the inconvenience, to fix this issue now, try bumping the Docusaurus packages as shown below:

```
    "@docusaurus/core": "2.0.0-alpha.66",
    "@docusaurus/preset-classic": "2.0.0-alpha.66",
```

@slorber apparently this is another negative consequence of the fact that we do not mark packages as `latest`.

https://github.com/facebook/docusaurus/blob/8f2d898f22a3d10fbb76abc866fb4b91547df33c/packages/docusaurus-migrate/src/index.ts#L25

![image](https://user-images.githubusercontent.com/4408379/99457210-a734d980-293b-11eb-8443-fbc74750a254.png)

**Comment by slorber** [comment]
yes, we'll fix this on next  release hopefully

**Comment by slorber** [comment]
Does it work for you now @caabernathy ?

**Comment by lex111** [comment]
In order to reduce staled issues, I am closing this issue, but feel free to open it again if needed.
This issue has been fixed anyway.

**Comment by Aravin** [comment]
Same issue

```
Uncaught ReferenceError: Buffer is not defined
    at isSpecificValue (webpack-internal:///./node_modules/deep-extend/lib/deep-extend.js:32)
    at eval (webpack-internal:///./node_modules/deep-extend/lib/deep-extend.js:132)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///./node_modules/deep-extend/lib/deep-extend.js:110)
    at Array.forEach (<anonymous>)
    at module.exports (webpack-internal:///./node_modules/deep-extend/lib/deep-extend.js:104)
    at Rr (webpack-internal:///./node_modules/swagger-ui-react/swagger-ui.js:2)
    at SwaggerUI.componentDidMount (webpack-internal:///./node_modules/swagger-ui-react/index.js:80)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19814)
    at commitLayoutEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:292)
    at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22541)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:653)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22381)
    at finishSyncRender (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21807)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21793)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11089)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:653)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11084)
    at flushSyncCallbackQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11072)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21199)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12639)
    at PendingNavigation.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:471)```

after upgrading too

![Uploading image.png…]()

**Comment by slorber** [comment]
@Aravin this does not seem related to the current issue. Try docusaurus clear, rm -rf node_modules, regen your lockfile etc and if it still does not work open an issue with a repro github repo
