### ISSUE TITLE
CSS minification fails with custom font-faces

### ISSUE THREAD

**Issue by hmil** [facebook/docusaurus#3874]
## 🐛 Bug Report

I have placed custom fonts in `static/fonts`, along with a css file, `static/fonts/fonts.css` which contains the `@font-face` declarations.
In `custom.css`, I link to the fonts file with: `@import url('/static/fonts/fonts.css');`. I do it this way because I don't want webpack to attempt to process my fonts.css file. If I use a relative import, then webpack tries to load my fonts and crashes (which is a different problem).

The setup above works in dev mode (`yarn start`). However it causes the production build to fail with:

```
docs/node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:30
          throw e;
          ^

TypeError: Cannot read property '0' of undefined
    at Object.font [as breakUp] (docs/node_modules/clean-css/lib/optimizer/level-2/break-up.js:303:91)
    at populateComponents (docs/node_modules/clean-css/lib/optimizer/level-2/properties/populate-components.js:17:42)
    at docs/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:141:9
    at markUsedAtRules (docs/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:63:9)
    at removeUnusedAtRule (docs/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:43:3)
    at removeUnusedAtRules (docs/node_modules/clean-css/lib/optimizer/level-2/remove-unused-at-rules.js:22:3)
    at level2Optimize (docs/node_modules/clean-css/lib/optimizer/level-2/optimize.js:117:5)
    at optimize (docs/node_modules/clean-css/lib/clean.js:147:5)
    at docs/node_modules/clean-css/lib/clean.js:120:29
    at docs/node_modules/clean-css/lib/reader/read-sources.js:26:64
    at loadOriginalSources (docs/node_modules/clean-css/lib/reader/load-original-sources.js:26:5)
    at docs/node_modules/clean-css/lib/reader/read-sources.js:26:14
    at applySourceMaps (docs/node_modules/clean-css/lib/reader/apply-source-maps.js:34:5)
    at Object.callback (docs/node_modules/clean-css/lib/reader/read-sources.js:25:12)
    at doInlineImports (docs/node_modules/clean-css/lib/reader/read-sources.js:200:25)
    at Object.callback (docs/node_modules/clean-css/lib/reader/read-sources.js:324:14)
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. Add woff2 fonts along with a css file containing `@font-face` declarations for this font in `static/`
2. Link to the css file from the main css file (custom.css) using an absolute path to prevent webpack from following the link
3. Run a production build. It fails with the error above.

## Expected behavior

Prod build should not fail. `fonts.css` should be treated like an opaque file (not processed). Even if it is processed, it should not crash.

## Actual Behavior

`fonts.css` is processed and the build crashes with an obscure error. If you comment out `@font-face` declarations in `fonts.css`, then the build passes (but then you can't enjoy your beautiful custom fonts)

## Your Environment

- Docusaurus version used: `2.0.0-alpha.68`
- Environment name and version: `NodeJs v12.16.2`
- clean-css version in `yarn.lock`: `4.2.3`

## Reproducible Demo

Sorry, no repro at the moment as this happened in a confidential project. I might add one later if time permits.

**Comment by hmil** [comment]
Note: I am using `USE_SIMPLE_CSS_MINIFIER=true` to work around this problem.

**Comment by slorber** [comment]
Thanks,

This is the same issue as https://github.com/facebook/docusaurus/issues/3836 right?

**Comment by hmil** [comment]
🤦‍♂️ yes.
Should've spent a little longer searching through the issues.
