### ISSUE TITLE
npm upgrade breaks install

### ISSUE THREAD

**Issue by Morriz** [facebook/docusaurus#3878]
## 🐛 Bug Report

`npm upgrade` breaks `docusaurus start`

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

I went from:
```json
    "@docusaurus/core": "2.0.0-alpha.66",
    "@docusaurus/plugin-content-docs": "^2.0.0-alpha.66",
    "@docusaurus/plugin-google-gtag": "^2.0.0-alpha.66",
    "@docusaurus/plugin-ideal-image": "^2.0.0-alpha.66",
    "@docusaurus/preset-classic": "2.0.0-alpha.66",
    "@docusaurus/theme-search-algolia": "^2.0.0-alpha.32",
```
with `npm upgrade` to:
```json
    "@docusaurus/core": "2.0.0-alpha.66",
    "@docusaurus/plugin-content-docs": "^2.0.0-alpha.69",
    "@docusaurus/plugin-google-gtag": "^2.0.0-alpha.69",
    "@docusaurus/plugin-ideal-image": "^2.0.0-alpha.69",
    "@docusaurus/preset-classic": "2.0.0-alpha.66",
    "@docusaurus/theme-search-algolia": "^2.0.0-alpha.69",
```

## Expected behavior

`npm start` to proceed

## Actual Behavior

`npm start` borks with following error:
```
Starting the development server...
Error: Cannot mix different versions of joi schemas
    at new module.exports (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@hapi/hoek/lib/error.js:23:19)
    at module.exports (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@hapi/hoek/lib/assert.js:20:11)
    at Object.exports.isSchema (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/common.js:132:5)
    at Object.internals.schema (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/compile.js:66:16)
    at Object.exports.schema (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/compile.js:17:26)
    at internals.Base.$_compile (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/base.js:645:24)
    at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/types/keys.js:256:92
    at Object.exports.tryWithPath (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/common.js:176:16)
    at internals.Base.method [as keys] (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/types/keys.js:256:32)
    at internals.Base.method [as append] (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/joi/lib/types/keys.js:185:29)
    at normalizePluginOptions (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@docusaurus/utils-validation/lib/validationUtils.js:27:32)
    at validateOptions (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@docusaurus/plugin-content-docs/lib/options.js:102:31)
    at /Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:52:39
    at Array.map (<anonymous>)
    at Object.initPlugins [as default] (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:27:10)
    at Object.loadPlugins (/Users/Morriz/Documents/Workspace/redkubes/otomi/otomi-docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:49:35)
```

## Your Environment

- Docusaurus version used: see above
- Environment name and version: Node.js v14.15.0:
- Operating system and version (desktop or mobile): OSX

## Reproducible Demo

Fork the repo mentioned above @ hash 2852c1f0ae7d240754b20acf98ff10a96b89f8bd and try the same upgrade steps

**Comment by Morriz** [comment]
After removing the packages and installing them without version with:
```
npm install -S @docusaurus/core @docusaurus/plugin-content-docs @docusaurus/plugin-google-gtag @docusaurus/plugin-ideal-image @docusaurus/preset-classic @docusaurus/preset-classic @docusaurus/theme-search-algolia
```
They are now all at `"^2.0.0-alpha.69"`. Closing.

**Comment by slorber** [comment]
yeah

actually have some code to ensure that it throws if you have mixed versions (alpha 66 + alpha 69), unfortunately in this case the Joi error appears even before this code can run 😅
