### ISSUE TITLE
2.0.0-alpha.73 can't handle tags which could be parsed as numbers 

### ISSUE THREAD

**Issue by johnnyreilly** [facebook/docusaurus#4642]
## 🐛 Bug Report

As of 2.0.0-alpha.73, docusaurus will choke on tags that can be parsed as numbers.  

Consider the following:

```
---
title: "Azure DevOps Node API: The missing episodes"
author: John Reilly
author_url: https://github.com/johnnyreilly
author_image_url: https://blog.johnnyreilly.com/img/profile.jpg
tags: [azure devops api, 203, node.js]
hide_table_of_contents: false
---
```

The `203` tag above is bad news and will lead to an error like this:

```
[en] Creating an optimized production build...
error building locale=en
ValidationError: "tags[1]" must be one of [string, object]
```

See: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/35/checks?check_run_id=2377642622

You can workaround it by changing `203` to be `'203'`, but ideally this wouldn't be necessary.

### Have you read the [Contributing Guidelines on issues]

Yes

## To Reproduce

Follow the example above and then `yarn build`

## Expected behavior

Compilation works.

## Actual Behavior

An error of the nature:

```
[en] Creating an optimized production build...
error building locale=en
ValidationError: "tags[1]" must be one of [string, object]
    at Object.exports.process (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/errors.js:184:16)
    at Object.internals.entry (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/validator.js:150:26)
    at Object.exports.entry (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/validator.js:27:30)
    at internals.Base.validate (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/base.js:548:26)
    at Object.internals.assert (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/index.js:225:27)
    at Object.attempt (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/joi/lib/index.js:107:26)
    at Object.assertBlogPostFrontMatter (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/plugin-content-blog/lib/blogFrontMatter.js:24:28)
    at /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/plugin-content-blog/lib/blogUtils.js:90:27
    at async Promise.all (index 194)
    at async Object.generateBlogPosts (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/plugin-content-blog/lib/blogUtils.js:84:5)
    at async Object.loadContent (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/plugin-content-blog/lib/index.js:59:25)
    at async /home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:53:46
    at async Promise.all (index 0)
    at async Object.loadPlugins (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:52:34)
    at async Object.load (/home/runner/work/blog.johnnyreilly.com/blog.johnnyreilly.com/blog-website/node_modules/@docusaurus/core/lib/server/index.js:94:82)
```

## Your Environment

Locally in Linux and in GitHub Actions

- Public source code: https://github.com/johnnyreilly/blog.johnnyreilly.com
- Public site url: https://blog.johnnyreilly.com/
- Docusaurus version used: 2.0.0-alpha.73
- Environment name and version: Node.js 14
- Operating system and version: Desktop

## Reproducible Demo

See linked PR: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/35

I've opted to go with the workaround for now; but I thought I should share the experience.  Certainly the error message isn't the most helpful in the world.

**Comment by slorber** [comment]
Make sense, I'll add the Joi {convert: true} option, that should fix it.

Also worth logging the doc frontmatter in the error message 😅

**Comment by johnnyreilly** [comment]
So I saw the failure when the GitHub Action ran - I than ran `yarn build` locally and looked at the stack trace. I then added a bunch of `console.log` statements to where the error was thrown, and that allowed me to identify the problematic post.  So not super hard, but required hacking away in `node_modules`

If you point me in the direction of the relevant bit of code I'd be happy to submit a fix PR myself if that helps?

**Comment by johnnyreilly** [comment]
Is it here? https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-plugin-content-blog/src/blogFrontMatter.ts

**Comment by slorber** [comment]
Yes that's here, I'd prefer to use "convert" as in the end we want the tag to be a string.

Can you also add a try/catch around the `attempt` to log the frontmatter in case of error? that would be helpful for users to debug.

Also can you add a test for this specific usecase of title (ensuring we don't remove the convert: true option)

Also related to https://github.com/facebook/docusaurus/issues/4591

**Comment by johnnyreilly** [comment]
See questions on the related WIP PR.
