### ISSUE TITLE
`docs:version` results in `Cannot find module './sidebars.json'`

### ISSUE THREAD

**Issue by SimenB** [facebook/docusaurus#4844]
## 🐛 Bug Report

Trying to create a new version of the docs fails with an unhandled rejection

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## To Reproduce

If possible, use https://new.docusaurus.io to create a CodeSandbox reproducible demo of the bug.

(Write your steps here:)

1. Clone https://github.com/facebook/jest
1. Run `yarn workspace jest-website docusaurus docs:version 27.0`

## Expected behavior

It should correctly generate a new version of the docs

## Actual Behavior

It errors out

```
(node:95658) UnhandledPromiseRejectionWarning: Error: Cannot find module './sidebars.json'
Require stack:
- /Users/simen/repos/jest/node_modules/@docusaurus/plugin-content-docs/lib/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._resolveFilename (/Users/simen/repos/jest/node_modules/module-alias/index.js:49:29)
    at resolveFileName (/Users/simen/repos/jest/node_modules/import-fresh/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/simen/repos/jest/node_modules/import-fresh/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/simen/repos/jest/node_modules/import-fresh/node_modules/resolve-from/index.js:46:41)
    at Object.module.exports [as default] (/Users/simen/repos/jest/node_modules/import-fresh/index.js:14:19)
    at Object.loadSidebars (/Users/simen/repos/jest/node_modules/@docusaurus/plugin-content-docs/lib/sidebars.js:130:47)
    at Object.cliDocsVersionCommand (/Users/simen/repos/jest/node_modules/@docusaurus/plugin-content-docs/lib/cli.js:64:43)
    at Command.<anonymous> (/Users/simen/repos/jest/node_modules/@docusaurus/plugin-content-docs/lib/index.js:56:23)
    at Command.listener [as _actionHandler] (/Users/simen/repos/jest/node_modules/@docusaurus/core/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/simen/repos/jest/node_modules/@docusaurus/core/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/simen/repos/jest/node_modules/@docusaurus/core/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/simen/repos/jest/node_modules/@docusaurus/core/node_modules/commander/index.js:882:12)
    at Command.parse (/Users/simen/repos/jest/node_modules/@docusaurus/core/node_modules/commander/index.js:717:10)
    at run (/Users/simen/repos/jest/node_modules/@docusaurus/core/bin/docusaurus.js:319:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95658) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95658) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also note (as the warnings indicate) that the error is unhandled, meaning the CLI exits with status 0. You are missing a `catch` somewhere 🙂 

## Your Environment

- Public source code: https://github.com/facebook/jest/tree/master/website
- Public site url: https://jestjs.io/
- Docusaurus version used: `2.0.0-alpha.c32d8bd11`, but `2.0.0-beta.0` also fails with the same error
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node 14.17.0
- Operating system and version (desktop or mobile): N/A

## Reproducible Demo

See reproduction steps above

**Comment by lex111** [comment]
@SimenB hi, [`sidebarPath`](https://github.com/facebook/jest/blob/master/website/docusaurus.config.js#L40) must be absolute path (i.e. `require.resolve('./sidebars.js')`, not `'./sidebars.js'`).

In fact, we recently changed DX sidebar config so that it can now be empty. Therefore, after that if relative path is specified in `sidebarPath` (= sidebar file will be considered as non-existent), new sidebar file will be automatically created.
Probably, we need to take into account case when user does not specify absolute path to sidebar, then we should notify (via throw error) they, and not create empty sidebar. Make sense?

**Comment by SimenB** [comment]
Aha! Yeah, a check with `path.isAbsolute` and throwing an explicit error would be nice 🙂

**Comment by SimenB** [comment]
Sorta weird some have to be absolute and some are relative to cwd, though.

https://github.com/facebook/jest/blob/d5aaedee2739f1c73c667c579a8aee4fdde0f0ee/website/docusaurus.config.js#L39-L40

should `docs` be absolute as well?

**Comment by SimenB** [comment]
Heh, nope! Making `docs` absolute fails: `UnhandledPromiseRejectionWarning: Error: [docs] There is no docs to version !` (extra space at the end, fwiw)

**Comment by lex111** [comment]
Yeah, it's not very obvious, there's bit of inconsistency here, if `docsPath` can be relative, meanwhile `sidebarPath` can _only_ be absolute. Although we can "internally fix" sidebar path by making it absolute. Perhaps that would be better than forcing user to specify absolute path, WDYT?

**Comment by SimenB** [comment]
IMO either all paths should be supported as either relative or absolute (resolving relative ones relative to the config file or cwd (whatever it is you do today)) or they should all be required to be absolute. Either works for me, but inconsistency in which can be which is confusing as you say 👍 

Easiest here is probably to resolve `sidebarPath` if it's relative like you used to, although docu v2 is a good opportunity to force all paths to be absolute (which is just `path.resolve(__dirname, 'old string here')`, so it's not a complicated migration for people)
