### ISSUE TITLE
Docusaurus 2.0.0-beta.0, dynamic imports using backticks not working

### ISSUE THREAD

**Issue by goceee** [facebook/docusaurus#5009]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [x] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

I recently installed the docusaurus starter project using npx @docusaurus/init@latest init my-website classic and i tried using dynamic imports with the loadable/component package using backticks to dynamically import different SVG files, but it is not working, when I add a static path without backticks it works.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

A fork showcasing the issue: https://codesandbox.io/s/great-wright-gzyb7?file=/src/pages/index.js

Currently the svg is shown without dynamic imports.

1. Comment the **IconNormal** component
2. Uncomment the **Icon** component
3. The error appears

## Expected behavior

It should show the image in the same way as non-dynamic imports work

## Actual behavior

It throws an error that the svg could not be loaded

```
The above error occurred in the </assets/images/undraw_docusaurus_mountain-92989bc69aed8241aa3f59b1477f0e56.svg> component:

    at /assets/images/undraw_docusaurus_mountain-92989bc69aed8241aa3f59b1477f0e56.svg

    at InnerLoadable (webpack-internal:///./node_modules/@loadable/component/dist/loadable.esm.js:167:34)

    at LoadableWithChunkExtractor

    at Loadable

    at div

    at div

    at header

    at HomepageHeader (webpack-internal:///./src/pages/index.js:13:517)

    at div

    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:16:745)

    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:16:387)

    at UserPreferencesProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/UserPreferencesProvider/index.js:14:157)

    at ThemeProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/ThemeProvider/index.js:13:142)

    at LayoutProviders (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/LayoutProviders/index.js:14:30)

    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/Layout/index.js:21:33)

    at Home (webpack-internal:///./src/pages/index.js:13:1470)

    at LoadableComponent (webpack-internal:///./node_modules/@docusaurus/react-loadable/lib/index.js:1:2843)

    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:464:29)

    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:670:29)

    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:464:29)

    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:18:180)

    at C (webpack-internal:///./node_modules/react-router/esm/react-router.js:725:37)

    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:18:16)

    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:23:94)

    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:93:30)

    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:59:35)


Consider adding an error boundary to your tree to customize error handling behavior.

Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

```

## Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 14.17.0):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

## Reproducible demo
Demo at: https://codesandbox.io/s/great-wright-gzyb7?file=/src/pages/index.js
-->

**Comment by slorber** [comment]
Thanks

We use react-loadable component (and not @loadable/component) internally, but this is an implementation detail and we don't propose any way to use dynamic imports in your React app so far. This is not something we support and we'll wait for REact 18 for that.

Also we use webpack/svgr to turn svg files to React components. I'm not sure this loader even support a wildcard in dynamic imports. By logging `await import(`../../static/img/${name}.svg`)` you can see that it returns an URL, not a React component anymore, which does not surprise me much.

You are doing fancy things here, and Docusaurus never claimed to support what you are trying to do, so I consider it not a bug.

If you feel it should be supported, please open a canny feature request, and also provide a vanilla webpack project using dynamic loading of SVGs as a proof this is even possible. It is not for me a high-priority to support such feature in Docusaurus.

**Comment by goceee** [comment]
I tried with react-loadable, it still gives the same error, this only happens when using backticks in import.

Dynamic imports are supported by webpack, it is automatically available to use in Create React App with both react-loadable and @loadable/components, i was thinking it would be the same case with docusaurus.

**Comment by slorber** [comment]
> Dynamic imports are supported by webpack, it is automatically available to use in Create React App with both react-loadable and @loadable/components, I was thinking it would be the same case with docusaurus.

Dynamic imports are supported by Docusaurus, and we use them internally and it's not directly related to React loadable libs.

I don't think the backticks is the problem, but rather the `${name}` inside the dynamic import string.

Have you been able to use exactly the same (dynamic imports + string template module + backticks + SVGR) in CRA? Please show me a sandbox of that, as a proof other envs support this.
