### ISSUE TITLE
If update-notifier fails, then the cli fails

### ISSUE THREAD

**Issue by milesj** [facebook/docusaurus#5400]
### Prerequisites

- [x] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [x] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [x] I have read the console error message carefully (if applicable)

### Description

If `update-notifier` fails to load config from `~/.config`, then the Docusaurus CLI fails with the following error:

```
/private/var/tmp/_bazel_milesjohnson/a3f1e21faca691f85e7e54fa376a3339/sandbox/darwin-sandbox/16/execroot/workspace/node_modules/@docusaurus/core/bin/beforeCli.js:50
  Date.now() - notifier.config.get('lastUpdateCheck') < 50
                               ^
TypeError: Cannot read property 'get' of undefined
    at Object.<anonymous> (/private/var/tmp/_bazel_milesjohnson/a3f1e21faca691f85e7e54fa376a3339/sandbox/darwin-sandbox/16/execroot/workspace/node_modules/@docusaurus/core/bin/beforeCli.js:50:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/var/tmp/_bazel_milesjohnson/a3f1e21faca691f85e7e54fa376a3339/sandbox/darwin-sandbox/16/execroot/workspace/node_modules/@docusaurus/core/bin/docusaurus.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

When I log the notifier object, the `config` property does not exist.

```
UpdateNotifier {
  options: {
    pkg: { name: '@docusaurus/core', version: '2.0.0-beta.4' },
    updateCheckInterval: 3600000,
    distTag: 'latest'
  },
  packageName: '@docusaurus/core',
  packageVersion: '2.0.0-beta.4',
  updateCheckInterval: 3600000,
  disabled: false,
  shouldNotifyInNpmScript: undefined
}
```

It's also apparent that `update-notifier` fails as it logs this to the console.

```
┌─────────────────────────────────────────────────────────────────┐
│              @docusaurus/core update check failed               │
│               Try running with sudo or get access               │
│              to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) /Users/milesjohnson/.config │
└─────────────────────────────────────────────────────────────────┘
```

The failing code is here: https://github.com/facebook/docusaurus/blob/main/packages/docusaurus/bin/beforeCli.js#L31

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

This is hard to reproduce. We only ran into the issue because of Bazel and its sandboxing/hermetic approach (no access to user directory).

## Expected behavior

CLI doesn't crash.

## Actual behavior

CLI crashes.

## Your environment

This fails on 2.0.0-beta.4 BUT works on 2.0.0-beta.3.

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.0.0-beta.4
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Any
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Any

## Reproducible demo

Not simple to create a reproducible demo. However the fix should be rather easy, just check for the `config` property first.

**Comment by slorber** [comment]
Make sense, thanks for reporting

Can probably be reproduced by chmod the update notifier files permissions

Le ven. 20 août 2021 à 21:38, Miles Johnson ***@***.***> a
écrit :
