### ISSUE TITLE
I used <Navbar> inside <Layout> simply to show you that <Navbar> renders fine only inside <Layout>  Tag not otherwise will add screenshots of output for the following code which I need to achieve. Also I just want to get rid of Footer From <Layout> only need the Navbar so I better render only Navbar right?

### ISSUE THREAD

**Issue by The-Tech-Troll-Tube** [facebook/docusaurus#5404]
I used <Navbar> inside <Layout> simply to show you that <Navbar> renders fine only inside <Layout>  Tag not otherwise will add screenshots of output for the following code which I need to achieve. Also I just want to get rid of Footer From <Layout> only need the Navbar so I better render only Navbar right? 

```
import React, { useEffect, useState } from 'react';
import clsx from 'clsx';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import styles from './index.module.css';
import HomepageFeatures from '../components/HomepageFeatures';
import Slideshow from '../components/ReactSlider/ReactSlider';
import Footer from '@theme/Footer';
import Navbar from '@theme/Navbar';

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className={clsx('hero hero--transparent', styles.heroBanner)}
    style={{background: "transparent", position:"absolute", top:"20px", marginLeft:"5px", textAlign:"center", cursor:"default"}}
    >
      <div className="container" >
        <h1 className="hero_"
        style={{color:"#505050", cursor:"default"}} // top badge color
        >{siteConfig.title}</h1>
        <p className="hero__subtitle"
        style={{color:"#505050"}} // top badge tagline color
        >{siteConfig.tagline}</p>
        <div className={styles.buttons}>
          <Link
          style={{backgroundColor:"skyblue", color:"#505050"}}
            className="button button--secondary button--lg btncolor"
            to="/docs/intro">
            Products Page
          </Link>
        </div>
      </div>
    </header>
  );
}

export default function Home() {

  const [loading, setLoading] = useState(true);

useEffect(() => {
  setTimeout(() => {
    setLoading(false);
  }, 0.0000001);
}, []);

  const {siteConfig} = useDocusaurusContext();
  return (
    <div>  
    <Navbar/>
  {loading ?  console.log('loading...') :  
    <>
    <Slideshow />  
    <HomepageHeader />
    <main>
      <HomepageFeatures />
    </main>
   <Footer/>
    </>
    }  
  </div>  
);
```
};

![image](https://user-images.githubusercontent.com/86089105/130324133-bea527a3-2182-46e3-91dd-ef9781b803c5.png)

When Navbar Tag is Commented:-
![image](https://user-images.githubusercontent.com/86089105/130324754-a8523960-bda9-423f-a70d-aead2b967cea.png)

 
Error Image and Output:-
![image](https://user-images.githubusercontent.com/86089105/130324798-a322394f-1c50-4ede-bb2f-7c0b685bba12.png)

```
yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  

× Server
  Compiled with some errors in 21.15s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

    at useThemeContext (main:5853:186)
    at useColorModeToggle (main:5639:407)
    at Navbar (main:5646:2094)
    at d (main:48450:498)
    at bb (main:48453:16)
    at a.b.render (main:48459:43)
    at a.b.read (main:48458:83)
    at Object.exports.renderToString (main:48469:138)
    at doRender (main:3786:356)
    at async serverEntry_render (main:3785:294)



Error: Server-side rendering fails due to the error above.
Unable to build website for locale "en".
Error: Failed to compile with errors.
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\@docusaurus\core\lib\webpack\utils.js:203:24
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  

× Server
  Compiled with some errors in 20.35s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

    at useThemeContext (main:5853:186)
    at useColorModeToggle (main:5639:407)
    at Navbar (main:5646:2094)
    at bb (main:48453:16)
    at a.b.render (main:48459:43)
    at a.b.read (main:48458:83)
    at Object.exports.renderToString (main:48469:138)
    at doRender (main:3786:356)
    at async serverEntry_render (main:3785:294)


Unable to build website for locale "en".
Error: Failed to compile with errors.
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\@docusaurus\core\lib\webpack\utils.js:203:24
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
error Command failed with exit code 1.
yarn run v1.22.5
error Command "v1.22.5" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> $ docusaurus build
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a   
path was included, verify that the path is correct and try again.
At line:1 char:1
+ $ docusaurus build
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> [en] Creating an optimized production build...
At line:1 char:6
+ [en] Creating an optimized production build...
+      ~~~~~~~~
Unexpected token 'Creating' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> √ Client
√ : The term '√' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a   
path was included, verify that the path is correct and try again.
At line:1 char:1
+ √ Client
+ ~
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> x Server
× : The term '×' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a   
path was included, verify that the path is correct and try again.
At line:1 char:1
+ × Server
+ ~
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>   Compiled with some errors in 21.15s
Compiled : The term 'Compiled' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the   
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+   Compiled with some errors in 21.15s
+   ~~~~~~~~
    + FullyQualifiedErrorId : CommandNotFoundException
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> loading...
loading... : The term 'loading...' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of   
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ loading...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (loading...:String) [], CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> Docusaurus Node/SSR could not render static page with path "/" because of following error:
Docusaurus : The term 'Docusaurus' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of   
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Docusaurus Node/SSR could not render static page with path "/" becaus ...
+ ~~~~~~~~~~
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> Error: "useThemeContext" is used outside of "Layout" component. Please see https://docusaurus.io/docs/api/themes/configuration#usethemecontext.
Error: : The term 'Error:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the       
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (Error::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at useThemeContext (main:5853:186)
main:5853:186 : The term 'main:5853:186' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:25
+                         ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:5853:186:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at useColorModeToggle (main:5639:407)
main:5639:407 : The term 'main:5639:407' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:28
+                            ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:5639:407:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at Navbar (main:5646:2094)
main:5646:2094 : The term 'main:5646:2094' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the       
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:16
+                ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:5646:2094:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at d (main:48450:498)
main:48450:498 : The term 'main:48450:498' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the       
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:11
+           ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:48450:498:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at bb (main:48453:16)
main:48453:16 : The term 'main:48453:16' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:12
+            ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:48453:16:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at a.b.render (main:48459:43)
main:48459:43 : The term 'main:48459:43' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:20
+                    ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:48459:43:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at a.b.read (main:48458:83)
main:48458:83 : The term 'main:48458:83' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:18
+                  ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:48458:83:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at Object.exports.renderToString (main:48469:138)
main:48469:138 : The term 'main:48469:138' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the       
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:39
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at doRender (main:3786:356)
main:3786:356 : The term 'main:3786:356' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:18
+     at doRender (main:3786:356)
+                  ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:3786:356:String) [], CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at async serverEntry_render (main:3785:294)
main:3785:294 : The term 'main:3785:294' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the         
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:34
+     at async serverEntry_render (main:3785:294)
+                                  ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (main:3785:294:String) [], CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> Error: Server-side rendering fails due to the error above.
Error: : The term 'Error:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the       
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Error: Server-side rendering fails due to the error above.
    + CategoryInfo          : ObjectNotFound: (Error::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> Unable to build website for locale "en".
Unable : The term 'Unable' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the       
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Unable to build website for locale "en".
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (Unable:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> Error: Failed to compile with errors.
Error: : The term 'Error:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the       
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Error: Failed to compile with errors.
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (Error::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\@docusaurus\core\lib\webpack\utils.js:203:24
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
time               Specifies the time when command is to run.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.
"command"          Is the Windows NT command, or batch program to be run.

PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:554:14
The AT command has been deprecated. Please use schtasks.exe instead.

Invalid command.

The AT command schedules commands and programs to run on a computer at
a specified time and date. The Schedule service must be running to use
the AT command.

AT [\\computername] [ [id] [/DELETE] | /DELETE [/YES]]
    [ /EVERY:date[,...] | /NEXT:date[,...]] "command"

\\computername     Specifies a remote computer. Commands are scheduled on the
                   local computer if this parameter is omitted.
id                 Is an identification number assigned to a scheduled
                   command.
/delete            Cancels a scheduled command. If id is omitted, all the
                   scheduled commands on the computer are canceled.
/yes               Used with cancel all jobs command when no further
                   confirmation is desired.
/interactive       Allows the job to interact with the desktop of the user
                   who is logged on at the time the job runs.
/every:date[,...]  Runs the command on each specified day(s) of the week or
                   month. If date is omitted, the current day of the month
                   is assumed.
/next:date[,...]   Runs the specified command on the next occurrence of the
                   day (for example, next Thursday).  If date is omitted, the
                   current day of the month is assumed.

PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website>     at processQueueWorker (C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6 : The term 
'C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6' is not recognized as the name of a   
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct    
and try again.
At line:1 char:28
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  

× Server
  Compiled with some errors in 20.37s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  

× Server
  Compiled with some errors in 20.05s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

Error: "useThemeContext" is used outside of "Layout" component. Please see https://docusaurus.io/docs/api/themes/configuration#usethemecontext.   
    at useThemeContext (main:5853:186)
    at useColorModeToggle (main:5639:407)
    at Navbar (main:5646:2094)
    at d (main:48450:498)
    at bb (main:48453:16)
    at a.b.render (main:48459:43)
    at a.b.read (main:48458:83)
    at Object.exports.renderToString (main:48469:138)
    at doRender (main:3786:356)
    at async serverEntry_render (main:3785:294)













Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 w i t h Space e x i t Space c o d e Space 1 . Enter
 i n f o Space V i s i t Space h t t p s : / / y a r n p k g . c o m / e n / d o c s / c l i / r u n Space f o r Space d o c u m e n t a t i o n Space a b o u t Space t h i s Space c o m m a n d . Ctrl+c Ctrl+l UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace s t a r t Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace Ctrl+l b u i l d Enter
 Ctrl+l UpArrow Enter
 Ctrl+l

PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client

√ Server
  Compiled successfully in 20.14s

loading...

√ Client
  

* Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
 stored

Success! Generated static files in "build".

Use `npm run serve` command to test your build locally.

Done in 32.83s.
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  


√ Client
  


√ Client
  

× Server
  Compiled with some errors in 4.98s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

Error: "useThemeContext" is used outside of "Layout" component. Please see https://docusaurus.io/docs/api/themes/configuration#usethemecontext.   
    at useThemeContext (main:5853:186)
    at useColorModeToggle (main:5639:407)
    at Navbar (main:5646:2094)
    at d (main:48450:498)
PS C:\Users\Albin\Desktop\saji-website\leo-scientific-website> yarn build
yarn run v1.22.5
$ docusaurus build

[en] Creating an optimized production build...

√ Client
  


√ Client
  


√ Client
  

× Server
  Compiled with some errors in 16.13s

loading...
Docusaurus Node/SSR could not render static page with path "/" because of following error:

Error: "useThemeContext" is used outside of "Layout" component. Please see https://docusaurus.io/docs/api/themes/configuration#usethemecontext.   
    at useThemeContext (main:5853:186)
    at useColorModeToggle (main:5639:407)
    at Navbar (main:5646:2094)
    at d (main:48450:498)
    at bb (main:48453:16)
    at a.b.render (main:48459:43)
    at a.b.read (main:48458:83)
    at Object.exports.renderToString (main:48469:138)
    at doRender (main:3786:356)
    at async serverEntry_render (main:3785:294)



Error: Server-side rendering fails due to the error above.
Unable to build website for locale "en".
Error: Failed to compile with errors.
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\@docusaurus\core\lib\webpack\utils.js:203:24
    at C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (C:\Users\Albin\Desktop\saji-website\leo-scientific-website\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Originally posted by @The-Tech-Troll-Tube in https://github.com/facebook/docusaurus/issues/5403#issuecomment-903124441_

**Comment by Josh-Cena** [comment]
@slorber Interesting that this stays up for a month now🧐
