### ISSUE TITLE
beta.5 docs tags feature - better validation for malformed tags

### ISSUE THREAD

**Issue by sw-yx** [facebook/docusaurus#5478]
### Description

when i upgraded my docs repo https://github.com/temporalio/documentation/pull/619 to beta.5 i got a new error.

```
Starting the development server...
Can't process doc metadatas for doc at path "/Users/swyx/Temporal/documentation/docs/go/hello-world-tutorial.md" in version "current"
Can't process doc metadatas for doc at path "/Users/swyx/Temporal/documentation/docs/java/hello-world-tutorial.md" in version "current"
Loading of version failed for version "current"
TypeError: frontMatterTags.map is not a function
    at Object.normalizeFrontMatterTags (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/utils/lib/tags.js:37:106)
    at doProcessDocMetadata (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:164:23)
    at Object.processDocMetadata (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:177:16)
    at processVersionDoc (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/index.js:88:35)
    at Array.map (<anonymous>)
    at loadVersionDocsBase (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/index.js:95:45)
    at async doLoadVersion (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/index.js:102:34)
    at async loadVersion (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/index.js:166:28)
    at async Promise.all (index 0)
    at async Object.loadContent (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/plugin-content-docs/lib/index.js:174:33)
    at async /Users/swyx/Temporal/documentation/node_modules/@docusaurus/core/lib/server/plugins/index.js:58:46
    at async Promise.all (index 0)
    at async Object.loadPlugins (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/core/lib/server/plugins/index.js:57:27)
    at async Object.load (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/core/lib/server/index.js:186:82)
    at async start (/Users/swyx/Temporal/documentation/node_modules/@docusaurus/core/lib/commands/start.js:44:19)
error Command failed with exit code 1.
```

this is because the new docs tag feature (https://github.com/facebook/docusaurus/pull/3646) expects this format:

```
---
tags:
  - foo
  - bar
  - baz
---
```

and doesnt gracefully handle:

```
---
tags: foo, bar, baz
---
```

or:

```
---
tags: foo
---
```

we were already using tags in our own way so our errors arent important, but i do think the comma separated tags experience is important that helpful/good errors are important.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

yep

## Steps to reproduce

https://github.com/temporalio/documentation/pull/619

## Expected behavior

clean upgrade process, elegant handling of tags

**Comment by sw-yx** [comment]
i have tracked this down to beta.5. probably one of these commits broke us and WE shoudl update.

docusaurus-init, docusaurus-mdx-loader, docusaurus-plugin-content-blog, docusaurus-plugin-content-docs, docusaurus-theme-bootstrap, docusaurus-theme-classic, docusaurus-utils-validation
#5396 feat(plugin-blog): multi-authors support + authors.yml global configuration (@Josh-Cena)
docusaurus-plugin-content-blog, docusaurus-theme-classic
#5371 feat: make blog config options and navbar versions dropdown label translatable (@Josh-Cena)
docusaurus-plugin-content-blog, docusaurus-plugin-content-docs, docusaurus-theme-bootstrap, docusaurus-theme-classic, docusaurus-theme-common
#5375 feat: add metatags support for seo / blogposts #5373 (@johnnyreilly)
docusaurus-plugin-content-blog, docusaurus-plugin-content-docs, docusaurus-theme-bootstrap, docusaurus-theme-classic, docusaurus-theme-common, docusaurus-utils-validation, docusaurus-utils
#3646 feat: doc tags (same as blog tags) (@isaac-philip)

**Comment by sw-yx** [comment]
question: is this behavior you want or are you fine with a very strict format of docs tags?
recommendation: at LEAST handle error better here, OR handle comma separated tags

**Comment by Josh-Cena** [comment]
For some reason this shows up in my inbox...

As I mentioned in  https://github.com/facebook/docusaurus/pull/5433#discussion_r697847413, the Markdown front matter conforms to YAML syntax. Per YAML spec there are two ways to define an array:

```yml
---
- Item 1
- Item 2
- Item 3
---
[Item 1, Item 2, Item 3]
```

So comma-separated list without the square brackets isn't even valid YAML. It's not something Docusaurus can gracefully handle.

**Comment by sw-yx** [comment]
hmm i see and hear you. yes lets do the validation. I'm not for extending YAML, i'm just in favor of nice errors so that when people make common mistakes we help them get back on track.

**Comment by slorber** [comment]
> hmm i see and hear you. yes lets do the validation. I'm not for extending YAML, i'm just in favor of nice errors so that when people make common mistakes we help them get back on track.

We should definitively add nice validation messages. That's why I added a strict fail-fast validation step but Joi is a bit painful to use and default messages are not always nice, so I always prefer to add tests about validation messages.

I also plan to add a method like `createFrontMatter` or `processFrontMatter` that gives the opportunity to add/modify/normalize frontmatters before the validation step, so eventually you could transform `["tag1, tag2"]` to `["tag1", ”tag2"]` yourself if that make sense for your use-case and legacy docs
