### ISSUE TITLE
Can't build a docker image after adding @docusaurus/plugin-ideal-image configuration

### ISSUE THREAD

**Issue by theCodingJohn** [facebook/docusaurus#5558]
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io
- [X] I have read the console error message carefully (if applicable)

### Description
I am getting this error whenever I try to build a docker image

<img width="1355" alt="131722838-f86a9233-cd0f-48a5-ae09-f562c25600b3" src="https://user-images.githubusercontent.com/67894296/132986281-875091c2-37aa-4fa2-9473-04068ef7b2fd.png">

```js
PS D:\theCodingJohn\New folder\my-website> docker build -t springville .
[+] Building 9.4s (11/15)
 => [internal] load build definition from Dockerfile                                                        0.1s 
 => => transferring dockerfile: 32B                                                                         0.0s 
 => [internal] load .dockerignore                                                                           0.0s 
 => => transferring context: 34B                                                                            0.0s 
 => [internal] load metadata for docker.io/library/node:14.16.0-alpine3.10                                  2.7s 
 => [auth] library/node:pull token for registry-1.docker.io                                                 0.0s 
 => [internal] load build context                                                                           0.1s 
 => => transferring context: 2.58kB                                                                         0.0s 
 => [stage-0 1/6] FROM docker.io/library/node:14.16.0-alpine3.10@sha256:a9c1dca1d75c99119323a8487e2b8ecaf5  0.0s 
 => CACHED [stage-0 2/6] WORKDIR /app                                                                       0.0s 
 => CACHED [stage-0 3/6] COPY package.json yarn.lock ./                                                     0.0s 
 => CACHED [stage-0 4/6] RUN yarn install --production                                                      0.0s 
 => [stage-0 5/6] ADD . ./                                                                                  0.2s 
 => ERROR [stage-0 6/6] RUN yarn build                                                                      6.2s 
------
 > [stage-0 6/6] RUN yarn build:
#14 1.415 yarn run v1.22.5
#14 1.469 $ docusaurus build
#14 4.732
#14 4.732 [en] Creating an optimized production build...
#14 6.066 Unable to build website for locale "en".
#14 6.067 Error:
#14 6.067 Something went wrong installing the "sharp" module
#14 6.067
#14 6.067 Error relocating /app/node_modules/sharp/build/Release/../../vendor/8.10.6/lib/libvips-cpp.so.42: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
#14 6.067
#14 6.067 - Remove the "node_modules/sharp" directory then run
#14 6.067   "npm install --ignore-scripts=false --verbose sharp" and look for errors
#14 6.067 - Consult the installation documentation at https://sharp.pixelplumbing.com/install
#14 6.067 - Search for this error at https://github.com/lovell/sharp/issues
#14 6.067
#14 6.067     at Object.<anonymous> (/app/node_modules/sharp/lib/constructor.js:32:9)
#14 6.067     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#14 6.067     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
#14 6.067     at Module.load (internal/modules/cjs/loader.js:928:32)
#14 6.067     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
#14 6.067     at Module.require (internal/modules/cjs/loader.js:952:19)
#14 6.067     at require (internal/modules/cjs/helpers.js:88:18)
#14 6.067     at Object.<anonymous> (/app/node_modules/sharp/lib/index.js:3:15)
#14 6.067     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#14 6.067     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
#14 6.067     at Module.load (internal/modules/cjs/loader.js:928:32)
#14 6.067     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
#14 6.067     at Module.require (internal/modules/cjs/loader.js:952:19)
#14 6.067     at require (internal/modules/cjs/helpers.js:88:18)
#14 6.067     at Object.<anonymous> (/app/node_modules/@docusaurus/responsive-loader/lib/adapters/sharp.js:3:15) 
#14 6.067     at Module._compile (internal/modules/cjs/loader.js:1063:30)
#14 6.085 error Command failed with exit code 1.
#14 6.088 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It happened after I added @docusaurus/plugin-ideal-image configuration to my app. 

I'm pretty sure it is caused by that, 'cause I also tried it to a freshly installed docusaurus app and just added my docker configuration. I am able to build a docker image just fine as long as I'm not using @docusaurus/plugin-ideal-image.
### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Your environment

- Docusaurus version used: 2.0.0-beta.6

**Comment by Josh-Cena** [comment]
Relevant issue in sharp: https://github.com/lovell/sharp/issues/1979

**Comment by theCodingJohn** [comment]
Indeed, I am using Alpine3.10. I upgraded it to Alpine3.11 and it works! Thanks @Josh-Cena
