### ISSUE TITLE
unsupport react hooks

### ISSUE THREAD

**Issue by moshuying** [facebook/docusaurus#6636]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

```mdx
import App from '../../../Effects/main'
<App />
```

![image](https://user-images.githubusercontent.com/37231523/152956157-f181784c-ba44-4d85-86ac-e0d910d2dcd0.png)

### Steps to reproduce

```sh
name=demo-porject-website
rm -rf $name
npx create-docusaurus@latest $name classic --skip-install
npm i
npm start
```
write code in `demo-porject-website/docs/tutorial-basics/markdown-features.mdx`

got errors

### Expected behavior

error

### Actual behavior

```txt
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js?9c41:14906:1)
    at useState (react.development.js?dad3:1508:1)
    at App (main.jsx?cb7e:55:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
throwInvalidHookError @ react-dom.development.js?9c41:14906
useState @ react.development.js?dad3:1508
App @ main.jsx?cb7e:55
renderWithHooks @ react-dom.development.js?ac89:14985
mountIndeterminateComponent @ react-dom.development.js?ac89:17811
beginWork @ react-dom.development.js?ac89:19049
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
beginWork$1 @ react-dom.development.js?ac89:23964
performUnitOfWork @ react-dom.development.js?ac89:22776
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21881
updateContainer @ react-dom.development.js?ac89:25482
eval @ react-dom.development.js?ac89:26021
unbatchedUpdates @ react-dom.development.js?ac89:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
render @ react-dom.development.js?ac89:26103
eval @ clientEntry.js?1755:21
Promise.then(异步)
eval @ clientEntry.js?1755:21
./node_modules/@docusaurus/core/lib/client/clientEntry.js @ main.js:95
__webpack_require__ @ runtime~main.js:36
__webpack_exec__ @ main.js:1635
(匿名) @ main.js:1636
__webpack_require__.O @ runtime~main.js:83
(匿名) @ main.js:1637
webpackJsonpCallback @ runtime~main.js:1314
(匿名) @ main.js:9
react_devtools_backend.js:4061 
        
       Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    at div
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXDefaultShortcode
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at p
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:13:1710)
    at div
    at article
    at div
    at div
    at div
    at DocItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocItem/index.js:22:42)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at main
    at div
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:13:96)
    at div
    at MobileSecondaryMenuProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/mobileSecondaryMenu.js:13:226)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:27:804)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:27:513)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:16:492)
    at TabGroupChoiceProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabGroupChoiceUtils.js:13:1193)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/announcementBarUtils.js:22:561)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/colorModeUtils.js:16:1839)
    at LayoutProviders (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/LayoutProviders/index.js:12:39)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/Layout/index.js:22:33)
    at DocPageContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocPage/index.js:25:38)
    at DocsSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsUtils.js:27:903)
    at DocsVersionProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsUtils.js:27:197)
    at DocPage (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocPage/index.js:27:2009)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:18:180)
    at C (webpack-internal:///./node_modules/react-router/esm/react-router.js:705:37)
    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:17:25)
    at BrowserContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/browserContext.js:18:126)
    at DocusaurusContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/docusaurusContext.js:19:495)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:13:96)
    at App
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
overrideMethod @ react_devtools_backend.js:4061
printWarning @ react-dom.development.js?ac89:67
error @ react-dom.development.js?ac89:43
validateDOMNesting @ react-dom.development.js?ac89:10083
createInstance @ react-dom.development.js?ac89:10181
completeWork @ react-dom.development.js?ac89:19464
completeUnitOfWork @ react-dom.development.js?ac89:22815
performUnitOfWork @ react-dom.development.js?ac89:22787
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21881
updateContainer @ react-dom.development.js?ac89:25482
eval @ react-dom.development.js?ac89:26021
unbatchedUpdates @ react-dom.development.js?ac89:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
render @ react-dom.development.js?ac89:26103
eval @ clientEntry.js?1755:21
Promise.then(异步)
eval @ clientEntry.js?1755:21
./node_modules/@docusaurus/core/lib/client/clientEntry.js @ main.js:95
__webpack_require__ @ runtime~main.js:36
__webpack_exec__ @ main.js:1635
(匿名) @ main.js:1636
__webpack_require__.O @ runtime~main.js:83
(匿名) @ main.js:1637
webpackJsonpCallback @ runtime~main.js:1314
(匿名) @ main.js:9
react_devtools_backend.js:4061 
        
       The above error occurred in the <App> component:

    at App (webpack-internal:///../react-three/sparksAndEffects/main.jsx:17:265)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (webpack-internal:///./docs/tutorial-basics/markdown-features.mdx:13:1710)
    at div
    at article
    at div
    at div
    at div
    at DocItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocItem/index.js:22:42)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at main
    at div
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:13:96)
    at div
    at MobileSecondaryMenuProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/mobileSecondaryMenu.js:13:226)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:27:804)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsPreferredVersion/DocsPreferredVersionProvider.js:27:513)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:16:492)
    at TabGroupChoiceProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/tabGroupChoiceUtils.js:13:1193)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/announcementBarUtils.js:22:561)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/colorModeUtils.js:16:1839)
    at LayoutProviders (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/LayoutProviders/index.js:12:39)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/Layout/index.js:22:33)
    at DocPageContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocPage/index.js:25:38)
    at DocsSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsUtils.js:27:903)
    at DocsVersionProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/docsUtils.js:27:197)
    at DocPage (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib-next/theme/DocPage/index.js:27:2009)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:18:180)
    at C (webpack-internal:///./node_modules/react-router/esm/react-router.js:705:37)
    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:17:25)
    at BrowserContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/browserContext.js:18:126)
    at DocusaurusContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/docusaurusContext.js:19:495)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:13:96)
    at App
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ react_devtools_backend.js:4061
logCapturedError @ react-dom.development.js?ac89:20085
callback @ react-dom.development.js?ac89:20154
callCallback @ react-dom.development.js?ac89:12318
commitUpdateQueue @ react-dom.development.js?ac89:12339
commitLifeCycles @ react-dom.development.js?ac89:20709
commitLayoutEffects @ react-dom.development.js?ac89:23426
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
commitRootImpl @ react-dom.development.js?ac89:23151
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
commitRoot @ react-dom.development.js?ac89:22990
performSyncWorkOnRoot @ react-dom.development.js?ac89:22329
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21881
updateContainer @ react-dom.development.js?ac89:25482
eval @ react-dom.development.js?ac89:26021
unbatchedUpdates @ react-dom.development.js?ac89:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
render @ react-dom.development.js?ac89:26103
eval @ clientEntry.js?1755:21
Promise.then(异步)
eval @ clientEntry.js?1755:21
./node_modules/@docusaurus/core/lib/client/clientEntry.js @ main.js:95
__webpack_require__ @ runtime~main.js:36
__webpack_exec__ @ main.js:1635
(匿名) @ main.js:1636
__webpack_require__.O @ runtime~main.js:83
(匿名) @ main.js:1637
webpackJsonpCallback @ runtime~main.js:1314
(匿名) @ main.js:9
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi!

1. You didn't provide a reproduction. It's impossible to reproduce given this limited information. I at least need the code for `../../../Effects/main`, which looks like outside the Docusaurus project you just created.
2. It's very possible that you have imported from a module outside your Docusaurus app, which uses another React version. Please check your `node_modules` to see if you have two versions of React installed.
3. Please don't use the GitHub issue tracker as a support forum. Unless you can prove it's a Docusaurus bug, ask on Discord first.
