### ISSUE TITLE
[ERROR] Error: Cannot mix different versions of joi schemas when upgrading from 2.0.0-beta.14 to 2.0.0-beta.16

### ISSUE THREAD

**Issue by Deflaimun** [facebook/docusaurus#6785]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

After upgrading from version 2.0.0-beta.14 to 2.0.0-beta.16, [following this tutorial](https://docusaurus.io/docs/installation#updating-your-docusaurus-version)

we can´t run `npm start` anymore because it returns this error message:
```
[INFO] Starting the development server...
[ERROR] Error: Cannot mix different versions of joi schemas
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site@0.0.0 start: `docusaurus start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the site@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paulo\AppData\Roaming\npm-cache\_logs\2022-02-28T13_50_37_511Z-debug.log

```

I have tried the following with no success:
 - Reverted all changes and executed the process again
 - Following the steps [described here](https://github.com/easyops-cn/docusaurus-search-local/issues/31)
 - Manually deleted package-lock.json and ran `npm install` again
 - [Changing manually the version on package-lock.json](https://github.com/redpanda-data/documentation/commit/8e1bf6dc0d8b2fc2e4e717d8f97f880714299760)

Here's the detailed log message:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle site@0.0.0~prestart: site@0.0.0
6 info lifecycle site@0.0.0~start: site@0.0.0
7 verbose lifecycle site@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle site@0.0.0~start: PATH: C:\Users\paulo\AppData\Roaming\nvm\v14.16.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Projetos\1 - GitHub\StackBuilders\documentation\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Go\bin;C:\ProgramData\chocolatey\bin;C:\Users\paulo\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Ruby30-x64\bin;C:\Users\paulo\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\paulo\AppData\Local\Programs\Python\Python310\;C:\Users\paulo\AppData\Local\Microsoft\WindowsApps;C:\Users\paulo\go\bin;C:\Users\paulo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\paulo\AppData\Roaming\npm;C:\Users\paulo\AppData\Local\Microsoft\WindowsApps;C:\Users\paulo\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle site@0.0.0~start: CWD: C:\Projetos\1 - GitHub\StackBuilders\documentation
10 silly lifecycle site@0.0.0~start: Args: [ '/d /s /c', 'docusaurus start' ]
11 silly lifecycle site@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle site@0.0.0~start: Failed to exec start script
13 verbose stack Error: site@0.0.0 start: `docusaurus start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\paulo\AppData\Roaming\nvm\v14.16.1\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\paulo\AppData\Roaming\nvm\v14.16.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid site@0.0.0
15 verbose cwd C:\Projetos\1 - GitHub\StackBuilders\documentation
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error site@0.0.0 start: `docusaurus start`
22 error Exit status 1
23 error Failed at the site@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Reproducible demo

https://github.com/redpanda-data/documentation/tree/update/16

### Steps to reproduce

Start from v.14
Update to v.16 
run `npm install`
run `npm start`

### Expected behavior

Running environment

### Actual behavior

```
[ERROR] Error: Cannot mix different versions of joi schemas
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! site@0.0.0 start: `docusaurus start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the site@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\paulo\AppData\Roaming\npm-cache\_logs\2022-02-28T14_40_23_658Z-debug.log
```

### Your environment

- Public source code: https://github.com/redpanda-data/documentation/tree/update/16
- Public site URL: https://docs.redpanda.com/
- Docusaurus version used:  2.0.0-beta.16
- Environment name and version (e.g. Chrome 89, Node.js 16.4): 
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10 Version	10.0.19043 Build 19043

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Still waiting for the OP to give me permissions, since this is a private repo. We are in touch on Discord.

**Comment by slorber** [comment]
I'd suggest trying to delete the `package-lock.json` file and reinstall

If this doesn't work, run `npm why joi` and paste the output there

**Comment by Deflaimun** [comment]
@Josh-Cena looks like the NPM/node version was indeed the culprit here. 
Upgrading them and forcing the values on package.json solved the issue.

Here's how my package.json looks like now

```json
{
  "name": "site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  },
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.16",
    "@docusaurus/preset-classic": "2.0.0-beta.16",
    "@easyops-cn/docusaurus-search-local": "^0.21.4",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^6.2.0",
    "clsx": "^1.1.1",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "raw-loader": "^4.0.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url-loader": "^4.1.1"
  },
  "engines": {
    "node": ">=16.13.2",
    "npm": ">=8.3.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by Josh-Cena** [comment]
Great to know it's solved! If you don't have further queries, feel free to remove me from the organization

**Comment by russurquhart** [comment]
I am having this problem as well. I have tried deduping but no luck! What did you do to resolve it? I have deleted the package-lock.json file and still no luck.

**Comment by lamaro** [comment]
In my case i've solved this issue changing from npm to yarn. Localhost was using yarn and AWS npm.

**Comment by rajanmishra** [comment]
We can use overrides in package Json to use same version for other dependent packages
 "overrides": {
    "hapi-swagger": {
      "swagger-ui-dist": "3.X.X",
      "joi": "16.X.X"
    }
  },
