### ISSUE TITLE
Builds with esbuild-loader >= 2.17.0 are failing

### ISSUE THREAD

**Issue by mxschmitt** [facebook/docusaurus#6901]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

When using `esbuild-loader` with docusaurus, builds start failing if `esbuild-loader` >= `v1.17.0`.

Relates: https://github.com/facebook/docusaurus/issues/4765

Upstream commit range: https://github.com/privatenumber/esbuild-loader/compare/v2.16.0...v2.17.0

(this is more of a tracking issue for users who are encountering this so they can discover it. Its most likely not an issue with docusaurus itself. If this is against the issue policies in this repo, feel free to close) 

### Steps to reproduce

Repro:

1. `npx create-docusaurus@latest my-website classic --typescript`
2. Add the following to the config:
  ```
  webpack: {
    jsLoader: (isServer) => ({
      loader: require.resolve('esbuild-loader'),
      options: {
        loader: 'tsx',
        format: isServer ? 'cjs' : undefined,
        target: isServer ? 'node12' : 'es2017',
      },
    }),
  }
  ```
3. `npm run build`

### Expected behavior

It works.

### Actual behavior

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Your environment

- Public source code:  See the repro
- Public site URL: N/A
- Docusaurus version used: beta-17
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 14, Chrome 100
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS 12.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mxschmitt** [comment]
I was bisecting it a bit more on `esbuild` level, these are my results:

- 0.14.5 bad
- 0.14.4 invalid 
- 0.14.3 good

why invalid?

```
➜  esbuild-loader npm i
npm ERR! code 1
npm ERR! path /Users/max/development/tmp/my-website/node_modules/esbuild-loader/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/max/development/tmp/my-website/node_modules/esbuild-loader/node_modules/esbuild/install.js:96
npm ERR!     throw new Error(`Expected ${JSON.stringify("0.14.4")} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Expected "0.14.4" but got "0.14.3"
npm ERR!     at validateBinaryVersion (/Users/max/development/tmp/my-website/node_modules/esbuild-loader/node_modules/esbuild/install.js:96:11)
npm ERR!     at /Users/max/development/tmp/my-website/node_modules/esbuild-loader/node_modules/esbuild/install.js:242:5

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/max/.npm/_logs/2022-03-11T23_47_50_926Z-debug-0.log
```

**Comment by mxschmitt** [comment]
I can confirm this works, thank you very much @Josh-Cena, have a great weekend. 💯
