### ISSUE TITLE
[1.1.3] npm start -> RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by philipmjohnson** [facebook/Docusaurus#697]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Environment

Docusaurus 1.1.3

### Steps to Reproduce

(Write your steps here:)

1. clone https://github.com/openpowerquality/docusaurus
2. cd website
2. npm install
3. npm update

### Expected Behavior

The system should come up.

### Actual Behavior

```
npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

LiveReload server started on port 35729
/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/docusaurus/lib/start-server.js:73
        throw ex;
        ^

RangeError: Maximum call stack size exceeded
    at Gaze._watchDir (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/gaze.js:331:17)
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/gaze.js:387:10
    at iterate (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:69:5)
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:78:11
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/gaze.js:452:5
    at iterate (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:69:5)
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:78:11
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/gaze.js:452:5
    at iterate (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:69:5)
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gaze/lib/helper.js:78:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `docusaurus-start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philipjohnson/.npm/_logs/2018-05-24T17_31_59_565Z-debug.log
```
### Reproducible Demo

1. clone https://github.com/openpowerquality/docusaurus
2. cd website
2. npm install
3. npm update

**Comment by yangshun** [comment]
@philipmjohnson Please test out 1.1.4 and let us know if it fixes the issue for you.

**Comment by philipmjohnson** [comment]
Unfortunately, I just did: 

  * `rm -rf node_modules`
  * `npm install`
  * `npm update`
  * `npm start`

and got the error: `Error: Cannot find module 'react-dev-utils/openBrowser'`

Here's the full output:

```
~/g/o/d/website (master|✚2) $ rm -rf node_modules
~/g/o/d/website (master|✚2) $ npm install

> gifsicle@3.0.4 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1437 packages in 17.236s
~/g/o/d/website (master|✚2) $ npm update
+ npm@6.1.0
added 2 packages, removed 2 packages and updated 16 packages in 14.916s
~/g/o/d/website (master|✚2) $ npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

module.js:549
    throw err;
    ^

Error: Cannot find module 'react-dev-utils/openBrowser'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/docusaurus/lib/start-server.js:27:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `docusaurus-start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/philipjohnson/.npm/_logs/2018-05-26T16_29_27_885Z-debug.log
~/g/o/d/website (master|✚2) $ 
```

**Comment by philipmjohnson** [comment]
And there's more.  I did a:

 * `npm install --save-dev react-dev-utils`
 * `npm start`

And then got the following error:

```
~/g/o/d/website (master|✚2) $ npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

Docusaurus server started on port 3000
LiveReload server started on port 35729
Error: Couldn't find preset "env" relative to directory "/Users/philipjohnson/github/openpowerquality/docusaurus/website/core"
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
```

**Comment by philipmjohnson** [comment]
Got it to work, but had to:

* `npm install --save-dev babel-cli babel-preset-env`
* `npm install --save-dev react`

Here's the trail:

```
~/g/o/d/website (master|✚2) $ npm install --save-dev babel-cli babel-preset-env

> fsevents@1.2.4 install /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/fsevents
> node install

[fsevents] Success: "/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ babel-preset-env@1.7.0
+ babel-cli@6.26.0
added 86 packages in 10.405s
~/g/o/d/website (master|✚2) $ npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

Docusaurus server started on port 3000
LiveReload server started on port 35729
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/philipjohnson/github/openpowerquality/docusaurus/website/core/Footer.js:8:15)
    at Module._compile (module.js:652:30)
    at loader (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
^C~                                                                                                                                  ~/g/o/d/website (master|✚2) $ npm install --save-dev react
+ react@16.4.0
added 1 package in 7.552s
~/g/o/d/website (master|✚2) $ npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

Docusaurus server started on port 3000
LiveReload server started on port 35729
```

**Comment by philipmjohnson** [comment]
My working package.json:

https://github.com/openpowerquality/docusaurus/blob/docusaurus-1.1.4/website/package.json

**Comment by JoelMarcey** [comment]
@philipmjohnson Just published 1.1.5 - can you test now? Thanks for bringing this to our attention.

**Comment by philipmjohnson** [comment]
I'm sorry to say this, but still getting the "env error" I got before, and fixed with additional package installs:

```
[~/github/openpowerquality/docusaurus/website]-> rm -rf node_modules/
[~/github/openpowerquality/docusaurus/website]-> npm install

> gifsicle@3.0.4 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
added 1493 packages in 17.299s
[~/github/openpowerquality/docusaurus/website]-> npm update
+ npm@6.1.0
added 2 packages, removed 2 packages and updated 16 packages in 15.035s
[~/github/openpowerquality/docusaurus/website]-> npm start

> @ start /Users/philipjohnson/github/openpowerquality/docusaurus/website
> docusaurus-start

Docusaurus server started on port 3000
LiveReload server started on port 35729
Error: Couldn't find preset "env" relative to directory "/Users/philipjohnson/github/openpowerquality/docusaurus/website/core"
    at /Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/philipjohnson/github/openpowerquality/docusaurus/website/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)

```

**Comment by JoelMarcey** [comment]
Hmmm.. How are you testing this? I get that `env` error when I try to utilize a local version of Docusaurus for testing. https://github.com/facebook/Docusaurus/blob/master/admin/local-third-party-project-testing.md#clowntown

Particularly, I have to install `npm install babel-preset-env@^1.7.0`.

But this should work on a site that is using the package of Docusaurus on `npm`

**Comment by JoelMarcey** [comment]
For example, I just created a new site via `docusaurus-init` and the `yarn start` brought up the site fine.

I am not saying there isn't anything wrong, I just want to make sure there is before doing yet another fix 😄

**Comment by JoelMarcey** [comment]
In your site can you do the following:

```
rm -rf node_modules
rm -rf package-lock.json
rm -rf yarn.lock
yarn install
yarn start
```

**Comment by JoelMarcey** [comment]
The `react-dev-utils` was definitely a legit issue. The `env` issue is a little more suspect to me because I have to do similar things when testing from a local version of Docusaurus.

**Comment by philipmjohnson** [comment]
OK, the problem was I didn't delete package-lock.json before rebuilding. Now it works.

Thanks for all the troubleshooting.

**Comment by maht0rz** [comment]
@bildungsroman i'm facing the same issue, even with `v1.13.0`
