### ISSUE TITLE
Should not assume package.json is available at CWD

### ISSUE THREAD

**Issue by wangjiaojiao77** [facebook/docusaurus#7161]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description
I put everything related to docusaurus in the `docs` folder and level it with `package.json`, there was no problem before, but recently there was an error.

everything related to the document is in the `docs` folder, the `docs` directory structure as follows:
```
docs      
├── babel.config.js
├── build
│   └── copyTranslations.js
├── docs
│   └── getting-started.md
├── docusaurus.config.js
├── i18n
│   └── zh-cn
│       ├── code.json
│       ├── docusaurus-plugin-content-blog
│       │   └── options.json
│       ├── docusaurus-plugin-content-docs
│       │   ├── current
│       │   └── current.json
│       └── docusaurus-theme-classic
│           ├── footer.json
│           └── navbar.json
├── sidebars.js
├── src
│   ├── css
│   │   └── custom.css
│   ├── pages
│   │   ├── index.js
│   │   └── index.module.css
│   └── theme
│       └── ReactLiveScope
│           └── index.js
└── static
    └── img
        └── .gitkeep
```

package.json
```
{
  "scripts": {
    "docs": "cd docs && docusaurus",
    "docs:dev": "cd docs && docusaurus start",
    "docs:build": "cd docs && docusaurus build",
    "docs:swizzle": "cd docs && docusaurus swizzle",
    "docs:deploy": "cd docs && docusaurus deploy",
    "docs:clear": "cd docs && docusaurus clear",
    "docs:serve": "cd docs && docusaurus serve",
    "docs:write-translations": "cd docs && docusaurus write-translations",
    "docs:write-heading-ids": "cd docs && docusaurus write-heading-ids",
    "docs:copy-translations": "node build/generateExportFile.js"
  },
  "devDependencies": {
    "@docusaurus/core": "2.0.0-beta.15",
    "@docusaurus/preset-classic": "2.0.0-beta.15",
    "@docusaurus/theme-live-codeblock": "^2.0.0-beta.15",
    "docusaurus-plugin-module-alias": "0.0.2",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "webpack": "^5.61.0",
    "webpack-cli": "^4.3.0"
  }
}
```

then running the `npm run docs:build` and other docusaurus-related commands to get an error:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/jojo/oker/blade/docs/package.json'
Require stack:
- /Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/beforeCli.js
- /Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/beforeCli.js:84:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/docusaurus.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/beforeCli.js',
    '/Users/jojo/oker/blade/node_modules/@docusaurus/core/bin/docusaurus.js'
  ]
}
```

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by Josh-Cena** [comment]
This has been brought up in the past, but I didn't find is severe enough for an immediate fix. The problem is indeed that we assume the package.json file exists at the root of site dir (which defaults to CWD). We have multiple places where we make that assumption.

I plan to do a minor refactor regarding importing various JSON modules (mostly package.json) and I'll take a look at this.

For the time being, please prefer using the [`siteDir` argument](https://docusaurus.io/docs/cli#docusaurus-start-sitedir) instead of using `cd docs`—it's almost always a bad idea to change CWD in the middle of an npm script.

```bash
yarn start docs
```

**Comment by fiveLucky** [comment]
This is a good issue.

**Comment by Josh-Cena** [comment]
@slorber This is the case where a user has a "monorepo-like" FS structure but does not have multiple package.json files. I've seen this multiple times, and very often they would use `cd` in their npm script.
