### ISSUE TITLE
githubPort configuration setting is reported as not recognised in docusaurus.config.js

### ISSUE THREAD

**Issue by mhughes2k** [facebook/docusaurus#7359]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Trying to execute the npm deploy command with the setting githubPort = '7999', results in an error:
[ERROR] Error: These field(s) ("githubPort",) are not recognized in docusaurus.config.js.
If you still want these fields to be in your configuration, put them in the "customFields" field.
See https://docusaurus.io/docs/api/docusaurus-config/#customfields
    at validateConfig (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/configValidation.js:201:15)
    at loadSiteConfig (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/config.js:25:62)
    at async loadContext (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/index.js:31:63)
    at async build (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/commands/build.js:50:21)

### Steps to reproduce

1. add a githubPort = '7999', option to docusaurus.config.js
2. run the deploy command

### Expected behavior

1. add a githubPort = '7999', option to docusaurus.config.js
2. run the deploy command
3. Deployment should run without an error

### Actual behavior

> docs@0.0.0 build
> docusaurus build

[ERROR] Error: These field(s) ("githubPort",) are not recognized in docusaurus.config.js.
If you still want these fields to be in your configuration, put them in the "customFields" field.
See https://docusaurus.io/docs/api/docusaurus-config/#customfields
    at validateConfig (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/configValidation.js:201:15)
    at loadSiteConfig (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/config.js:25:62)
    at async loadContext (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/server/index.js:31:63)
    at async build (/home/igs03102/sme/docs/node_modules/@docusaurus/core/lib/commands/build.js:50:21)

### Self-service

- [X] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Thanks for the report! Quite funny that `githubHost` is in the schema while `githubPort` is not. PRs welcome. In the meantime, you can get around it by using a `GITHUB_PORT` environment variable.

**Comment by mhughes2k** [comment]
Done a PR for this, seems like a 1-line addition to the validation file.
