### ISSUE TITLE
Unable to run example docs

### ISSUE THREAD

**Issue by vacarsu** [facebook/Docusaurus#741]
### Is this a bug report?

yes

I just did a fresh install of docusaurus globally.
```npm install --global docusaurus-init```
I then cded into the website directory and ran npm run start. The server starts fine and my browser opened a tab at http://localhost:3000/

However I got this error: 
```
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 1, attempted to resolve relative to "/Users/alexlopez/Desktop/uikit-react/website/core"
    at /usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

**Comment by JoelMarcey** [comment]
@vacarsu Hi - did you do `npm install --global docusaurus` or `npm install --global docusaurus-init` as discussed here: https://docusaurus.io/docs/en/installation

**Comment by vacarsu** [comment]
Sorry it was docusaurus-init, updated the post.

**Comment by JoelMarcey** [comment]
I just ran the following steps:

1. `npm install --global docusaurus-init`
2. `mkdir docusaurus-issue-741`
3. `cd docusaurus-issue-741`
4. `docusaurus-init`
5. `cd website`
6. `mv blog-examples-from-docusaurus/ blog`
7. `mv ../docs-examples-from-docusaurus/ ../docs`
8. `yarn start`

```
Using globally installed version of Yarn
yarn run v1.5.1
warning package.json: No license field
$ docusaurus-start
Docusaurus server started on port 3000
LiveReload server started on port 35729
```

And the test site came up.

Please try running exactly as I ran and also provide more details about your system, etc. if it still doesn't work.

**Comment by vacarsu** [comment]
I just tried that but I got the same issue.

```
Alexs-MacBook-Pro-2:uikit-react alexlopez$ npm install --global docusaurus-init
/usr/local/bin/docusaurus-init -> /usr/local/lib/node_modules/docusaurus-init/initialize.js
+ docusaurus-init@1.0.1
updated 1 package in 1.81s
Alexs-MacBook-Pro-2:uikit-react alexlopez$ mkdir docusaurus-issue-741
Alexs-MacBook-Pro-2:uikit-react alexlopez$ cd docusaurus-issue-741
Alexs-MacBook-Pro-2:docusaurus-issue-741 alexlopez$ docusaurus-init
Website folder created!

Installing latest version of Docusaurus in website.

yarn add v0.19.1
info No lockfile found.
warning No license field
[1/4] Resolving packages...
warning docusaurus > markdown-toc > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning docusaurus > imagemin-jpegtran > jpegtran-bin > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util isdeprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
error tree-node-cli@1.2.2: The engine "yarn" is incompatible with this module. Expected version ">=0.27.5 || >=1.0.0-20170811".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Docusaurus installed in website folder!

yarn run v0.19.1
$ docusaurus-examples
Wrote docusaurus scripts to package.json file.

docusaurus-issue-741
├── docs-examples-from-docusaurus
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md
│   ├── exampledoc4.md
│   └── exampledoc5.md
└── website
    ├── blog-examples-from-docusaurus
    │   ├── 2016-03-11-blog-post.md
    │   ├── 2017-04-10-blog-post-two.md
    │   ├── 2017-09-25-testing-rss.md
    │   ├── 2017-09-26-adding-rss.md
    │   └── 2017-10-24-new-version-1.0.0.md
    ├── core
    │   └── Footer.js
    ├── package.json
    ├── pages
    │   └── en
    │       ├── help.js
    │       ├── index.js
    │       └── users.js
    ├── sidebars.json
    ├── siteConfig.js
    └── static
        ├── css
        │   └── custom.css
        └── img
            ├── docusaurus.svg
            ├── favicon
            │   └── favicon.ico
            ├── favicon.png
            └── oss_logo.png
Rename docusaurus-issue-741/docs-examples-from-docusaurus to docusaurus-issue-741/docs to see the example docs on your site.

Rename docusaurus-issue-741/website/blog-examples-from-docusaurus to docusaurus-issue-741/website/blog to see the example blog posts on your site.

Done in 0.42s.
Alexs-MacBook-Pro-2:docusaurus-issue-741 alexlopez$ cd website
Alexs-MacBook-Pro-2:website alexlopez$ mv blog-examples-from-docusaurus/ blog
Alexs-MacBook-Pro-2:website alexlopez$ mv ../docs-examples-from-docusaurus/ ../docs
Alexs-MacBook-Pro-2:website alexlopez$ yarn start
yarn start v0.19.1
$ docusaurus-start
Docusaurus server started on port 3000
LiveReload server started on port 35729
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 1, attempted to resolve relative to "/Users/alexlopez/Desktop/uikit-react/docusaurus-issue-741/website/core"
    at /usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/docusaurus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:103:45)
    at loader (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/docusaurus/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

looks like yarn is incompatible with a module as well?

**Comment by JoelMarcey** [comment]
It looks like you are using a very old version of `yarn` - v0.19.1. It's probably not supported. We should document that like we did with `node` in the documentation.

Can you give me the versions you have of the following?

[joelm@kangkai-mbp:~/dev/docusaurus-issue-741/website]  $ yarn --version
1.5.1
[joelm@kangkai-mbp:~/dev/docusaurus-issue-741/website]  $ node --version
v8.11.1
[joelm@kangkai-mbp:~/dev/docusaurus-issue-741/website]  $ npm --version
6.0.0

Also, what happens if you run `npm start` instead of `yarn start`?

**Comment by vacarsu** [comment]
Yeah I just noticed that and am updating yarn now when I compared our version numbers.
node version is 10.0.0
npm version is 5.6.0

**Comment by JoelMarcey** [comment]
I hope upgrading `yarn` works and, if so, we should update the docs saying that `yarn 1.5` should be the minimum.

Interested in updating step 1 here: https://docusaurus.io/docs/en/installation with a PR? 😄

**Comment by vacarsu** [comment]
Aha! updating yarn fixed the issue. Sure I can do that PR.

**Comment by JoelMarcey** [comment]
I am going to close this out. Thanks for the PR.
