### ISSUE TITLE
line break in markdown table

### ISSUE THREAD

**Issue by wanghaisheng** [facebook/docusaurus#7614]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I  got a md  like this, there are 3 rows and in one column it may contain more than 1 line 
I use a </br> to do break

```

**HL7** | **优点** | **缺点**
---- | ---- | -----
FHIR | *   快速且易于实施，简洁且易于理解</br>*   统一数据模型和面向对象建模</br>*   提供很多开源实现库和例子，易于开发</br>*   支持web标准-XML，JSON，HTTP，OAuth等</br>*   支持RESTful架构，也支持消息和文档等框架</br>*  | 国内暂时缺少本地化实施统一规范，相关组织正推进
V2 | *   提供了一个基于语法的标准化接口的框架</br>*   有较多工具可供使用</br>*   提供了标准的开发方法</br> |*   只提供了消息的规范</br>*   只提供了80%接口的规范</br>*   没有标准的术语,复杂神秘的编码规则</br>*   没有考虑国际化支持</br>*   不易定制和扩展</br>
V3 | *   提供了基于语义的标准化接口框架，提高了识别的一致性</br>*   提供了统一的数据模型</br>*   采用面向对象的建模技术</br> | *   HL7官网已停止版本更新</br>*   实施非常复杂，国内暂无本地化规范</br>*   学习曲线陡，成本高</br>

```
but 

Compiled with problems:X

ERROR in ./docs/c1.md

Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: /Users/wenke/daily-test/fhir-handbook/facebook/docs/c1.md: Expected corresponding JSX closing tag for <em>. (75:82)

is this a bug  or i miss the best practice to write table markdown in docusaurus

### Steps to reproduce

have tried 
https://mdxjs.com/playground/
failed 

### Expected behavior

success parse

### Actual behavior

  73 | <tr parentName="tbody">
  74 | <td parentName="tr" {...{"align":null}}>{`FHIR`}</td>
> 75 | <td parentName="tr" {...{"align":null}}><em parentName="td">{`   快速且易于实施，简洁且易于理解`}</br></em>{`   统一数据模型和面向对象建模`}</br><em parentName="td">{`   提供很多开源实现库和例子，易于开发`}</br></em>{`   支持web标准-XML，JSON，HTTP，OAuth等`}</br><em parentName="td">{`   支持RESTful架构，也支持消息和文档等框架`}</br></em></td>
     |                                                                                   ^
  76 | <td parentName="tr" {...{"align":null}}>{`国内暂时缺少本地化实施统一规范，相关组织正推进`}</td>
  77 | </tr>
  78 | <tr parentName="tbody">
    at instantiate (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:72:32)
    at constructor (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:358:12)
    at Object.raise (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:3341:19)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7991:16)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7953:32)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7953:32)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7953:32)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7953:32)
    at Object.jsxParseElementAt (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:7953:32)
    at Object.jsxParseElement (/Users/wenke/daily-test/fhir-handbook/facebook/node_modules/@babel/parser/lib/index.js:8022:17)

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, `</br>` is not a valid tag in either HTML or JSX. MDX uses JSX, so you need to use valid JSX syntax, i.e. `<br />`. See https://docusaurus.io/zh-CN/docs/markdown-features/react

**Comment by wanghaisheng** [comment]
wonderful
