### ISSUE TITLE
2.0.0-beta.22 breaks deploy to GitHub Pages (shallow update not allowed)

### ISSUE THREAD

**Issue by yechs** [facebook/docusaurus#7744]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Updating to docusaurus v2.0.0-beta.22 breaks my deployment to GitHub Pages.

The relevant commandline error follows:
```
[INFO] `git commit -m "Deploy website - based on 6f67bb9205e05e2d37ba6368e30774c48e6db78d"` code: 0
To github.com:yechs/website.git
 ! [remote rejected] master -> master (shallow update not allowed)
error: failed to push some refs to 'github.com:yechs/website.git'
[INFO] `git push --force origin master` code: 1
[ERROR] Deployment of the build output failed.
[ERROR] Error: Running "git push" command failed. Does the GitHub user account you are using have push access to the repository?
    at runDeploy (/Users/yeshu/Coding/Personal/website/node_modules/@docusaurus/core/lib/commands/deploy.js:168:19)
    at async Command.deploy (/Users/yeshu/Coding/Personal/website/node_modules/@docusaurus/core/lib/commands/deploy.js:189:13)
error Command failed with exit code 1.
```

According to the command line output, it looks like a shallow update problem. However, the weird thing is, docusaurus has been doing shallow clone deployments for almost a year now and has never failed before.
Relevant PR: https://github.com/facebook/docusaurus/pull/5748

### Logs

If you want a full log, there is one available from GitHub Actions (https://github.com/yechs/website/runs/7256462347)

And here is the successful log running `yarn deploy` on v2.0.0-beta.21 three days ago (https://github.com/yechs/website/runs/7204294330)

### Reproduction

Just to rule out the variables of GitHub Actions or GitHub changing their behavior:

I've ran `yarn deploy` locally on v2.0.0-beta.22 and it failed with the same message.
I have also manually reverted back to v2.0.0-beta.21 and ran `yarn deploy`, which functioned perfectly normal. (Note that it is doing the same shallow clone)

### Reproducible demo

https://github.com/yechs/website/

### Steps to reproduce

1. Run `yarn deploy`
2. Observe that it fails
3. `git checkout 193d6e0` to go back to docusaurus v2.0.0-beta.21
4. Run `yarn` to install dependencies
5. Run `yarn deploy`
6. Observe that it succeeds

### Expected behavior

Deployment continues to function as in v2.0.0-beta.21

### Actual behavior

Deployment fails. See log from [GitHub Actions](https://github.com/yechs/website/runs/7256462347).

### Your environment

- Public source code:
  - Source code at https://github.com/yechs/website/
  - Deployed to https://github.com/yechs/yechs.github.io/
- Public site URL:
- Docusaurus version used:
  - v2.0.0-beta.21
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
  - Ubuntu (GitHub Actions) with Node v16
  - MacOS with Node v16.15.1
  - Arch Linux with Node v16.14.2

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Looks like a bug with #7702?

**Comment by yechs** [comment]
Yes deploying with 0.0.0-5163 is fine. Could be related to this issue

**Comment by yechs** [comment]
I have taken a look at the PR content. It may be possible that by copying over local `.git/config`, the `remote` origin url is also copied over.

However, I'm deploying to a different repo other than the source repo, which has a different "origin" url. This causes a problem.

**Comment by Josh-Cena** [comment]
cc @ghostsquad Any ideas?

**Comment by yechs** [comment]
In my humble opinion, it would be counter-intuitive to copy git configs during deployment. 

It should be up to the CI to set up the desired git configuration environment, either via [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) or, in the case of more advanced configs such as gpg signing key, via global configuration

**Comment by ghostsquad** [comment]
The problem is that I don't want to just deploy via CI. A local deployment should be valid as well. Let me look at the error...

**Comment by Josh-Cena** [comment]
> A local deployment should be valid as well. 

You can always change your `deploy` script in package.json.

**Comment by ghostsquad** [comment]
I can submit a pull request to add a git configuration map to the main config file that is used for this operation. It would allow arbitrary configuration to be applied after the clone operation.

**Comment by ghostsquad** [comment]
> > A local deployment should be valid as well.
> 
> You can always change your `deploy` script in package.json.

literally the only thing I need to change is some simple stuff like my email, gpg key, etc. It shouldn't be necessary to reproduce the entirety of what's already being done just to inject some git config.

**Comment by yechs** [comment]
> literally the only thing I need to change is some simple stuff like my email, gpg key, etc. It shouldn't be necessary to reproduce the entirety of what's already being done just to inject some git config.

Here is an email thread from the Git developers that may be interesting for you to read. (https://lore.kernel.org/git/xmqqwnm12xv7.fsf@gitster.g/T/)

It would be a lot simpler to just use environment variables. 
There exists built-in variables for setting `user.email` and `user.name`. Then, ALL config fields can be set via the `GIT_CONFIG_KEY_<n>` and `GIT_CONFIG_VALUE_<n>` env vars (read [manual](https://git-scm.com/docs/git-config#Documentation/git-config.txt-GITCONFIGCOUNT))
So, for the signingkey, you can set `GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=user.signingkey GIT_CONFIG_VALUE_0=<your keyID>`

Alternatively, you can also use the [conditional includes](https://git-scm.com/docs/git-config#_conditional_includes) feature of git config.

Both methods seem to be more intuitive (i.e. less hacks) solutions to your problem. 
In the worst case, you can always use `patch-packages` to patch the deployment commands for your own.

**Comment by ghostsquad** [comment]
@yechs I think you are right. I'll file a revert for this.

**Comment by silverqx** [comment]
I have upgraded to the beta22 now and I can't deploy too, exactly the same problem.

**Comment by yechs** [comment]
> I have upgraded to the beta22 now and I can't deploy too, exactly the same problem.

I guess you'll have to wait until #7750 gets merged and hopefully they'll release a hotfix soon enough

**Comment by silverqx** [comment]
Fixed in rc1, deploying works well again thx

**Comment by veris-amoghbanta** [comment]
Still getting this error in 2.0.1.
```
[ERROR] Deployment of the build output failed.
[ERROR] Error: Running "git push" command failed. Does the GitHub user account you are using have push access to the repository?
    at runDeploy (.../node_modules/@docusaurus/core/lib/commands/deploy.js:158:19)
    at async Command.deploy (.../node_modules/@docusaurus/core/lib/commands/deploy.js:179:13)
```

**Comment by silverqx** [comment]
I have deployed two times using v2.0.1 and don't have any problems.
