### ISSUE TITLE
In version 2.1, the `npm run start` command breaks on Node 16 and 18

### ISSUE THREAD

**Issue by LoicPoullain** [facebook/docusaurus#8044]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

**Steps to reproduce:**
Use Node 16.14, 16.18 or 18.2 and run the following commands:
```
npx create-docusaurus@latest my-website classic
cd my-website
npm run start
```

We then get the following error:
```bash
[INFO] Starting the development server...
[ERROR] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/loicpoullain/Desktop/my-website/node_modules/parse5/dist/cjs/index.js from /Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/parsers/parse5-adapter.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/loicpoullain/Desktop/my-website/node_modules/parse5/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/parsers/parse5-adapter.js:14:16)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/index.js:41:27)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/plugin-content-blog/lib/feed.js:17:19)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/plugin-content-blog/lib/index.js:17:16)
    at module.exports (/Users/loicpoullain/Desktop/my-website/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:45:57)
    at /Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:99:60
    at Array.map (<anonymous>)
    at loadPluginConfigs (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:99:38)
    at async initPlugins (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/init.js:42:27)
    at async loadPlugins (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.1.0
Node version: v16.14.0

```

### Reproducible demo

https://github.com/FoalTS/foal/tree/master/docs on branch "no-index-google"

### Steps to reproduce

Use Node 16.14, 16.18 or 18.2 and run the following commands:
```
npx create-docusaurus@latest my-website classic
cd my-website
npm run start
```

### Expected behavior

The command should succeed and start the server.

### Actual behavior

The command prints this error:
```bash
[INFO] Starting the development server...
[ERROR] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/loicpoullain/Desktop/my-website/node_modules/parse5/dist/cjs/index.js from /Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/parsers/parse5-adapter.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/loicpoullain/Desktop/my-website/node_modules/parse5/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/parsers/parse5-adapter.js:14:16)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/cheerio/lib/index.js:41:27)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/plugin-content-blog/lib/feed.js:17:19)
    at Object.<anonymous> (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/plugin-content-blog/lib/index.js:17:16)
    at module.exports (/Users/loicpoullain/Desktop/my-website/node_modules/import-fresh/index.js:32:59)
    at normalizePluginConfig (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:45:57)
    at /Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:99:60
    at Array.map (<anonymous>)
    at loadPluginConfigs (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:99:38)
    at async initPlugins (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/init.js:42:27)
    at async loadPlugins (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/Users/loicpoullain/Desktop/my-website/node_modules/@docusaurus/core/lib/commands/start.js:42:19)
[INFO] Docusaurus version: 2.1.0
Node version: v16.14.0

```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node.js 16.14, 16.16, 18.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Max OS version 12.5 (Monterey)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by echarles** [comment]
Same issue here.

**Comment by echarles** [comment]
parse5 7.0.0 has just been released and a fix is already out with https://github.com/inikulin/parse5/pull/664

This may help

**Comment by Josh-Cena** [comment]
Yep, this is entirely an external issue: package A is importing package B and it breaks. Docusaurus doesn't control either. You can pin your transitive dependencies, or upgrade them again.
