### ISSUE TITLE
Unable to resolve "Unexpected: no Docusaurus route context found"

### ISSUE THREAD

**Issue by milesj** [facebook/docusaurus#8072]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Docusaurus build passes locally, but fails in CI and errors with:

### Reproducible demo

https://github.com/moonrepo/moon/pull/304

### Steps to reproduce

I'm not entirely sure what caused it. This PR started failing with the error: https://github.com/moonrepo/moon/pull/304

However, I've tried:

- Cleaning my local state to try and reproduce, no luck. Works locally just fine.
- Updating docusaurus to v2.1, was on v2.0. Did not help.
- Reverted `docusaurus.config.js` changes. Still failed.
- Different Node.js versions.

### Expected behavior

It builds correctly in CI.

### Actual behavior

It fails in CI with the following errors:

```
[website:build] [success] [webpackbar] Client: Compiled successfully in 35.49s
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/bin.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/check.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/ci.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/clean.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/dep-graph.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/generate.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/init.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/migrate.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/migrate/from-package-json.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/overview.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/project.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/project-graph.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/query.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/query/projects.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/query/touched-files.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/run.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/setup.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/sync.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/commands/teardown.
[website:build] [ERROR] Docusaurus server-side rendering could not render static page with path /docs/comparison.
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] Error: Unexpected: no Docusaurus route context found
[website:build] [ERROR] Unable to build website for locale en.
[website:build] [ERROR] Error: Failed to compile with errors.
[website:build]     at /home/runner/work/moon/moon/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
[website:build]     at /home/runner/work/moon/moon/node_modules/webpack/lib/MultiCompiler.js:554:14
[website:build]     at processQueueWorker (/home/runner/work/moon/moon/node_modules/webpack/lib/MultiCompiler.js:491:6)
[website:build]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[website:build] [INFO] Docusaurus version: 2.1.0
[website:build] Node version: v16.17.0
```

### Your environment

- Public source code: https://github.com/moonrepo/moon/pull/304
- Public site URL:
- Docusaurus version used: 2.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16/18
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu latest

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by steventilator** [comment]
I am facing the same error. It builds locally, apparently without errors, but when I open the site, I am greeted by this message: 

This page crashed.
Unexpected: no Docusaurus route context found

The browser console logs:

```
Uncaught Error: Unexpected: no Docusaurus route context found
    at useRouteContext (useRouteContext.js?4ab8:6:1)
    at PluginHtmlClassNameProvider (metadataUtils.tsx?5c9e:102:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22776:1)

The above error occurred in the <PluginHtmlClassNameProvider> component:

    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:52)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:31:392)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:34:60)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:18:488)
    at TabGroupChoiceProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/tabGroupChoice.js:14:1380)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/announcementBar.js:23:459)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/colorMode.js:25:1255)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:65:19)
    at LayoutProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/Provider/index.js:19:741)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:23:33)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at Error (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Error/index.js:15:641)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:26:241)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7320)
```

I am on version 2.1.0.

**Comment by slorber** [comment]
@milesj can I get the exact code that produced which CI failure exactly? Because looking at the linked PR, it is merged and all CI is green so it's hard to inspect anything 🤷‍♂️ 

---

Same @steventilator, I will need a repro. If your site can build and only fail later, that looks like a different behavior than the one reported initially (where the CI fails).

---

Make sure to remove all your swizzled components and attempt a new build, maybe it is due to unsafe swizzle customizations?

**Comment by milesj** [comment]
@slorber Yeah, it "just started working" randomly. I'm not sure what caused it, but...

Here's an example failing run: https://github.com/moonrepo/moon/actions/runs/3018212049/jobs/4852904913

And this is basically the code changes that were failing: https://github.com/moonrepo/moon/pull/304/commits/1cfbe9c8343f3de45e4d2c159582824477095aed

**Comment by slorber** [comment]
🤷‍♂️ this seems unexpected. Maybe running "docusaurus clear" or whatever solved the problem. Maybe the CI cache auto clears on fails?

Going to close for now if nobody has the build issue anymore, but we can reopen if this happens again.

---

@steventilator your issue is different. If you have a runtime issue (ie error only appearing in console logs) that's a totally different case and you need to at least provide me the website URL to inspect it, preferably also some repro source code.
