### ISSUE TITLE
TypeError: Invalid URL while trying to build with sitemap not set to false

### ISSUE THREAD

**Issue by chreniuc** [facebook/docusaurus#8116]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm using v2.1.0 and I've noticed that I get an error when I want to create a production build with sitemap not set to false, the `yarn run start` works with no issue, but when I run `yarn run build` I get a build error. If I set the `sitemap` option to false, it builds without errors. I use it as a blog only.

### Steps to reproduce

```bash
git clone https://gitlab.com/chreniuc/hreniuc-dev -b failed_build
cd hreniuc-dev
yarn install
yarn run build
```

### Expected behavior

To build successfully.

### Actual behavior

I'm receiving this error:

```
[ERROR] Unable to build website for locale en.
[ERROR] TypeError: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:553:9)
    at new URL (node:internal/url:629:5)
    at new URL (node:internal/url:626:22)
    at normalizeURL (/path/node_modules/sitemap/dist/lib/utils.js:274:15)
    at SitemapStream._transform (/path/node_modules/sitemap/dist/lib/sitemap-stream.js:74:87)
    at SitemapStream.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at SitemapStream.Writable.write (node:internal/streams/writable:334:10)
    at /path/node_modules/@docusaurus/plugin-sitemap/lib/createSitemap.js:44:57
    at Array.forEach (<anonymous>)
    at createSitemap (/path/node_modules/@docusaurus/plugin-sitemap/lib/createSitemap.js:44:20)
    at Object.postBuild (/path/node_modules/@docusaurus/plugin-sitemap/lib/index.js:23:72)
    at /path/node_modules/@docusaurus/core/lib/commands/build.js:171:22
    at Array.map (<anonymous>)
    at buildLocale (/path/node_modules/@docusaurus/core/lib/commands/build.js:167:31)
    at async tryToBuildLocale (/path/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
    at async mapAsyncSequential (/path/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/path/node_modules/@docusaurus/core/lib/commands/build.js:73:21)
[INFO] Docusaurus version: 2.1.0
Node version: v16.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your environment

- Public source code: https://gitlab.com/chreniuc/hreniuc-dev/-/tree/failed_build
- Public site URL:
- Docusaurus version used: 2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): v16.15.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 20.04.2 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
🤪 hard to understand but I figured it out:

```diff
- url: 'hreniuc.dev',
+ url: 'https://hreniuc.dev',
```

I guess the value you provide is fine and we should instead ensure that our normalization process will always normalize it to add the missing `https://` protocol

Anyone want to contribute this?

**Comment by Josh-Cena** [comment]
> normalize it to add the missing `https://` protocol

I don't think that's a totally safe thing to do. We should just throw on anything that doesn't pass `new URL()` (which I thought we do already).

**Comment by slorber** [comment]
Fine with both solutions. Agree it looks safer to ask user to always provide a protocol 👍 

Also thought it was the case 😅 Joi is just a pain

**Comment by forgeRW** [comment]
I'd like to work on this so here's my PR #8159 for your review

**Comment by a11rew** [comment]
Ahh should have probably put in a heads-up that I was working on this

**Comment by Josh-Cena** [comment]
Yeah, it's always a good idea to at least give a heads-up—especially since it's October😅
