### ISSUE TITLE
Servers aren't shutting down with CTRL+C

### ISSUE THREAD

**Issue by nebrelbug** [facebook/Docusaurus#831]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

(Docusaurus version via `npm outdated docusaurus` or `yarn outdated docusaurus`, OS, Node, npm, yarn)

### Steps to Reproduce

(Write your steps here:)

1. Run `npm start` inside the "website" directory of your project
2. Press CTRL+C
3. Run `npm start` again several times.
4. It will say: 
```
Port 3000 is in use
Port 3001 is in use
Port 3002 is in use ... etc.
```
4. And also say:
```
You already have a server listening on 35729
You should stop it and try again.
````

### Expected Behavior

I thought it would just shut down the server.

### Actual Behavior

It looks like all of the servers are still running, then it throws this error:
```

Request failed: { Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
```
### Reproducible Demo

https://github.com/nebrelbug/squirrelly-website

**Comment by yangshun** [comment]
Seems like a bug indeed. I narrowed down the issue to the `baseUrl`. Basically any `baseUrl` that's not `/` will cause the error. To unblock yourself now, you could use `/` for the `baseUrl` value now.

@endiliey any ideas?

**Comment by nebrelbug** [comment]
Thank you both! Sorry that I didn't realize it was because of the baseURL. Should I download the new version tomorrow then?

**Comment by nebrelbug** [comment]
I can now view the pages, but it still looks like the servers aren't shutting down. After a bit of Googling, it looks like it may just be a problem with Git Bash though.

**Comment by yangshun** [comment]
I have yet to release 1.3.2. Will do it tonight 🌞

**Comment by yangshun** [comment]
I have yet to release 1.3.2. Will do it tonight and let you know when I do 🌞

**Comment by yangshun** [comment]
@nebrelbug v1.3.2 has been released.

**Comment by nebrelbug** [comment]
Thanks! Finally got everything to work :)
