### ISSUE TITLE
This page crashed - url is not defined

### ISSUE THREAD

**Issue by Braunson** [facebook/docusaurus#8816]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Overview

I'm using the plugin `docusaurus-graphql-plugin` in order to generate my GraphQL docs from my `schema.graphql` file. It seems all other sessions of the generated docs are accessible except for `Objects` which throws the crash error.

Unable to share the private repository but can share the config. I also noticed the sidebar dropdown to show the pages does not show anything but it exists in the HTML it's just not visible. See image below
![image](https://user-images.githubusercontent.com/577273/227346816-9e610f0f-52f2-451f-a866-d27ddca96302.png)

If I attempt to build the docs `yarn docusaurus build` the same error appears
```
[ERROR] Docusaurus server-side rendering could not render static page with path /docs/GraphQL/Foobar-API/objects.
ReferenceError: url is not defined

[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /home/braunson/backend/docs/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /home/braunson/backend/docs/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/home/braunson/backend/docs/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Code

**docusaurus.config.js**
```js
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

/** @type {import('@docusaurus/types').Config} */
const config = {
  // .... boilerplate removed
  plugins: [
    require.resolve("@cmfcmf/docusaurus-search-local"),
    [
      "docusaurus-graphql-plugin",
      {
        schema: "schema.graphql",
        routeBasePath: "/docs/GraphQL/Foobar-API",
        sidebar: {
          label: "Foobar API",
          position: 1,
        },
      },
    ],
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: 'https://github.com/foobar/edit',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      navbar: {
        title: 'Home',
        logo: {
          alt: 'Home',
          src: 'img/logo.svg',
        },
        items: [
          {
            type: 'doc',
            docId: 'setup',
            position: 'left',
            label: 'Documentation',
          },{
            type: 'doc',
            docId: 'GraphQL/Foobar-API/enums',
            position: 'left',
            label: 'GQL Foobar API',
          },
    }),
};

module.exports = config;
```

**sidebar.js**
```js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  graphQlApiSidebar: [
    "GraphQL/Foobar-API/queries",
    "GraphQL/Foobar-API/mutations",
    "GraphQL/Foobar-API/objects",
    "GraphQL/Foobar-API/interfaces",
    "GraphQL/Foobar-API/enums",
    "GraphQL/Foobar-API/unions",
    "GraphQL/Foobar-API/inputObjects",
    "GraphQL/Foobar-API/scalars",
  ]
};

module.exports = sidebars;
```

### Console
```
Uncaught ReferenceError: url is not defined
    at MDXContent (objects.md?f292:3:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22779:1)
    at workLoopSync (react-dom.development.js?ac89:22707:1)
react-dom.development.js?ac89:20085 The above error occurred in the <MDXContent> component:

    at MDXContent (webpack-internal:///./docs/GraphQL/Foobar-API/objects.md:13:18328)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/MDXContent/index.js:13:34)
    at div
    at DocItemContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Content/index.js:25:315)
    at article
    at div
    at div
    at div
    at DocItemLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Layout/index.js:25:749)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at DocProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/doc.js:22:35)
    at DocItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/index.js:15:72)
    at RouteContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/routeContext.js:14:70)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:647:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:849:29)
    at div
    at main
    at DocPageLayoutMain (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/Layout/Main/index.js:14:41)
    at div
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at div
    at NavbarSecondaryMenuDisplayProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/display.js:19:327)
    at NavbarMobileSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarMobileSidebar.js:21:423)
    at NavbarSecondaryMenuContentProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/content.js:14:156)
    at NavbarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/navbarUtils.js:20:38)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:52)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:31:392)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:34:60)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:18:488)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/announcementBar.js:23:459)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/colorMode.js:25:1255)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:65:19)
    at LayoutProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/Provider/index.js:18:655)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:24:33)
    at DocPageLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/Layout/index.js:17:37)
    at DocsSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsSidebar.js:17:43)
    at DocsVersionProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsVersion.js:15:43)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at DocPage (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/index.js:21:788)
    at RouteContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/routeContext.js:14:70)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:647:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:849:29)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:647:29)
    at ClientLifecyclesDispatcher (webpack-internal:///./node_modules/@docusaurus/core/lib/client/ClientLifecyclesDispatcher.js:15:271)
    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:15:138)
    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:18:25)
    at BrowserContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/browserContext.js:19:126)
    at DocusaurusContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/docusaurusContext.js:19:495)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:26:241)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:266:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7320)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Reproducible demo

N/A

### Steps to reproduce

1. Create new project
2. Import the plugin `docusaurus-graphql-plugin`
3. Use the settings/sidebar I provided
4. Use an example `schema.graphql` file
5. Generate, build and serve the docs

### Expected behavior

Page should render

### Actual behavior

Page crashes with given error "url is not defined"

```
ERROR
url is not defined
ReferenceError: url is not defined
    at MDXContent (webpack-internal:///./docs/GraphQL/Foobar-API/objects.md:13:371261)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23959:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22774:12)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22702:5)
 ```

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.4.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 19.8.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04.2 LTS

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
Hi

Sorry but `docusaurus-graphql-plugin` is not an official plugin. Bugs related to non-official plugins should be reported to their respective repositories.

If you think there's a bug in Docusaurus core, then create a bug repro only using official plugins.
