### ISSUE TITLE
cannot render katex in side div element

### ISSUE THREAD

**Issue by xinhaiwang** [facebook/docusaurus#8838]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

cannot render katex in side div element

### Steps to reproduce

'<div>
$K_i$
<div>'

### Expected behavior

katex rendered

### Actual behavior

dispaly '$K_i$' literally

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by Josh-Cena** [comment]
Hi, you've given no context, but I suppose you will want to read https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability. In any case, this is not going to be a bug. Please use [discussions](https://github.com/facebook/docusaurus/discussions) instead for questions.

**Comment by xinhaiwang** [comment]
ERROR
ik is not defined
ReferenceError: ik is not defined
    at MDXContent (webpack-internal:///./geotech/JGJ94-2008/5/1.mdx:13:57912)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23959:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22771:12)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22702:5)

**Comment by xinhaiwang** [comment]
<div>
    $F_k$ —— 荷载效应标准组合下，作用于承台顶面的竖向力；<br/>
    $G_k$ —— 桩基承台和承台上土自重标准值，对稳定的地下水位以下部分应扣除水的浮力；<br/>
    $N_k$ —— 荷载效应标准组合轴心竖向力作用下，基桩或复合基桩的平均竖向力；<br/>
    $N_{ik}$ —— 荷载效应标准组合偏心竖向力作用下，第i基桩或复合基桩的竖向力；<br/>
    $M_{xk}$ 、$M_{yk}$ —— 荷载效应标准组合下，作用于承台底面，绕通过桩群形心的x、y主轴的力矩；<br/>
    $x_i$ 、$x_j$ 、$y_i$ 、$y_j$ —— 第i 、j 基桩或复合基桩至y 、x 轴的距离；<br/>
    $H_k$ —— 荷载效应标准组合下，作用于桩基承台底面的水平力；<br/>
    $H_{ik}$ —— 荷载效应标准组合下，作用于第 i 基桩或复合基桩的水平力；<br/>
    n —— 桩基中的桩数。
</div>

**Comment by xinhaiwang** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/20069410/228123335-c4d506ae-b0c5-4ea6-81a0-4633d1e875ae.png">

**Comment by xinhaiwang** [comment]
lol, closed so fast. loser

**Comment by xinhaiwang** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/20069410/228124309-3dc35bb0-fe6f-4135-b760-f024ac8acac9.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/20069410/228124373-3ffbf8df-206a-4230-9d9b-1e05b67bceec.png">

**Comment by xinhaiwang** [comment]
@Josh-Cena did you check the code?
