### ISSUE TITLE
Can't able to build Vanila docusaurus project

### ISSUE THREAD

**Issue by nigampatel** [facebook/docusaurus#8912]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm following the installation steps ttps://docusaurus.io/docs/installation.

Able to install the project by running `npm install`

Whoever, when I run the `npm run build`. I get following error.

`➜ npm run build     

> my-website@0.0.0 build
> docusaurus build
node:internal/modules/cjs/loader:400
      const err = new Error(
                  ^
Error: Cannot find module '/Users/nigam/Documents/workarea/test/my-website/node_modules/@babel/core/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/c316119/Documents/workarea/test/my-website/node_modules/@docusaurus/core/lib/server/translations/translationsExtractor.js:16:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/nigam/Documents/workarea/test/my-website/node_modules/@babel/core/package.json',
  requestPath: '@babel/core'
}

Node.js v18.12.1`

Any help would be appreciated.

### Steps to reproduce

1 . npx create-docusaurus@latest my-website classic
2 cd my-website
3. npm run start

### Expected behavior

No errors.

### Actual behavior

Error: Cannot find module '/Users/nigam/Documents/workarea/test/my-website/node_modules/@babel/core/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:400:19)
    at Module._findPath (node:internal/modules/cjs/loader:613:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/c316119/Documents/workarea/test/my-website/node_modules/@docusaurus/core/lib/server/translations/translationsExtractor.js:16:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/nigam/Documents/workarea/test/my-website/node_modules/@babel/core/package.json',
  requestPath: '@babel/core'
}

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by nigampatel** [comment]
moving this to discuss board.
