### ISSUE TITLE
Hook useDoc is called outside the <DocProvider>

### ISSUE THREAD

**Issue by psygo** [facebook/docusaurus#9010]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I'm trying to upgrade my Docusaurus in my OpenAPI project, with [docusaurus-openapi-docs](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) plugin but right now, there seem to be many conflicts.

This is the error I'm getting:

```error
Hook useDoc is called outside the <DocProvider>. 
ReactContextError
    at useDoc (webpack-internal:///./node_modules/@docusaurus/theme-classic/node_modules/@docusaurus/theme-common/lib/contexts/doc.js:28:112)
    at DocItemMetadata (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Metadata/index.js:13:139)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14986:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17812:13)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19050:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4057:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23960:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22775:12)
```

### Steps to reproduce

I cannot share my whole project because I'm not allowed to, but here is the minimal setup to make it appear locally to me:

```sh
rm -r node_modules/

npm i \
  @docusaurus/core@2.1.0 \
  @docusaurus/preset-classic@2.1.0 \
  @docusaurus/theme-live-codeblock@2.1.0 \
  docusaurus-plugin-openapi-docs \
  docusaurus-theme-openapi-docs

npm run clear
npm run docusaurus clean-api-docs all
npm run docusaurus gen-api-docs all
npm run docusaurus start
```

### Expected behavior

No errors from internal Docusaurus dependencies...

### Actual behavior

The error mentioned above

### Your environment

- Public source code: cannot share
- Public site URL: https://docs.verticalinsure.com/docs/overview/getting-started
- Docusaurus version used: right now I'm using 2.0.1, but anything above it seems to generate the mentioned error
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 113, Node.js 9.5.0, Node 19.7.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Archcraft 6.3.1-arch2-1

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by TheCatLady** [comment]
See https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#compatibility-matrix
