### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by esakarya** [facebook/docusaurus#9215]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

All time i am getting following error when i try "npx create-docusaurus@latest my-website classic" or build or start any source documents.

Iam on ubuntu 22 LTS

`> docs-site@0.0.0 start
> node --max-old-space-size=11264 node_modules/@docusaurus/core/bin/docusaurus.mjs start

file:///root/docs-site/node_modules/@docusaurus/core/bin/docusaurus.mjs:30
process.env.BABEL_ENV ??= 'development';
                       ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
`

### Steps to reproduce

npx create-docusaurus@latest my-website classic
npm run build
npm start

### Expected behavior

run without error

### Actual behavior

run without error

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by esakarya** [comment]
ok my mistake. my nodjs ver is not latest.

**Comment by mubasher117** [comment]
Please add closed: question label to it and remove other labels as I'm unable to change them. Thank you!

**Comment by slorber** [comment]
Hey, how did you figure out your Node version was outdated?

Normally your package manager is supposed to tell you so 🤷‍♂️ 

We have this config on our packages:

```
  "engines": {
    "node": ">=16.14"
  }
```

**Comment by esakarya** [comment]
i was install ubuntu's default packgage, its getting this problem. i later install nodejs from directly site. then problem is fixed.
