### ISSUE TITLE
Error loading Docusaurus for the first time

### ISSUE THREAD

**Issue by marcote** [facebook/Docusaurus#955]
## 🐛 Bug Report

Error: Cannot find module '/Users/marcote/code/dev/test-pages/website/node_modules/docusaurus/lib/pages/website/'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at removeModuleAndChildrenFromCache (/Users/marcote/code/dev/test-pages/website/node_modules/docusaurus/lib/server/server.js:49:23)
    at /Users/marcote/code/dev/test-pages/website/node_modules/docusaurus/lib/server/server.js:286:7
    at Layer.handle [as handle_request] (/Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/layer.js:95:5)
    at /Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/marcote/code/dev/test-pages/website/node_modules/express/lib/router/index.js:335:12)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## To Reproduce

1. create folder (eg: test-pages)
1. run `npx docusaurus-init`   (installing and then executing globally yields the same error)
1. rename folders to /docs and blog
1. run `yarn start` 

yarn --version                                                    
1.9.4
npm --version
6.2.0
node --version
10.9.0

macOS 10.13.6

## Expected behavior

A sample site running in port 3000 

## Actual Behavior

Errors.
<img width="1071" alt="screen shot 2018-09-11 at 5 31 02 pm" src="https://user-images.githubusercontent.com/2897427/45385942-813b7e00-b5e8-11e8-8c0f-8ebbc04f2aac.png">

Thanks!!

**Comment by endiliey** [comment]
I couldn't reproduce. See this 👇 

https://asciinema.org/a/NK7STe6Q2RWGmqrSoHlGXJ13M

Please send a reproducible repo

**Comment by marcote** [comment]
@endiliey 
I'm starting to think is an environment issue. I wasn't able to repro in another laptop. I'll close it. Thank you!
