### ISSUE TITLE
When multiple i18n are configured, the plug-in will report an error when using the Link tag.

### ISSUE THREAD

**Issue by CodFrm** [facebook/docusaurus#9957]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Using the Link tag in the plug-in will report the following error:

```
Error: Unable to build website for locale zh-CN.
    at tryToBuildLocale (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at async mapAsyncSequential (/Users/codfrm/Code/my-website/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Docusaurus found broken links!
  
  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
  
  Exhaustive list of all broken links found:
  - Broken link on source page path = /test:
     -> linking to /zh-CN/test/2
  - Broken link on source page path = /test/2:
     -> linking to /zh-CN/test/2
  
      at throwError (/Users/codfrm/Code/my-website/node_modules/@docusaurus/logger/lib/index.js:79:11)
      at reportBrokenLinks (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:242:47)
      at handleBrokenLinks (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/server/brokenLinks.js:274:5)
      at buildLocale (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:192:47)
      at async tryToBuildLocale (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:46:20)
      at async mapAsyncSequential (/Users/codfrm/Code/my-website/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
      at async Command.build (/Users/codfrm/Code/my-website/node_modules/@docusaurus/core/lib/commands/build.js:82:21)
}

[INFO] Docusaurus version: 3.1.1
Node version: v20.11.1
```

### Steps to reproduce

Below is a reproducible sample：

[test.zip](https://github.com/facebook/docusaurus/files/14622450/test.zip)

### Expected behavior

No error is reported and the alternate in `build/zh-CN/test/index.html` is generated correctly.

### Actual behavior

An error is reported and the alternate in `build/zh-CN/test/index.html` generates multiple slashes

```
    <link
      data-rh="true"
      rel="alternate"
      href="https://your-docusaurus-site.example.com/zh-CN//test"
      hreflang="zh-CN"
    />
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 3.1.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Edge 122.0.2365.80,Nodejs v20.11.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS 14.0 (23A344)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by slorber** [comment]
The reported errors are correct, and you can see the problem if you run your site with `yarn start --locale zh-CN`

This is because the localized variant of your site is using `baseUrl: '/zh-CN/'` automatically.

Currently, it is the responsibility of plugin authors to add the site baseUrl to the route config. If you do this, it will work:

```js
    async contentLoaded({ content, actions }): Promise<void> {
      const { addRoute } = actions;
      addRoute({
        path: context.baseUrl+"test",
        component: "@theme/Test",
      });

      addRoute({
        path: context.baseUrl+"/test/2",
        component: "@theme/Test",
      });
    },
```

I'll look into simplifying this later, and try to make your code work, but for now this is the current state of how things work, and changing this behavior would be a breaking change.
